<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="rastend" Comment="Subapplication Type">
	<Identification Standard="61499-2" Description="Copyright (c) 2024 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2024-10-23">
	</VersionInfo>
	<CompilerInfo packageName="MyLib::sys">
	</CompilerInfo>
	<SubAppInterfaceList>
		<Plugs>
			<AdapterDeclaration Name="OUT" Type="adapter::types::unidirectional::AX"/>
		</Plugs>
		<Sockets>
			<AdapterDeclaration Name="IN" Type="adapter::types::unidirectional::AX"/>
		</Sockets>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="E_T_FF" Type="adapter::events::unidirectional::AX_T_FF" x="-11000" y="-1300">
		</FB>
		<FB Name="E_SWITCH" Type="adapter::events::unidirectional::AX_SWITCH" x="-12300" y="-1300">
		</FB>
		<Comment Comment="soll beim Loslassen gestarte t werden !" x="-12600" y="-1800" width="3000" height="366.67"/>
		<EventConnections>
			<Connection Source="E_SWITCH.EO0" Destination="E_T_FF.CLK" dx1="320"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="IN" Destination="E_SWITCH.G" dx1="2833.33"/>
			<Connection Source="E_T_FF.Q" Destination="OUT" dx1="7540"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
