// ISO-Designer ISO 11783   Version 5.7.1.6514 Bucher Automation AG
// Do not change!

#define WorkingSet_0_Offset                                     1
#define Macro_1_Offset                                         21
#define Macro_2_Offset                                         34
#define Macro_3_Offset                                         47
#define Macro_4_Offset                                         60
#define Macro_5_Offset                                         73
#define Macro_6_Offset                                         86
#define Macro_7_Offset                                         99
#define Macro_8_Offset                                        112
#define Macro_9_Offset                                        125
#define DataMask_M3_Offset                                    138
#define DataMask_M4_Offset                                    164
#define DataMask_M1_Offset                                    232
#define DataMask_M2_Offset                                    294
#define DataMask_M5_Offset                                    332
#define Container_M1_weight_Offset                            382
#define Container_W1_flow_factor_old_Offset                   422
#define Container_M1_speed_Offset                             468
#define Container_W1_actual_quantity_Offset                   502
#define Container_M1_percent_Offset                           542
#define Container_M1_kg_ha_Offset                             576
#define Container_M1_filllevel_Offset                         610
#define Container_W1_flow_factor_Offset                       644
#define Container_M1_electric_motor_Offset                    696
#define Container_W1_target_quantity_Offset                   730
#define Container_W1_engine_speed_rpm_Offset                  770
#define Container_M2_target_quantity_Offset                   804
#define Container_W1_header_Offset                            844
#define Container_M2_flow_factor_Offset                       866
#define Container_M2_calibration_area_Offset                  906
#define Container_Picture_fertilzier_bin_full_M1_filllevel_Offset    946
#define Container_Picture_fertilzier_bin_empty_M1_filllevel_Offset    962
#define SoftKeyMask_S1_Offset                                 978
#define SoftKeyMask_S2_Offset                                1004
#define SoftKeyMask_S3_Offset                                1030
#define SoftKeyMask_S4_Offset                                1056
#define SoftKey_stop_Offset                                  1082
#define SoftKey_100_percent_Offset                           1095
#define SoftKey_plus_percent_Offset                          1108
#define SoftKey_start_Offset                                 1121
#define SoftKey_minus_percent_Offset                         1134
#define SoftKey_main_Offset                                  1147
#define SoftKey_debug_Offset                                 1160
#define SoftKey_calibration_run_Offset                       1173
#define SoftKey_settings_Offset                              1186
#define SoftKey_5009_Offset                                  1199
#define SoftKey_5010_Offset                                  1206
#define SoftKey_5011_Offset                                  1213
#define SoftKey_5012_Offset                                  1220
#define SoftKey_5013_Offset                                  1227
#define SoftKey_5014_Offset                                  1234
#define SoftKey_5015_Offset                                  1241
#define SoftKey_5016_Offset                                  1248
#define SoftKey_5017_Offset                                  1255
#define SoftKey_5018_Offset                                  1262
#define SoftKey_5019_Offset                                  1269
#define SoftKey_5020_Offset                                  1276
#define SoftKey_5021_Offset                                  1283
#define SoftKey_5022_Offset                                  1290
#define SoftKey_5023_Offset                                  1297
#define SoftKey_5024_Offset                                  1304
#define SoftKey_5025_Offset                                  1311
#define SoftKey_5026_Offset                                  1318
#define SoftKey_5027_Offset                                  1325
#define Button_M1_reset_Offset                               1332
#define Button_6001_Offset                                   1351
#define Button_M4_manuel_start_Offset                        1364
#define Button_M1_restart_Offset                             1383
#define Button_M4_manuel_stop_Offset                         1402
#define Button_6005_Offset                                   1421
#define Button_6006_Offset                                   1436
#define Button_W1_stop_Offset                                1451
#define Button_M1_refresh_Offset                             1470
#define Button_W1_accept_Offset                              1489
#define Button_M2_start_Offset                               1508
#define Button_M4_auto_Offset                                1527
#define Button_M2_calibration_area_1a_Offset                 1546
#define Button_M2_calibration_area_5a_Offset                 1565
#define Button_M2_calibration_area_10a_Offset                1584
#define InputNumber_W1_actual_quantity_Offset                1603
#define InputNumber_9001_Offset                              1641
#define InputNumber_M2_target_quantity_Offset                1679
#define InputNumber_M2_flow_factor_Offset                    1717
#define InputNumber_9004_Offset                              1755
#define InputNumber_M4_motor_speed_Offset                    1793
#define InputNumber_M3_speed_Offset                          1831
#define InputNumber_M4_auto_Offset                           1869
#define OutputString_M3_radar_speed_kmh_Offset               1907
#define OutputString_M3_settings_header_Offset               1928
#define OutputString_M1_kg_ha_Offset                         1956
#define OutputString_M1_filllevel_Offset                     1978
#define OutputString_W1_actual_quantity_g_Offset             2004
#define OutputString_W1_target_quantity_g_Offset             2022
#define OutputString_W1_accept_Offset                        2040
#define OutputString_M4_debug_Offset                         2068
#define OutputString_M1_header_Offset                        2096
#define OutputString_M2_header_Offset                        2122
#define OutputString_M1_reset_Offset                         2150
#define OutputString_W1_flow_factor_g_U_Offset               2172
#define OutputString_SK_start_Offset                         2192
#define OutputString_SK_stop_Offset                          2214
#define OutputString_M1_weight_Offset                        2235
#define OutputString_M1_percent_Offset                       2254
#define OutputString_M1_electric_motor_Offset                2272
#define OutputString_M4_start_Offset                         2294
#define OutputString_W1_flow_factor_old_Offset               2316
#define OutputString_M3_speed_Offset                         2344
#define OutputString_flow_factor_old_g_U_Offset              2381
#define OutputString_W1_actual_quantity_header_Offset        2401
#define OutputString_W1_flow_factor_Offset                   2427
#define OutputString_W1_target_quantity_Offset               2455
#define OutputString_W1_flow_factor_old_old_Offset           2482
#define OutputString_W1_engine_speed_rpm_Offset              2502
#define OutputString_M2_target_quantity_kg_Offset            2524
#define OutputString_W1_header_Offset                        2543
#define OutputString_W1_stop_Offset                          2560
#define OutputString_M2_target_quantity_header_Offset        2581
#define OutputString_M2_start_Offset                         2609
#define OutputString_11031_Offset                            2631
#define OutputString_M2_flow_factor_header_Offset            2652
#define OutputString_M2_calibration_area_Offset              2680
#define OutputString_M2_calibration_area_1a_Offset           2709
#define OutputString_M2_calibration_area_5a_Offset           2729
#define OutputString_M2_calibration_area_10a_Offset          2749
#define OutputString_M4_manuel_Offset                        2770
#define OutputString_M4_engine_speed_manuel_Offset           2798
#define OutputString_M4_auto_Offset                          2831
#define OutputString_M2_flow_factor_g_U_Offset               2852
#define OutputString_M4_speed_auto_Offset                    2872
#define OutputString_M4_rpm_Offset                           2905
#define OutputString_W1_flow_factor_new_Offset               2927
#define OutputNumber_W1_flow_factor_Offset                   2947
#define OutputNumber_W1_flow_factor_old_Offset               2976
#define OutputNumber_M1_speed_Offset                         3005
#define OutputNumber_M1_percent_Offset                       3034
#define OutputNumber_M1_weight_Offset                        3063
#define OutputNumber_M1_electric_motor_Offset                3092
#define OutputNumber_W1_target_quantity_Offset               3121
#define OutputNumber_W1_engine_speed_rpm_Offset              3150
#define OutputNumber_12014_Offset                            3179
#define Line_13000_Offset                                    3208
#define Rectangle_M1_percent_Offset                          3219
#define Rectangle_M1_speed_Offset                            3232
#define Rectangle_M1_kg_ha_Offset                            3245
#define Rectangle_M1_filllevel_Offset                        3258
#define Rectangle_M1_weight_Offset                           3271
#define Rectangle_M1_electric_motor_Offset                   3284
#define Rectangle_W1_flow_factor_old_Offset                  3297
#define Rectangle_M2_target_quantity_Offset                  3310
#define Rectangle_W1_actual_quantity_Offset                  3323
#define Rectangle_W1_flow_factor_Offset                      3336
#define Rectangle_W1_target_quantity_Offset                  3349
#define Rectangle_W1_engine_speed_rpm_Offset                 3362
#define Rectangle_W1_header_Offset                           3375
#define Rectangle_M2_flow_factor_Offset                      3388
#define Rectangle_M2_calibration_area_Offset                 3401
#define weight_W1_actual_quantity_Offset                     3414
#define _100_percent_softkeys_Offset                         4705
#define debug_softkeys_Offset                                5996
#define fertilzier_bin_W1_flow_factor_old_Offset             7287
#define plus_percent_softkeys_Offset                         8578
#define minus_percent_softkeys_Offset                        9869
#define fertilzier_bin_softkeys_Offset                      11160
#define measuring_cup_softkeys_Offset                       12451
#define settings_softkeys_Offset                            13742
#define Picture_Tractor_forward_side_M1_speed_Offset        15033
#define Picturere_Graphic_refresh_Offset                    16324
#define Picture_Graphic_restart_Offset                      17615
#define Picture_fertilzier_bin_empty_M1_filllevel_Offset    18906
#define Picture_M1_weight_Offset                            20197
#define Picture_application_rate_per_area_M1_kg_ha_Offset   21488
#define Picture_application_rate_per_area_M1_percent_Offset  22779
#define Picture_fertilzier_bin_full_M1_filllevel_Offset     24070
#define Picture_M1_electric_motor_Offset                    25361
#define fertilzier_bin_W1_flow_factor_Offset                26652
#define weight_W1_target_quantity_Offset                    27943
#define Electric_motor_W1_engine_speed_rpm_Offset           29234
#define weight_20031_Offset                                 30525
#define application_rate_per_area_M2_target_quantity_Offset  31816
#define application_rate_per_area_20039_Offset              33107
#define fertilzier_bin_M2_flow_factor_Offset                34398
#define fertilzier_bin_20041_Offset                         35689
#define NumberVariable_normal_speed_Offset                  36980
#define NumberVariable_bool_selected_speed_Offset           36987
#define NumberVariable_target_quantity_calibration_run_Offset  36994
#define NumberVariable_selected_speed_Offset                37001
#define NumberVariable_engine_speed_manuel_Offset           37008
#define NumberVariable_weight_Offset                        37015
#define NumberVariable_rpm_Offset                           37022
#define NumberVariable_application_rate_percent_Offset      37029
#define NumberVariable_manuel_auto_speed_Offset             37036
#define NumberVariable_flow_factor_new_Offset               37043
#define NumberVariable_target_quantity_Offset               37050
#define NumberVariable_W1_actual_quantity_Offset            37057
#define NumberVariable_flow_factor_Offset                   37064
#define NumberVariable_application_rate_percent_old_Offset  37071
#define StringVariable_calibration_run_Offset               37078
#define FontAttributes_23000_Offset                         37101
#define FontAttributes_Header_Offset                        37109
#define FontAttributes_WindowMask_Offset                    37117
#define FontAttributes_23005_Offset                         37125
#define FontAttributes_reset_Offset                         37133
#define FontAttributes_string_start_stop_button_Offset      37141
#define FontAttributes_main_boxes_Offset                    37149
#define FontAttributes_23016_Offset                         37157
#define FontAttributes_Header_white_Offset                  37165
#define LineAttributes_24000_Offset                         37173
#define LineAttributes_24001_Offset                         37181
#define LineAttributes_24002_Offset                         37189
#define LineAttributes_24003_Offset                         37197
#define LineAttributes_24004_Offset                         37205
#define LineAttributes_24005_Offset                         37213
#define LineAttributes_24006_Offset                         37221
#define LineAttributes_24007_Offset                         37229
#define LineAttributes_24009_Offset                         37237
#define LineAttributes_24010_Offset                         37245
#define LineAttributes_24011_Offset                         37253
#define LineAttributes_24013_Offset                         37261
#define LineAttributes_24014_Offset                         37269
#define LineAttributes_24015_Offset                         37277
#define LineAttributes_24016_Offset                         37285
#define FillAttributes_25000_Offset                         37293
#define FillAttributes_main_colour_Offset                   37301
#define FillAttributes_new_holland_blue_Offset              37309

#define ISO_OP_MEMORY_CLASS

#define ISO_OP_DefaultPool_Size  37317
extern const unsigned char ISO_OP_MEMORY_CLASS isoOP_DefaultPool[];

#define ISO_OP_DefaultPool_ObjectNumber    224
extern const unsigned long ISO_OP_MEMORY_CLASS isoOP_DefaultPool_Offset[];
extern const unsigned long ISO_OP_MEMORY_CLASS isoOP_DefaultPool_Offset_Id[];
#define ISO_OP_DefaultPool_Scale_Offset      1

#define ID_NULL  0xFFFF

#define TYPEID_WORKSET        0
#define TYPEID_DATAMASK       1
#define TYPEID_ALARMMASK      2
#define TYPEID_CONTAINER      3
#define TYPEID_SKEYMASK       4
#define TYPEID_SOFTKEY        5
#define TYPEID_BUTTON         6
#define TYPEID_INBOOL         7
#define TYPEID_INSTR          8
#define TYPEID_INNUM          9
#define TYPEID_INLIST        10
#define TYPEID_OUTSTR        11
#define TYPEID_OUTNUM        12
#define TYPEID_OUTLINE       13
#define TYPEID_OUTRECT       14
#define TYPEID_OUTELLIPSE    15
#define TYPEID_OUTPOLY       16
#define TYPEID_OUTMETER      17
#define TYPEID_OUTLINBAR     18
#define TYPEID_OUTARCBAR     19
#define TYPEID_OUTPICT       20
#define TYPEID_VARNUM        21
#define TYPEID_VARSTR        22
#define TYPEID_FONTATTR      23
#define TYPEID_LINEATTR      24
#define TYPEID_FILLATTR      25
#define TYPEID_INPATTR       26
#define TYPEID_OBJPTR        27
#define TYPEID_MACRO         28
#define TYPEID_AUXFUNC       29
#define TYPEID_AUXINP        30
#define TYPEID_AUXFUNC2      31
#define TYPEID_AUXINP2       32
#define TYPEID_AUXPTR        33
#define TYPEID_WINMASK       34
#define TYPEID_KEYGROUP      35
#define TYPEID_GRPHCTXT      36
#define TYPEID_OUTLIST       37
#define TYPEID_EXTINPATTR    38
#define TYPEID_COLORMAP      39
#define TYPEID_OBJLBLREF     40
#define TYPEID_EXTOBJDEF     41
#define TYPEID_EXTREFNAME    42
#define TYPEID_EXTOBJPTR     43
#define TYPEID_ANIMATION     44
#define TYPEID_COLORPAL      45
#define TYPEID_GRAPHDATA     46
#define TYPEID_WSSPECIAL     47
#define TYPEID_SCALEGRAPH    48

#define EV_REFRESH            0
#define EV_ACT                1
#define EV_DEACT              2
#define EV_SHOW               3
#define EV_HIDE               4
#define EV_ENABLE             5
#define EV_DISABLE            6
#define EV_CHGACTMASK         7
#define EV_CHGSKEYMASK        8
#define EV_CHGATTR            9
#define EV_CHGBKCOLOR        10
#define EV_CHGFONTATTR       11
#define EV_CHGLINEATTR       12
#define EV_CHGFILLATTR       13
#define EV_CHGCHILDLOC       14
#define EV_CHGSIZE           15
#define EV_CHGVAL            16
#define EV_CHGPRIOR          17
#define EV_CHGENDPNT         18
#define EV_SELINPUT          19
#define EV_DESELINPUT        20
#define EV_ESC               21
#define EV_ENTERVAL          22
#define EV_ENTERCHGVAL       23
#define EV_KEYPRESS          24
#define EV_KEYRELEASE        25
#define EV_CHGCHILDPOS       26

#define CMD_HIDE_SHOW               160
#define CMD_ENABLE_DISABLE          161
#define CMD_SELECT_INPUT_OBJECT     162
#define CMD_CONTROL_AUDIO_DEVICE    163
#define CMD_SET_AUDIO_VOLUME        164
#define CMD_CHANGE_CHILD_LOCATION   165
#define CMD_CHANGE_SIZE             166
#define CMD_CHANGE_BACKGROUND_COLOR 167
#define CMD_CHANGE_NUMERIC_VALUE    168
#define CMD_CHANGE_END_POINT        169
#define CMD_CHANGE_FONT_ATTRIBUTES  170
#define CMD_CHANGE_LINE_ATTRIBUTES  171
#define CMD_CHANGE_FILL_ATTRIBUTES  172
#define CMD_CHANGE_ACTIVE_MASK      173
#define CMD_CHANGE_SOFT_KEY_MASK    174
#define CMD_CHANGE_ATTRIBUTE        175
#define CMD_CHANGE_PRIORITY         176
#define CMD_CHANGE_LIST_ITEM        177
#define CMD_CHANGE_STRING_VALUE     179
#define CMD_CHANGE_CHILD_POSITION   180
#define CMD_SET_OBJECT_LABEL        181
#define CMD_CHANGE_POLYGON_POINT    182
#define CMD_CHANGE_POLYGON_SCALE    183
#define CMD_GRAPHICS_CONTEXT        184
#define CMD_GET_ATTRIBUTE           185
#define CMD_SELECT_COLOURMAP_OR_PALETTE 186
#define CMD_EXECUTE_EXTENDED_MACRO  188
#define CMD_LOCK_UNLOCK_MASK        189
#define CMD_EXECUTE_MACRO           190

#define COLOR_BLACK       0
#define COLOR_WHITE       1
#define COLOR_GREEN       2
#define COLOR_TEAL        3
#define COLOR_MAROON      4
#define COLOR_PURPLE      5
#define COLOR_OLIVE       6
#define COLOR_SILVER      7
#define COLOR_GREY        8
#define COLOR_BLUE        9
#define COLOR_LIME       10
#define COLOR_CYAN       11
#define COLOR_RED        12
#define COLOR_MAGENTA    13
#define COLOR_YELLOW     14
#define COLOR_NAVY       15

#define FLOAT_1      0x00, 0x00, 0x80, 0x3F
#define FLOAT_10     0x00, 0x00, 0x20, 0x41
#define FLOAT_100    0x00, 0x00, 0xC8, 0x42
#define FLOAT_1000   0x00, 0x00, 0x7A, 0x44
#define FLOAT_0_1    0xCD, 0xCC, 0xCC, 0x3D
#define FLOAT_0_01   0x0A, 0xD7, 0x23, 0x3C
#define FLOAT_0_001  0x6F, 0x12, 0x83, 0x3A
