// ISO-Designer ISO 11783   Version 5.7.1.6514 Bucher Automation AG
// Do not change!

#define WorkingSet_0_Offset                                     1
#define Macro_1_Offset                                         21
#define Macro_2_Offset                                         34
#define Macro_3_Offset                                         47
#define Macro_4_Offset                                         60
#define Macro_5_Offset                                         73
#define Macro_6_Offset                                         86
#define Macro_7_Offset                                         99
#define Macro_8_Offset                                        112
#define Macro_9_Offset                                        125
#define DataMask_M3_Offset                                    138
#define DataMask_M4_Offset                                    164
#define DataMask_M1_Offset                                    214
#define DataMask_M2_Offset                                    270
#define DataMask_M5_Offset                                    308
#define Container_M1_weight_Offset                            358
#define Container_M3_radar_speed_Offset                       398
#define Container_M1_speed_Offset                             444
#define Container_M3_wheel_speed_Offset                       478
#define Container_W1_actual_quantity_Offset                   524
#define Container_M1_percent_Offset                           564
#define Container_M1_kg_ha_Offset                             598
#define Container_M1_filllevel_Offset                         632
#define Container_W1_flow_factor_Offset                       666
#define Container_M1_electric_motor_Offset                    706
#define Container_W1_target_quantity_Offset                   740
#define Container_W1_engine_speed_percent_Offset              774
#define Container_W1_engine_speed_rpm_Offset                  808
#define Container_M2_target_quantity_Offset                   842
#define Container_W1_header_Offset                            882
#define Container_M2_flow_factor_Offset                       904
#define Container_M2_calibration_area_Offset                  938
#define Container_Picture_fertilzier_bin_full_M1_filllevel_Offset    978
#define Container_Picture_fertilzier_bin_empty_M1_filllevel_Offset    994
#define SoftKeyMask_S1_Offset                                1010
#define SoftKeyMask_S2_Offset                                1036
#define SoftKeyMask_S3_Offset                                1062
#define SoftKeyMask_S4_Offset                                1088
#define SoftKey_stop_Offset                                  1114
#define SoftKey_100_percent_Offset                           1127
#define SoftKey_plus_percent_Offset                          1140
#define SoftKey_start_Offset                                 1153
#define SoftKey_minus_percent_Offset                         1166
#define SoftKey_main_Offset                                  1179
#define SoftKey_debug_Offset                                 1192
#define SoftKey_calibration_run_Offset                       1205
#define SoftKey_settings_Offset                              1218
#define SoftKey_5009_Offset                                  1231
#define SoftKey_5010_Offset                                  1238
#define SoftKey_5011_Offset                                  1245
#define SoftKey_5012_Offset                                  1252
#define SoftKey_5013_Offset                                  1259
#define SoftKey_5014_Offset                                  1266
#define SoftKey_5015_Offset                                  1273
#define SoftKey_5016_Offset                                  1280
#define SoftKey_5017_Offset                                  1287
#define SoftKey_5018_Offset                                  1294
#define SoftKey_5019_Offset                                  1301
#define SoftKey_5020_Offset                                  1308
#define SoftKey_5021_Offset                                  1315
#define SoftKey_5022_Offset                                  1322
#define SoftKey_5023_Offset                                  1329
#define SoftKey_5024_Offset                                  1336
#define SoftKey_5025_Offset                                  1343
#define SoftKey_5026_Offset                                  1350
#define SoftKey_5027_Offset                                  1357
#define Button_M1_reset_Offset                               1364
#define Button_M3_radar_speed_select_Offset                  1383
#define Button_M4_manuel_start_Offset                        1402
#define Button_M3_wheel_speed_select_Offset                  1421
#define Button_M4_manuel_stop_Offset                         1440
#define Button_6005_Offset                                   1459
#define Button_6006_Offset                                   1474
#define Button_W1_stop_Offset                                1489
#define Button_M1_refresh_Offset                             1508
#define Button_6009_Offset                                   1527
#define Button_M2_start_Offset                               1546
#define Button_M2_calibration_area_1a_Offset                 1565
#define Button_M2_calibration_area_5a_Offset                 1584
#define Button_M2_calibration_area_10a_Offset                1603
#define InputNumber_W1_actual_quantity_Offset                1622
#define InputNumber_9001_Offset                              1660
#define InputNumber_M2_target_quantity_Offset                1698
#define InputNumber_M2_flow_factor_Offset                    1736
#define InputNumber_9004_Offset                              1774
#define InputNumber_M4_motor_speed_Offset                    1812
#define OutputString_M3_radar_speed_kmh_Offset               1850
#define OutputString_M1_settings_header_Offset               1871
#define OutputString_M1_kg_ha_Offset                         1899
#define OutputString_M1_filllevel_Offset                     1921
#define OutputString_W1_actual_quantity_g_Offset             1947
#define OutputString_M3_radar_speed_header_Offset            1965
#define OutputString_11006_Offset                            1995
#define OutputString_M4_debug_Offset                         2023
#define OutputString_M1_header_Offset                        2045
#define OutputString_M2_header_Offset                        2071
#define OutputString_M1_reset_Offset                         2099
#define OutputString_M3_radar_speed_x_Offset                 2121
#define OutputString_SK_start_Offset                         2139
#define OutputString_SK_stop_Offset                          2161
#define OutputString_M1_weight_Offset                        2182
#define OutputString_M1_percent_Offset                       2201
#define OutputString_M1_electric_motor_Offset                2219
#define OutputString_11017_Offset                            2241
#define OutputString_M3_wheel_speed_kmh_Offset               2263
#define OutputString_M3_wheel_speed_header_Offset            2284
#define OutputString_M3_wheel_speed_x_Offset                 2315
#define OutputString_W1_actual_quantity_header_Offset        2332
#define OutputString_W1_flow_factor_Offset                   2358
#define OutputString_W1_target_quantity_Offset               2386
#define OutputString_W1_engine_speed_percent_Offset          2413
#define OutputString_W1_engine_speed_rpm_Offset              2431
#define OutputString_M2_target_quantity_kg_Offset            2453
#define OutputString_W1_header_Offset                        2472
#define OutputString_W1_stop_Offset                          2489
#define OutputString_M2_target_quantity_header_Offset        2510
#define OutputString_M2_start_Offset                         2538
#define OutputString_11031_Offset                            2560
#define OutputString_M2_flow_factor_header_Offset            2581
#define OutputString_M2_calibration_area_Offset              2609
#define OutputString_M2_calibration_area_1a_Offset           2638
#define OutputString_M2_calibration_area_5a_Offset           2658
#define OutputString_M2_calibration_area_10a_Offset          2678
#define OutputString_M4_manuel_Offset                        2699
#define OutputString_M4_engine_speed_manuel_Offset           2727
#define OutputNumber_W1_flow_factor_Offset                   2760
#define OutputNumber_M3_radar_speed_Offset                   2789
#define OutputNumber_M1_speed_Offset                         2818
#define OutputNumber_M1_percent_Offset                       2847
#define OutputNumber_M1_weight_Offset                        2876
#define OutputNumber_M1_electric_motor_Offset                2905
#define OutputNumber_M3_wheel_speed_Offset                   2934
#define OutputNumber_W1_target_quantity_Offset               2963
#define OutputNumber_W1_engine_speed_percent_Offset          2992
#define OutputNumber_W1_engine_speed_rpm_Offset              3021
#define OutputNumber_12014_Offset                            3050
#define Line_13000_Offset                                    3079
#define Rectangle_M1_percent_Offset                          3090
#define Rectangle_M1_speed_Offset                            3103
#define Rectangle_M1_kg_ha_Offset                            3116
#define Rectangle_M1_filllevel_Offset                        3129
#define Rectangle_M1_weight_Offset                           3142
#define Rectangle_M1_electric_motor_Offset                   3155
#define Rectangle_M3_radar_speed_Offset                      3168
#define Rectangle_M3_wheel_speed_Offset                      3181
#define Rectangle_M2_target_quantity_Offset                  3194
#define Rectangle_W1_actual_quantity_Offset                  3207
#define Rectangle_W1_flow_factor_Offset                      3220
#define Rectangle_W1_target_quantity_Offset                  3233
#define Rectangle_W1_engine_speed_percent_Offset             3246
#define Rectangle_W1_engine_speed_rpm_Offset                 3259
#define Rectangle_W1_header_Offset                           3272
#define Rectangle_M2_flow_factor_Offset                      3285
#define Rectangle_M2_calibration_area_Offset                 3298
#define weight_W1_actual_quantity_Offset                     3311
#define _100_percent_softkeys_Offset                         4602
#define debug_softkeys_Offset                                5893
#define Tractor_ground_speed_M3_radar_speed_Offset           7184
#define plus_percent_softkeys_Offset                         7713
#define minus_percent_softkeys_Offset                        9004
#define fertilzier_bin_softkeys_Offset                      10295
#define measuring_cup_softkeys_Offset                       11586
#define settings_softkeys_Offset                            12877
#define Picture_Tractor_forward_side_M1_speed_Offset        14168
#define Picturere_Graphic_refresh_Offset                    15459
#define Picture_fertilzier_bin_empty_M1_filllevel_Offset    16750
#define Picture_M1_weight_Offset                            18041
#define Picture_application_rate_per_area_M1_kg_ha_Offset   19332
#define Picture_application_rate_per_area_M1_percent_Offset  20623
#define Picture_fertilzier_bin_full_M1_filllevel_Offset     21914
#define Picture_M1_electric_motor_Offset                    23205
#define Tractor_wheel_slip_M3_wheel_speed_Offset            24496
#define fertilzier_bin_W1_flow_factor_Offset                25787
#define weight_W1_target_quantity_Offset                    27078
#define Electric_motor_W1_engine_speed_percent_Offset       28369
#define Electric_motor_W1_engine_speed_rpm_Offset           29660
#define weight_20031_Offset                                 30951
#define application_rate_per_area_M2_target_quantity_Offset  32242
#define application_rate_per_area_20039_Offset              33533
#define fertilzier_bin_M2_flow_factor_Offset                34824
#define fertilzier_bin_20041_Offset                         36115
#define NumberVariable_engine_speed_percent_Offset          37406
#define NumberVariable_Ground_based_machine_speed_Offset    37413
#define NumberVariable_bool_selected_speed_Offset           37420
#define NumberVariable_target_quantity_calibration_run_Offset  37427
#define NumberVariable_selected_speed_Offset                37434
#define NumberVariable_engine_speed_manuel_Offset           37441
#define NumberVariable_weight_Offset                        37448
#define NumberVariable_application_rate_percent_Offset      37455
#define NumberVariable_Wheel_based_machine_speed_Offset     37462
#define NumberVariable_flow_factor_new_Offset               37469
#define NumberVariable_target_quantity_Offset               37476
#define NumberVariable_W1_actual_quantity_Offset            37483
#define NumberVariable_engine_speed_rpm_Offset              37490
#define NumberVariable_flow_factor_Offset                   37497
#define NumberVariable_application_rate_percent_old_Offset  37504
#define StringVariable_calibration_run_Offset               37511
#define FontAttributes_23000_Offset                         37534
#define FontAttributes_23001_Offset                         37542
#define FontAttributes_Header_Offset                        37550
#define FontAttributes_WindowMask_Offset                    37558
#define FontAttributes_reset_Offset                         37566
#define FontAttributes_string_start_stop_button_Offset      37574
#define FontAttributes_main_boxes_Offset                    37582
#define FontAttributes_23016_Offset                         37590
#define FontAttributes_Header_white_Offset                  37598
#define LineAttributes_24000_Offset                         37606
#define LineAttributes_24001_Offset                         37614
#define LineAttributes_24002_Offset                         37622
#define LineAttributes_24003_Offset                         37630
#define LineAttributes_24004_Offset                         37638
#define LineAttributes_24006_Offset                         37646
#define LineAttributes_24007_Offset                         37654
#define LineAttributes_24008_Offset                         37662
#define LineAttributes_24009_Offset                         37670
#define LineAttributes_24010_Offset                         37678
#define LineAttributes_24011_Offset                         37686
#define LineAttributes_24012_Offset                         37694
#define LineAttributes_24013_Offset                         37702
#define LineAttributes_24014_Offset                         37710
#define LineAttributes_24015_Offset                         37718
#define LineAttributes_24016_Offset                         37726
#define FillAttributes_main_colour_Offset                   37734
#define FillAttributes_new_holland_blue_Offset              37742

#define ISO_OP_MEMORY_CLASS

#define ISO_OP_DefaultPool_Size  37750
extern const unsigned char ISO_OP_MEMORY_CLASS isoOP_DefaultPool[];

#define ISO_OP_DefaultPool_ObjectNumber    224
extern const unsigned long ISO_OP_MEMORY_CLASS isoOP_DefaultPool_Offset[];
extern const unsigned long ISO_OP_MEMORY_CLASS isoOP_DefaultPool_Offset_Id[];
#define ISO_OP_DefaultPool_Scale_Offset      1

#define ID_NULL  0xFFFF

#define TYPEID_WORKSET        0
#define TYPEID_DATAMASK       1
#define TYPEID_ALARMMASK      2
#define TYPEID_CONTAINER      3
#define TYPEID_SKEYMASK       4
#define TYPEID_SOFTKEY        5
#define TYPEID_BUTTON         6
#define TYPEID_INBOOL         7
#define TYPEID_INSTR          8
#define TYPEID_INNUM          9
#define TYPEID_INLIST        10
#define TYPEID_OUTSTR        11
#define TYPEID_OUTNUM        12
#define TYPEID_OUTLINE       13
#define TYPEID_OUTRECT       14
#define TYPEID_OUTELLIPSE    15
#define TYPEID_OUTPOLY       16
#define TYPEID_OUTMETER      17
#define TYPEID_OUTLINBAR     18
#define TYPEID_OUTARCBAR     19
#define TYPEID_OUTPICT       20
#define TYPEID_VARNUM        21
#define TYPEID_VARSTR        22
#define TYPEID_FONTATTR      23
#define TYPEID_LINEATTR      24
#define TYPEID_FILLATTR      25
#define TYPEID_INPATTR       26
#define TYPEID_OBJPTR        27
#define TYPEID_MACRO         28
#define TYPEID_AUXFUNC       29
#define TYPEID_AUXINP        30
#define TYPEID_AUXFUNC2      31
#define TYPEID_AUXINP2       32
#define TYPEID_AUXPTR        33
#define TYPEID_WINMASK       34
#define TYPEID_KEYGROUP      35
#define TYPEID_GRPHCTXT      36
#define TYPEID_OUTLIST       37
#define TYPEID_EXTINPATTR    38
#define TYPEID_COLORMAP      39
#define TYPEID_OBJLBLREF     40
#define TYPEID_EXTOBJDEF     41
#define TYPEID_EXTREFNAME    42
#define TYPEID_EXTOBJPTR     43
#define TYPEID_ANIMATION     44
#define TYPEID_COLORPAL      45
#define TYPEID_GRAPHDATA     46
#define TYPEID_WSSPECIAL     47
#define TYPEID_SCALEGRAPH    48

#define EV_REFRESH            0
#define EV_ACT                1
#define EV_DEACT              2
#define EV_SHOW               3
#define EV_HIDE               4
#define EV_ENABLE             5
#define EV_DISABLE            6
#define EV_CHGACTMASK         7
#define EV_CHGSKEYMASK        8
#define EV_CHGATTR            9
#define EV_CHGBKCOLOR        10
#define EV_CHGFONTATTR       11
#define EV_CHGLINEATTR       12
#define EV_CHGFILLATTR       13
#define EV_CHGCHILDLOC       14
#define EV_CHGSIZE           15
#define EV_CHGVAL            16
#define EV_CHGPRIOR          17
#define EV_CHGENDPNT         18
#define EV_SELINPUT          19
#define EV_DESELINPUT        20
#define EV_ESC               21
#define EV_ENTERVAL          22
#define EV_ENTERCHGVAL       23
#define EV_KEYPRESS          24
#define EV_KEYRELEASE        25
#define EV_CHGCHILDPOS       26

#define CMD_HIDE_SHOW               160
#define CMD_ENABLE_DISABLE          161
#define CMD_SELECT_INPUT_OBJECT     162
#define CMD_CONTROL_AUDIO_DEVICE    163
#define CMD_SET_AUDIO_VOLUME        164
#define CMD_CHANGE_CHILD_LOCATION   165
#define CMD_CHANGE_SIZE             166
#define CMD_CHANGE_BACKGROUND_COLOR 167
#define CMD_CHANGE_NUMERIC_VALUE    168
#define CMD_CHANGE_END_POINT        169
#define CMD_CHANGE_FONT_ATTRIBUTES  170
#define CMD_CHANGE_LINE_ATTRIBUTES  171
#define CMD_CHANGE_FILL_ATTRIBUTES  172
#define CMD_CHANGE_ACTIVE_MASK      173
#define CMD_CHANGE_SOFT_KEY_MASK    174
#define CMD_CHANGE_ATTRIBUTE        175
#define CMD_CHANGE_PRIORITY         176
#define CMD_CHANGE_LIST_ITEM        177
#define CMD_CHANGE_STRING_VALUE     179
#define CMD_CHANGE_CHILD_POSITION   180
#define CMD_SET_OBJECT_LABEL        181
#define CMD_CHANGE_POLYGON_POINT    182
#define CMD_CHANGE_POLYGON_SCALE    183
#define CMD_GRAPHICS_CONTEXT        184
#define CMD_GET_ATTRIBUTE           185
#define CMD_SELECT_COLOURMAP_OR_PALETTE 186
#define CMD_EXECUTE_EXTENDED_MACRO  188
#define CMD_LOCK_UNLOCK_MASK        189
#define CMD_EXECUTE_MACRO           190

#define COLOR_BLACK       0
#define COLOR_WHITE       1
#define COLOR_GREEN       2
#define COLOR_TEAL        3
#define COLOR_MAROON      4
#define COLOR_PURPLE      5
#define COLOR_OLIVE       6
#define COLOR_SILVER      7
#define COLOR_GREY        8
#define COLOR_BLUE        9
#define COLOR_LIME       10
#define COLOR_CYAN       11
#define COLOR_RED        12
#define COLOR_MAGENTA    13
#define COLOR_YELLOW     14
#define COLOR_NAVY       15

#define FLOAT_1      0x00, 0x00, 0x80, 0x3F
#define FLOAT_10     0x00, 0x00, 0x20, 0x41
#define FLOAT_100    0x00, 0x00, 0xC8, 0x42
#define FLOAT_1000   0x00, 0x00, 0x7A, 0x44
#define FLOAT_0_1    0xCD, 0xCC, 0xCC, 0x3D
#define FLOAT_0_01   0x0A, 0xD7, 0x23, 0x3C
#define FLOAT_0_001  0x6F, 0x12, 0x83, 0x3A
