// ISO-Designer ISO 11783   Version 5.7.1.6514 Bucher Automation AG
// Do not change!

#define WorkingSet_0_Offset                                     1
#define Macro_1_Offset                                         21
#define DataMask_M3_Offset                                     34
#define DataMask_M4_Offset                                     60
#define DataMask_M1_Offset                                     74
#define DataMask_M2_Offset                                    124
#define Container_3001_Offset                                 138
#define Container_3002_Offset                                 184
#define Container_3003_Offset                                 218
#define Container_3005_Offset                                 264
#define Container_3006_Offset                                 298
#define Container_3007_Offset                                 332
#define Container_3008_Offset                                 366
#define Container_3009_Offset                                 400
#define Container_3010_Offset                                 434
#define SoftKeyMask_S1_Offset                                 456
#define SoftKeyMask_S2_Offset                                 482
#define SoftKeyMask_S3_Offset                                 508
#define SoftKeyMask_S4_Offset                                 534
#define SoftKey_stop_Offset                                   560
#define SoftKey_100_percent_Offset                            573
#define SoftKey_plus_percent_Offset                           586
#define SoftKey_start_Offset                                  599
#define SoftKey_minus_percent_Offset                          612
#define SoftKey_main_Offset                                   625
#define SoftKey_debug_Offset                                  638
#define SoftKey_calibration_run_Offset                        651
#define SoftKey_settings_Offset                               664
#define SoftKey_5009_Offset                                   677
#define SoftKey_5010_Offset                                   684
#define SoftKey_5011_Offset                                   691
#define SoftKey_5012_Offset                                   698
#define SoftKey_5013_Offset                                   705
#define SoftKey_5014_Offset                                   712
#define SoftKey_5015_Offset                                   719
#define SoftKey_5016_Offset                                   726
#define SoftKey_5017_Offset                                   733
#define SoftKey_5018_Offset                                   740
#define SoftKey_5019_Offset                                   747
#define SoftKey_5020_Offset                                   754
#define SoftKey_5021_Offset                                   761
#define SoftKey_5022_Offset                                   768
#define SoftKey_5023_Offset                                   775
#define SoftKey_5024_Offset                                   782
#define SoftKey_5025_Offset                                   789
#define SoftKey_5026_Offset                                   796
#define SoftKey_5027_Offset                                   803
#define Button_reset_Offset                                   810
#define Button_select_radar_speed_Offset                      831
#define Button_select_wheel_speed_Offset                      850
#define OutputString_km_h_Offset                              869
#define OutputString_settings_header_Offset                   890
#define OutputString_11002_Offset                             920
#define OutputString_11003_Offset                             942
#define OutputString_radar_speed_Offset                       968
#define OutputString_11006_Offset                            1006
#define OutputString_debug_Offset                            1028
#define OutputString_nordsten_Offset                         1050
#define OutputString_abdrehprobe_Offset                      1076
#define OutputString_reset_Offset                            1104
#define OutputString_x_radar_speed_Offset                    1126
#define OutputString_start_Offset                            1144
#define OutputString_stop_Offset                             1166
#define OutputString_11014_Offset                            1187
#define OutputString_11015_Offset                            1206
#define OutputString_11016_Offset                            1224
#define OutputString_11018_Offset                            1246
#define OutputString_11019_Offset                            1267
#define OutputString_x_wheel_speed_Offset                    1306
#define OutputNumber_12001_Offset                            1323
#define OutputNumber_Ground_based_machine_speed_km_h_Offset   1352
#define OutputNumber_12003_Offset                            1381
#define OutputNumber_12004_Offset                            1410
#define OutputNumber_12005_Offset                            1439
#define OutputNumber_12006_Offset                            1468
#define OutputNumber_12007_Offset                            1497
#define OutputNumber_12008_Offset                            1526
#define OutputNumber_12009_Offset                            1555
#define NumberVariable_Wheel_based_machine_speed_Offset      1584
#define Line_13000_Offset                                    1613
#define Rectangle_14000_Offset                               1624
#define Rectangle_14001_Offset                               1637
#define Rectangle_14002_Offset                               1650
#define Rectangle_14003_Offset                               1663
#define Rectangle_14004_Offset                               1676
#define Rectangle_14005_Offset                               1689
#define Rectangle_14006_Offset                               1702
#define Rectangle_radar_speed_Offset                         1715
#define Rectangle_14008_Offset                               1728
#define _100_percent_20001_Offset                            1741
#define debug_20002_Offset                                   3032
#define Tractor_ground_speed_Offset                          4323
#define plus_percent_20004_Offset                            4852
#define minus_percent_20005_Offset                           6143
#define fertilzier_bin_20006_Offset                          7434
#define measuring_cup_20007_Offset                           8725
#define settings_20008_Offset                               10016
#define Tractor_forward_side_200_20009_Offset               11307
#define weight_20010_Offset                                 12598
#define application_rate_per_area_20011_Offset              13889
#define fertilzier_bin_empty_20012_Offset                   15180
#define weight_20013_Offset                                 16471
#define application_rate_per_area_20014_Offset              17762
#define application_rate_per_area_20015_Offset              19053
#define fertilzier_bin_20016_Offset                         20344
#define Tractor_forward_side_200_20017_Offset               21635
#define Electric_motor_general_20018_Offset                 22926
#define Tractor_ground_speed_200_20019_Offset               24217
#define Tractor_wheel_slip_200_20021_Offset                 24746
#define NumberVariable_Ground_based_machine_speed_Offset    26037
#define NumberVariable_bool_selected_speed_Offset           26044
#define NumberVariable_application_rate_Offset              26051
#define NumberVariable_selected_speed_Offset                26058
#define NumberVariable_21005_Offset                         26065
#define NumberVariable_21006_Offset                         26072
#define NumberVariable_21007_Offset                         26079
#define NumberVariable_21008_Offset                         26086
#define NumberVariable_21009_Offset                         26093
#define NumberVariable_21010_Offset                         26100
#define NumberVariable_21011_Offset                         26107
#define FontAttributes_OutputNumber_Offset                  26114
#define FontAttributes_Header_Offset                        26122
#define FontAttributes_23003_Offset                         26130
#define FontAttributes_23004_Offset                         26138
#define FontAttributes_23005_Offset                         26146
#define FontAttributes_23009_reset_Offset                   26154
#define FontAttributes_string_start_stop_button_Offset      26162
#define FontAttributes_23011_main_boxes_Offset              26170
#define FontAttributes_23012_Offset                         26178
#define LineAttributes_24000_Offset                         26186
#define LineAttributes_24001_Offset                         26194
#define LineAttributes_24002_Offset                         26202
#define LineAttributes_24003_Offset                         26210
#define LineAttributes_24004_Offset                         26218
#define LineAttributes_24005_Offset                         26226
#define LineAttributes_24006_Offset                         26234
#define LineAttributes_24007_Offset                         26242
#define LineAttributes_24008_Offset                         26250
#define FillAttributes_box_Offset                           26258
#define FillAttributes_25001_Offset                         26266
#define FillAttributes_25002_Offset                         26274
#define FillAttributes_25003_Offset                         26282
#define FillAttributes_25004_Offset                         26290
#define FillAttributes_25005_Offset                         26298
#define FillAttributes_25006_Offset                         26306
#define FillAttributes_25007_Offset                         26314

#define ISO_OP_MEMORY_CLASS

#define ISO_OP_DefaultPool_Size  26322
extern const unsigned char ISO_OP_MEMORY_CLASS isoOP_DefaultPool[];

#define ISO_OP_DefaultPool_ObjectNumber    146
extern const unsigned long ISO_OP_MEMORY_CLASS isoOP_DefaultPool_Offset[];
extern const unsigned long ISO_OP_MEMORY_CLASS isoOP_DefaultPool_Offset_Id[];
#define ISO_OP_DefaultPool_Scale_Offset      1

#define ID_NULL  0xFFFF

#define TYPEID_WORKSET        0
#define TYPEID_DATAMASK       1
#define TYPEID_ALARMMASK      2
#define TYPEID_CONTAINER      3
#define TYPEID_SKEYMASK       4
#define TYPEID_SOFTKEY        5
#define TYPEID_BUTTON         6
#define TYPEID_INBOOL         7
#define TYPEID_INSTR          8
#define TYPEID_INNUM          9
#define TYPEID_INLIST        10
#define TYPEID_OUTSTR        11
#define TYPEID_OUTNUM        12
#define TYPEID_OUTLINE       13
#define TYPEID_OUTRECT       14
#define TYPEID_OUTELLIPSE    15
#define TYPEID_OUTPOLY       16
#define TYPEID_OUTMETER      17
#define TYPEID_OUTLINBAR     18
#define TYPEID_OUTARCBAR     19
#define TYPEID_OUTPICT       20
#define TYPEID_VARNUM        21
#define TYPEID_VARSTR        22
#define TYPEID_FONTATTR      23
#define TYPEID_LINEATTR      24
#define TYPEID_FILLATTR      25
#define TYPEID_INPATTR       26
#define TYPEID_OBJPTR        27
#define TYPEID_MACRO         28
#define TYPEID_AUXFUNC       29
#define TYPEID_AUXINP        30
#define TYPEID_AUXFUNC2      31
#define TYPEID_AUXINP2       32
#define TYPEID_AUXPTR        33
#define TYPEID_WINMASK       34
#define TYPEID_KEYGROUP      35
#define TYPEID_GRPHCTXT      36
#define TYPEID_OUTLIST       37
#define TYPEID_EXTINPATTR    38
#define TYPEID_COLORMAP      39
#define TYPEID_OBJLBLREF     40
#define TYPEID_EXTOBJDEF     41
#define TYPEID_EXTREFNAME    42
#define TYPEID_EXTOBJPTR     43
#define TYPEID_ANIMATION     44
#define TYPEID_COLORPAL      45
#define TYPEID_GRAPHDATA     46
#define TYPEID_WSSPECIAL     47
#define TYPEID_SCALEGRAPH    48

#define EV_REFRESH            0
#define EV_ACT                1
#define EV_DEACT              2
#define EV_SHOW               3
#define EV_HIDE               4
#define EV_ENABLE             5
#define EV_DISABLE            6
#define EV_CHGACTMASK         7
#define EV_CHGSKEYMASK        8
#define EV_CHGATTR            9
#define EV_CHGBKCOLOR        10
#define EV_CHGFONTATTR       11
#define EV_CHGLINEATTR       12
#define EV_CHGFILLATTR       13
#define EV_CHGCHILDLOC       14
#define EV_CHGSIZE           15
#define EV_CHGVAL            16
#define EV_CHGPRIOR          17
#define EV_CHGENDPNT         18
#define EV_SELINPUT          19
#define EV_DESELINPUT        20
#define EV_ESC               21
#define EV_ENTERVAL          22
#define EV_ENTERCHGVAL       23
#define EV_KEYPRESS          24
#define EV_KEYRELEASE        25
#define EV_CHGCHILDPOS       26

#define CMD_HIDE_SHOW               160
#define CMD_ENABLE_DISABLE          161
#define CMD_SELECT_INPUT_OBJECT     162
#define CMD_CONTROL_AUDIO_DEVICE    163
#define CMD_SET_AUDIO_VOLUME        164
#define CMD_CHANGE_CHILD_LOCATION   165
#define CMD_CHANGE_SIZE             166
#define CMD_CHANGE_BACKGROUND_COLOR 167
#define CMD_CHANGE_NUMERIC_VALUE    168
#define CMD_CHANGE_END_POINT        169
#define CMD_CHANGE_FONT_ATTRIBUTES  170
#define CMD_CHANGE_LINE_ATTRIBUTES  171
#define CMD_CHANGE_FILL_ATTRIBUTES  172
#define CMD_CHANGE_ACTIVE_MASK      173
#define CMD_CHANGE_SOFT_KEY_MASK    174
#define CMD_CHANGE_ATTRIBUTE        175
#define CMD_CHANGE_PRIORITY         176
#define CMD_CHANGE_LIST_ITEM        177
#define CMD_CHANGE_STRING_VALUE     179
#define CMD_CHANGE_CHILD_POSITION   180
#define CMD_SET_OBJECT_LABEL        181
#define CMD_CHANGE_POLYGON_POINT    182
#define CMD_CHANGE_POLYGON_SCALE    183
#define CMD_GRAPHICS_CONTEXT        184
#define CMD_GET_ATTRIBUTE           185
#define CMD_SELECT_COLOURMAP_OR_PALETTE 186
#define CMD_EXECUTE_EXTENDED_MACRO  188
#define CMD_LOCK_UNLOCK_MASK        189
#define CMD_EXECUTE_MACRO           190

#define COLOR_BLACK       0
#define COLOR_WHITE       1
#define COLOR_GREEN       2
#define COLOR_TEAL        3
#define COLOR_MAROON      4
#define COLOR_PURPLE      5
#define COLOR_OLIVE       6
#define COLOR_SILVER      7
#define COLOR_GREY        8
#define COLOR_BLUE        9
#define COLOR_LIME       10
#define COLOR_CYAN       11
#define COLOR_RED        12
#define COLOR_MAGENTA    13
#define COLOR_YELLOW     14
#define COLOR_NAVY       15

#define FLOAT_1      0x00, 0x00, 0x80, 0x3F
#define FLOAT_10     0x00, 0x00, 0x20, 0x41
#define FLOAT_100    0x00, 0x00, 0xC8, 0x42
#define FLOAT_1000   0x00, 0x00, 0x7A, 0x44
#define FLOAT_0_1    0xCD, 0xCC, 0xCC, 0x3D
#define FLOAT_0_01   0x0A, 0xD7, 0x23, 0x3C
#define FLOAT_0_001  0x6F, 0x12, 0x83, 0x3A
