<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="front_fertilizer_main" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="04jul" Date="2026-01-24">
	</VersionInfo>
	<CompilerInfo packageName="Main">
		<Import declaration="DefaultPool::Button_M1_refresh"/>
		<Import declaration="DefaultPool::Button_M1_reset"/>
		<Import declaration="DefaultPool::Button_M2_calibration_area_10a"/>
		<Import declaration="DefaultPool::Button_M2_calibration_area_1a"/>
		<Import declaration="DefaultPool::Button_M2_calibration_area_5a"/>
		<Import declaration="DefaultPool::Button_M2_start"/>
		<Import declaration="DefaultPool::Button_M4_manuel_start"/>
		<Import declaration="DefaultPool::Button_M4_manuel_stop"/>
		<Import declaration="DefaultPool::Button_W1_stop"/>
		<Import declaration="DefaultPool::Container_Picture_fertilzier_bin_empty_M1_filllevel"/>
		<Import declaration="DefaultPool::Container_Picture_fertilzier_bin_full_M1_filllevel"/>
		<Import declaration="DefaultPool::DataMask_M1"/>
		<Import declaration="DefaultPool::DataMask_M2"/>
		<Import declaration="DefaultPool::DataMask_M3"/>
		<Import declaration="DefaultPool::DataMask_M4"/>
		<Import declaration="DefaultPool::DataMask_M5"/>
		<Import declaration="DefaultPool::NumberVariable_application_rate_percent"/>
		<Import declaration="DefaultPool::NumberVariable_engine_speed_manuel"/>
		<Import declaration="DefaultPool::NumberVariable_engine_speed_rpm"/>
		<Import declaration="DefaultPool::NumberVariable_flow_factor"/>
		<Import declaration="DefaultPool::NumberVariable_target_quantity"/>
		<Import declaration="DefaultPool::NumberVariable_target_quantity_calibration_run"/>
		<Import declaration="DefaultPool::OutputNumber_M1_weight"/>
		<Import declaration="DefaultPool::OutputString_M1_filllevel"/>
		<Import declaration="DefaultPool::SoftKeyMask_S1"/>
		<Import declaration="DefaultPool::SoftKeyMask_S2"/>
		<Import declaration="DefaultPool::SoftKeyMask_S3"/>
		<Import declaration="DefaultPool::SoftKeyMask_S4"/>
		<Import declaration="DefaultPool::SoftKey_100_percent"/>
		<Import declaration="DefaultPool::SoftKey_calibration_run"/>
		<Import declaration="DefaultPool::SoftKey_debug"/>
		<Import declaration="DefaultPool::SoftKey_main"/>
		<Import declaration="DefaultPool::SoftKey_minus_percent"/>
		<Import declaration="DefaultPool::SoftKey_plus_percent"/>
		<Import declaration="DefaultPool::SoftKey_settings"/>
		<Import declaration="DefaultPool::SoftKey_start"/>
		<Import declaration="DefaultPool::SoftKey_stop"/>
		<Import declaration="DefaultPool::WorkingSet_0"/>
		<Import declaration="Uebungen::const::NVS::NVS_Keys::KEY_I1_STORE"/>
		<Import declaration="Uebungen::const::NVS::NVS_Keys::KEY_I2_STORE"/>
		<Import declaration="Uebungen::const::NVS::NVS_Keys::KEY_I3_STORE"/>
		<Import declaration="Uebungen::const::NVS::NVS_Keys::SECTION_I1_STORE"/>
		<Import declaration="Uebungen::const::NVS::NVS_Keys::SECTION_I2_STORE"/>
		<Import declaration="Uebungen::const::NVS::NVS_Keys::SECTION_I3_STORE"/>
		<Import declaration="isobus::UT::Q::const::colours::COLOR_BLUE"/>
		<Import declaration="isobus::UT::Q::const::colours::COLOR_GREY"/>
		<Import declaration="isobus::UT::Q::const::colours::COLOR_RED"/>
		<Import declaration="isobus::UT::io::Button::ButtonActivationCode::BT_RELEASED_UNLATCHED"/>
		<Import declaration="isobus::UT::io::Softkey::SoftKeyActivationCode::SK_RELEASED"/>
		<Import declaration="logiBUS::io::AI::logiBUS_AI::AnalogInput_I6"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q4"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Q_SoftKeyMask" Type="isobus::UT::Q::Q_SoftKeyMask" x="-1500" y="-800">
			<Parameter Name="u8MaskType" Value="1"/>
			<Parameter Name="u16DataMaskId" Value="DataMask_M1"/>
			<Parameter Name="u16SoftKeyMaskId" Value="SoftKeyMask_S1"/>
		</FB>
		<FB Name="Softkey_IE_main" Type="isobus::UT::io::Softkey::Softkey_IE" x="-5200" y="2600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_main"/>
			<Parameter Name="InputEvent" Value="SK_RELEASED"/>
		</FB>
		<FB Name="Softkey_IE_calibration_run" Type="isobus::UT::io::Softkey::Softkey_IE" x="-5400" y="3600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_calibration_run"/>
			<Parameter Name="InputEvent" Value="SK_RELEASED"/>
		</FB>
		<FB Name="Softkey_IE_settings" Type="isobus::UT::io::Softkey::Softkey_IE" x="-5200" y="4600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_settings"/>
			<Parameter Name="InputEvent" Value="SK_RELEASED"/>
		</FB>
		<FB Name="Softkey_IE_debug" Type="isobus::UT::io::Softkey::Softkey_IE" x="-5200" y="5600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_debug"/>
			<Parameter Name="InputEvent" Value="SK_RELEASED"/>
		</FB>
		<FB Name="Q_ActiveMask_DataMask_M1" Type="isobus::UT::Q::Q_ActiveMask" x="-700" y="3800">
			<Parameter Name="u16WorkSetId" Value="WorkingSet_0"/>
		</FB>
		<FB Name="Q_NumericValue" Type="isobus::UT::Q::Q_NumericValue" x="9500" y="3200">
			<Parameter Name="u16ObjId" Value="NumberVariable_application_rate_percent"/>
		</FB>
		<FB Name="Softkey_IE_100_percent" Type="isobus::UT::io::Softkey::Softkey_IE" x="2300" y="2600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_100_percent"/>
			<Parameter Name="InputEvent" Value="SK_RELEASED"/>
		</FB>
		<FB Name="Softkey_IE_plus_percent" Type="isobus::UT::io::Softkey::Softkey_IE" x="2300" y="3700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_plus_percent"/>
			<Parameter Name="InputEvent" Value="SK_RELEASED"/>
		</FB>
		<FB Name="Softkey_IE_minus_percent" Type="isobus::UT::io::Softkey::Softkey_IE" x="2300" y="4800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_minus_percent"/>
			<Parameter Name="InputEvent" Value="SK_RELEASED"/>
		</FB>
		<FB Name="F_ADD" Type="iec61131::arithmetic::F_ADD" x="4700" y="4000">
			<Parameter Name="IN2" Value="UDINT#278" Comment="Second function input"/>
		</FB>
		<FB Name="F_SUB" Type="iec61131::arithmetic::F_SUB" x="4700" y="5000">
			<Parameter Name="IN2" Value="UDINT#278" Comment="Second function input"/>
		</FB>
		<FB Name="F_SEL_E_4" Type="eclipse4diac::utils::selection::F_SEL_E_4" x="-2800" y="3300">
			<Parameter Name="IN1" Value="DataMask_M1"/>
			<Parameter Name="IN2" Value="DataMask_M2"/>
			<Parameter Name="IN3" Value="DataMask_M3"/>
			<Parameter Name="IN4" Value="DataMask_M4" Comment="Selectable input variable"/>
		</FB>
		<FB Name="Q_ActiveMask_DataMask_M2" Type="isobus::UT::Q::Q_ActiveMask" x="-4800" y="-900">
			<Parameter Name="u16WorkSetId" Value="WorkingSet_0"/>
			<Parameter Name="u16NewMaskId" Value="DataMask_M1"/>
		</FB>
		<FB Name="Q_SoftKeyMask_2" Type="isobus::UT::Q::Q_SoftKeyMask" x="-1500" y="200">
			<Parameter Name="u8MaskType" Value="1"/>
			<Parameter Name="u16DataMaskId" Value="DataMask_M2"/>
			<Parameter Name="u16SoftKeyMaskId" Value="SoftKeyMask_S2"/>
		</FB>
		<FB Name="Q_SoftKeyMask_3" Type="isobus::UT::Q::Q_SoftKeyMask" x="-1500" y="1200">
			<Parameter Name="u8MaskType" Value="1"/>
			<Parameter Name="u16DataMaskId" Value="DataMask_M3"/>
			<Parameter Name="u16SoftKeyMaskId" Value="SoftKeyMask_S3"/>
		</FB>
		<FB Name="Q_SoftKeyMask_4" Type="isobus::UT::Q::Q_SoftKeyMask" x="-1500" y="2200">
			<Parameter Name="u8MaskType" Value="1"/>
			<Parameter Name="u16DataMaskId" Value="DataMask_M4"/>
			<Parameter Name="u16SoftKeyMaskId" Value="SoftKeyMask_S4"/>
		</FB>
		<FB Name="F_SEL_E_3" Type="eclipse4diac::utils::selection::F_SEL_E_3" x="6800" y="3200">
			<Parameter Name="IN1" Value="UDINT#27780"/>
		</FB>
		<FB Name="NVS" Type="eclipse4diac::storage::INI" x="6640" y="6900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="SECTION" Value="SECTION_I1_STORE"/>
			<Parameter Name="KEY" Value="KEY_I1_STORE"/>
			<Parameter Name="DEFAULT_VALUE" Value="UDINT#0"/>
		</FB>
		<FB Name="Q_NumericValue_1" Type="isobus::UT::Q::Q_NumericValue" x="9140" y="7100">
			<Parameter Name="u16ObjId" Value="NumberVariable_application_rate_percent"/>
		</FB>
		<FB Name="CbVtStatus" Type="isobus::UT::status::CbVtStatus" x="3800" y="6200">
		</FB>
		<FB Name="F_SEL_E_2" Type="eclipse4diac::utils::selection::F_SEL_E_2" x="8200" y="2800">
		</FB>
		<FB Name="Button_IE" Type="isobus::UT::io::Button::Button_IE" x="8800" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="Button_M4_manuel_stop"/>
			<Parameter Name="InputEvent" Value="BT_RELEASED_UNLATCHED"/>
		</FB>
		<FB Name="F_DWORD_TO_UDINT" Type="iec61131::conversion::F_DWORD_TO_UDINT" x="-4006.67" y="9100">
		</FB>
		<FB Name="InputNumber_I1" Type="isobus::UT::io::NumericValue::NumericValue_ID" x="-5600" y="8900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="NumberVariable_flow_factor"/>
		</FB>
		<FB Name="INI" Type="eclipse4diac::storage::INI" x="-1300" y="8600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="SECTION" Value="SECTION_I2_STORE"/>
			<Parameter Name="KEY" Value="KEY_I2_STORE"/>
			<Parameter Name="DEFAULT_VALUE" Value="UDINT#55"/>
		</FB>
		<FB Name="Q_NumericValue_2" Type="isobus::UT::Q::Q_NumericValue" x="1400" y="8800">
			<Parameter Name="u16ObjId" Value="NumberVariable_flow_factor"/>
		</FB>
		<FB Name="CbVtStatus_1" Type="isobus::UT::status::CbVtStatus" x="-1500" y="7000">
		</FB>
		<FB Name="INI_1" Type="eclipse4diac::storage::INI" x="9100" y="22100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="SECTION" Value="SECTION_I3_STORE"/>
			<Parameter Name="KEY" Value="KEY_I3_STORE"/>
			<Parameter Name="DEFAULT_VALUE" Value="UDINT#55"/>
		</FB>
		<FB Name="CbVtStatus_2" Type="isobus::UT::status::CbVtStatus" x="8900" y="20500">
		</FB>
		<FB Name="F_DWORD_TO_UDINT_1" Type="iec61131::conversion::F_DWORD_TO_UDINT" x="6393.33" y="22600">
		</FB>
		<FB Name="InputNumber_I2" Type="isobus::UT::io::NumericValue::NumericValue_ID" x="4800" y="22400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="NumberVariable_target_quantity"/>
		</FB>
		<FB Name="Q_NumericValue_3" Type="isobus::UT::Q::Q_NumericValue" x="11800" y="22300">
			<Parameter Name="u16ObjId" Value="NumberVariable_target_quantity"/>
		</FB>
		<FB Name="F_DINT_TO_UDINT" Type="iec61131::conversion::F_DINT_TO_UDINT" x="5800" y="4700">
		</FB>
		<FB Name="F_DINT_TO_UDINT_1" Type="iec61131::conversion::F_DINT_TO_UDINT" x="5300" y="2800">
		</FB>
		<FB Name="F_DINT_TO_UDINT_2" Type="iec61131::conversion::F_DINT_TO_UDINT" x="7400" y="4600">
		</FB>
		<FB Name="logiBUS_IX" Type="logiBUS::io::DI::logiBUS_IX" x="-8200" y="12900">
			<Parameter Name="QI" Value="True"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="Q_StringValue" Type="isobus::UT::Q::Q_StringValue" x="-4200" y="13700">
			<Parameter Name="u16ObjId" Value="OutputString_M1_filllevel"/>
		</FB>
		<FB Name="F_SEL" Type="iec61131::selection::F_SEL" x="-6100" y="13600">
			<Parameter Name="IN0" Value="STRING#'Tank leer'"/>
			<Parameter Name="IN1" Value="STRING#'Tank voll'"/>
		</FB>
		<FB Name="Q_ObjHideShow" Type="isobus::UT::Q::Q_ObjHideShow" x="-4200" y="14600">
			<Parameter Name="u16ObjId" Value="Container_Picture_fertilzier_bin_full_M1_filllevel"/>
		</FB>
		<FB Name="Q_ObjHideShow_1" Type="isobus::UT::Q::Q_ObjHideShow" x="-4200" y="15600">
			<Parameter Name="u16ObjId" Value="Container_Picture_fertilzier_bin_empty_M1_filllevel"/>
		</FB>
		<FB Name="Q_BackgroundColour_3" Type="isobus::UT::Q::Q_BackgroundColour" x="5600" y="15600">
			<Parameter Name="u16ObjId" Value="Button_M2_calibration_area_1a"/>
		</FB>
		<FB Name="Q_BackgroundColour_4" Type="isobus::UT::Q::Q_BackgroundColour" x="5600" y="16500">
			<Parameter Name="u16ObjId" Value="Button_M2_calibration_area_5a"/>
		</FB>
		<FB Name="Q_BackgroundColour_5" Type="isobus::UT::Q::Q_BackgroundColour" x="5600" y="17300">
			<Parameter Name="u16ObjId" Value="Button_M2_calibration_area_10a"/>
		</FB>
		<FB Name="F_SEL_E_5" Type="eclipse4diac::utils::selection::F_SEL_E_3" x="3100" y="15200">
			<Parameter Name="IN1" Value="COLOR_BLUE"/>
			<Parameter Name="IN2" Value="COLOR_GREY"/>
			<Parameter Name="IN3" Value="COLOR_GREY"/>
		</FB>
		<FB Name="F_SEL_E_6" Type="eclipse4diac::utils::selection::F_SEL_E_3" x="3100" y="16400">
			<Parameter Name="IN1" Value="COLOR_GREY"/>
			<Parameter Name="IN2" Value="COLOR_BLUE"/>
			<Parameter Name="IN3" Value="COLOR_GREY"/>
		</FB>
		<FB Name="Button_IE_1" Type="isobus::UT::io::Button::Button_IE" x="300" y="15300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="Button_M2_calibration_area_1a"/>
			<Parameter Name="InputEvent" Value="BT_RELEASED_UNLATCHED"/>
		</FB>
		<FB Name="Button_IE_2" Type="isobus::UT::io::Button::Button_IE" x="300" y="16400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="Button_M2_calibration_area_5a"/>
			<Parameter Name="InputEvent" Value="BT_RELEASED_UNLATCHED"/>
		</FB>
		<FB Name="Button_IE_3" Type="isobus::UT::io::Button::Button_IE" x="300" y="17700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="Button_M2_calibration_area_10a"/>
			<Parameter Name="InputEvent" Value="BT_RELEASED_UNLATCHED"/>
		</FB>
		<FB Name="F_SEL_E_7" Type="eclipse4diac::utils::selection::F_SEL_E_3" x="3100" y="17500">
			<Parameter Name="IN1" Value="COLOR_GREY"/>
			<Parameter Name="IN2" Value="COLOR_GREY"/>
			<Parameter Name="IN3" Value="COLOR_BLUE"/>
		</FB>
		<FB Name="Button_IE_4" Type="isobus::UT::io::Button::Button_IE" x="2440" y="19600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="Button_M2_start"/>
			<Parameter Name="InputEvent" Value="BT_RELEASED_UNLATCHED"/>
		</FB>
		<FB Name="Q_ActiveMask_DataMask_M3" Type="isobus::UT::Q::Q_ActiveMask" x="5400" y="20000">
			<Parameter Name="u16WorkSetId" Value="WorkingSet_0"/>
		</FB>
		<FB Name="F_SEL_E_8" Type="eclipse4diac::utils::selection::F_SEL_E_2" x="3900" y="20400">
			<Parameter Name="IN1" Value="DataMask_M5"/>
			<Parameter Name="IN2" Value="DataMask_M2"/>
		</FB>
		<FB Name="Button_IE_5" Type="isobus::UT::io::Button::Button_IE" x="2400" y="21000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="Button_W1_stop"/>
			<Parameter Name="InputEvent" Value="BT_RELEASED_UNLATCHED"/>
		</FB>
		<FB Name="F_SEL_E_9" Type="eclipse4diac::utils::selection::F_SEL_E_3" x="3200" y="18500">
			<Parameter Name="IN1" Value="UDINT#100"/>
			<Parameter Name="IN2" Value="UDINT#20"/>
			<Parameter Name="IN3" Value="UDINT#10"/>
		</FB>
		<FB Name="F_DIV" Type="iec61131::arithmetic::F_DIV" x="7600" y="18600">
		</FB>
		<FB Name="F_UDINT_TO_UINT" Type="iec61131::conversion::F_UDINT_TO_UINT" x="5800" y="18300">
		</FB>
		<FB Name="Q_NumericValue_4" Type="isobus::UT::Q::Q_NumericValue" x="10600" y="18400">
			<Parameter Name="u16ObjId" Value="NumberVariable_target_quantity_calibration_run"/>
		</FB>
		<FB Name="E_PERMIT" Type="iec61499::events::E_PERMIT" x="1600" y="19300">
		</FB>
		<FB Name="E_SR" Type="iec61499::events::E_SR" x="600" y="19000">
		</FB>
		<FB Name="F_UDINT_TO_UINT_1" Type="iec61131::conversion::F_UDINT_TO_UINT" x="8600" y="19700">
		</FB>
		<FB Name="InputNumber_I3" Type="isobus::UT::io::NumericValue::NumericValue_ID" x="4700" y="25000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="NumberVariable_target_quantity"/>
		</FB>
		<FB Name="F_DWORD_TO_UDINT_2" Type="iec61131::conversion::F_DWORD_TO_UDINT" x="6293.33" y="25200">
		</FB>
		<FB Name="INI_2" Type="eclipse4diac::storage::INI" x="9000" y="24700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="SECTION" Value="SECTION_I3_STORE"/>
			<Parameter Name="KEY" Value="KEY_I3_STORE"/>
			<Parameter Name="DEFAULT_VALUE" Value="UDINT#55"/>
		</FB>
		<FB Name="Q_NumericValue_5" Type="isobus::UT::Q::Q_NumericValue" x="11700" y="24900">
			<Parameter Name="u16ObjId" Value="NumberVariable_target_quantity"/>
		</FB>
		<FB Name="Softkey_IE_start" Type="isobus::UT::io::Softkey::Softkey_IE" x="2300" y="-200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_start"/>
			<Parameter Name="InputEvent" Value="SK_RELEASED"/>
		</FB>
		<FB Name="Softkey_IE_stop" Type="isobus::UT::io::Softkey::Softkey_IE" x="2400" y="1200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_stop"/>
			<Parameter Name="InputEvent" Value="SK_RELEASED"/>
		</FB>
		<FB Name="Q_BackgroundColour" Type="isobus::UT::Q::Q_BackgroundColour" x="6600" y="-200">
			<Parameter Name="u16ObjId" Value="SoftKey_start"/>
		</FB>
		<FB Name="Q_BackgroundColour_1" Type="isobus::UT::Q::Q_BackgroundColour" x="6600" y="1200">
			<Parameter Name="u16ObjId" Value="SoftKey_stop"/>
		</FB>
		<FB Name="E_SR_1" Type="iec61499::events::E_SR" x="4100" y="700">
		</FB>
		<FB Name="F_SEL_1" Type="iec61131::selection::F_SEL" x="5300" y="200">
			<Parameter Name="IN0" Value="COLOR_BLUE"/>
			<Parameter Name="IN1" Value="COLOR_GREY"/>
		</FB>
		<FB Name="F_SEL_2" Type="iec61131::selection::F_SEL" x="5300" y="1200">
			<Parameter Name="IN0" Value="COLOR_GREY"/>
			<Parameter Name="IN1" Value="COLOR_RED"/>
		</FB>
		<FB Name="PWMOutput_Q4" Type="logiBUS::io::DQ::logiBUS_QD_PWM" x="1686.67" y="10300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="OUT" Value="16#FFFFFFFF"/>
			<Parameter Name="Output" Value="Output_Q4"/>
		</FB>
		<FB Name="AnalogInput_I6" Type="logiBUS::io::AI::logiBUS_AI_ID" x="-5900" y="11300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="AnalogInput_I6"/>
			<Parameter Name="AnalogInput_hysteresis" Value="40"/>
		</FB>
		<FB Name="F_DWORD_TO_UDINT_3" Type="iec61131::conversion::F_DWORD_TO_UDINT" x="-3700" y="11800">
		</FB>
		<FB Name="F_DWORD_TO_UDINT_4" Type="iec61131::conversion::F_DWORD_TO_UDINT" x="-5800" y="10600">
		</FB>
		<FB Name="F_MUL" Type="iec61131::arithmetic::F_MUL" x="-2900" y="10600">
			<Parameter Name="IN2" Value="REAL#81.92"/>
		</FB>
		<FB Name="F_REAL_TO_UDINT" Type="iec61131::conversion::F_REAL_TO_UDINT" x="-2100" y="10600">
		</FB>
		<FB Name="F_UDINT_TO_REAL" Type="iec61131::conversion::F_UDINT_TO_REAL" x="-4400" y="10600">
		</FB>
		<FB Name="F_UDINT_TO_DWORD" Type="iec61131::conversion::F_UDINT_TO_DWORD" x="200" y="10600">
		</FB>
		<FB Name="F_LIMIT" Type="iec61131::selection::F_LIMIT" x="-700" y="10600">
			<Parameter Name="MN" Value="UDINT#0"/>
			<Parameter Name="MX" Value="UDINT#8192"/>
		</FB>
		<FB Name="F_NOT" Type="iec61131::bitwiseOperators::F_NOT" x="-6700" y="15900">
		</FB>
		<FB Name="Button_IX" Type="isobus::UT::io::Button::Button_IX" x="300" y="13000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="Button_M1_reset"/>
		</FB>
		<FB Name="logiBUS_QX" Type="logiBUS::io::DQ::logiBUS_QX" x="1800" y="13000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</FB>
		<FB Name="Q_NumericValue_6" Type="isobus::UT::Q::Q_NumericValue" x="-1500" y="11600">
			<Parameter Name="u16ObjId" Value="OutputNumber_M1_weight"/>
		</FB>
		<FB Name="E_DELAY" Type="iec61499::events::E_DELAY" x="-5600" y="200">
			<Parameter Name="DT" Value="T#1s"/>
		</FB>
		<SubApp Name="Speedcontrol" Type="Speedcontrol" x="12100" y="700">
			<Parameter Name="SET_SPEED" Value="REAL#0.0"/>
		</SubApp>
		<FB Name="Button_IE_6" Type="isobus::UT::io::Button::Button_IE" x="8800" y="-2000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="Button_M4_manuel_start"/>
			<Parameter Name="InputEvent" Value="BT_RELEASED_UNLATCHED"/>
		</FB>
		<FB Name="NumericValue_ID" Type="isobus::UT::io::NumericValue::NumericValue_ID" x="8700" y="1400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="NumberVariable_engine_speed_manuel"/>
		</FB>
		<FB Name="F_DWORD_TO_UDINT_5" Type="iec61131::conversion::F_DWORD_TO_UDINT" x="10200" y="2500">
		</FB>
		<FB Name="F_UDINT_TO_REAL_1" Type="iec61131::conversion::F_UDINT_TO_REAL" x="10300" y="1700">
		</FB>
		<FB Name="Q_NumericValue_7" Type="isobus::UT::Q::Q_NumericValue" x="15600" y="600">
			<Parameter Name="u16ObjId" Value="NumberVariable_engine_speed_rpm"/>
		</FB>
		<FB Name="F_REAL_TO_UDINT_1" Type="iec61131::conversion::F_REAL_TO_UDINT" x="13600" y="1200">
		</FB>
		<FB Name="Button_IE_7" Type="isobus::UT::io::Button::Button_IE" x="-6900" y="-1200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="Button_M1_refresh"/>
			<Parameter Name="InputEvent" Value="BT_RELEASED_UNLATCHED"/>
		</FB>
		<EventConnections>
			<Connection Source="Softkey_IE_minus_percent.IND" Destination="F_SUB.REQ" dx1="940"/>
			<Connection Source="Softkey_IE_main.IND" Destination="F_SEL_E_4.REQ1" dx1="746.67"/>
			<Connection Source="Softkey_IE_calibration_run.IND" Destination="F_SEL_E_4.REQ2" dx1="766.67"/>
			<Connection Source="Softkey_IE_settings.IND" Destination="F_SEL_E_4.REQ3" dx1="746.67"/>
			<Connection Source="Q_ActiveMask_DataMask_M2.CNF" Destination="Q_SoftKeyMask.REQ" dx1="1013.33"/>
			<Connection Source="Q_SoftKeyMask.CNF" Destination="Q_SoftKeyMask_2.REQ" dx1="80" dx2="80" dy="493.33"/>
			<Connection Source="Q_SoftKeyMask_2.CNF" Destination="Q_SoftKeyMask_3.REQ" dx1="80" dx2="80" dy="500"/>
			<Connection Source="Q_SoftKeyMask_3.CNF" Destination="Q_SoftKeyMask_4.REQ" dx1="80" dx2="80" dy="493.33"/>
			<Connection Source="Softkey_IE_plus_percent.IND" Destination="F_ADD.REQ" dx1="706.67"/>
			<Connection Source="Softkey_IE_100_percent.IND" Destination="F_SEL_E_3.REQ1" dx1="1760"/>
			<Connection Source="NVS.GETO" Destination="Q_NumericValue_1.REQ" dx1="740"/>
			<Connection Source="CbVtStatus.IND" Destination="Q_NumericValue_1.REQ" dx1="4353.33"/>
			<Connection Source="NVS.INITO" Destination="NVS.GET" dx1="80" dx2="80" dy="-506.67"/>
			<Connection Source="F_SEL_E_2.CNF" Destination="Q_NumericValue.REQ" dx1="286.67"/>
			<Connection Source="Q_NumericValue_1.CNF" Destination="F_SEL_E_2.REQ2" dx1="80" dx2="80" dy="-2146.67"/>
			<Connection Source="InputNumber_I1.IND" Destination="F_DWORD_TO_UDINT.REQ" dx1="293.33"/>
			<Connection Source="F_DWORD_TO_UDINT.CNF" Destination="INI.SET" dx1="80"/>
			<Connection Source="INI.GETO" Destination="Q_NumericValue_2.REQ" dx1="840"/>
			<Connection Source="CbVtStatus_1.IND" Destination="Q_NumericValue_2.REQ" dx1="1560"/>
			<Connection Source="INI.INITO" Destination="INI.GET" dx1="80" dx2="80" dy="-240"/>
			<Connection Source="CbVtStatus_2.IND" Destination="Q_NumericValue_3.REQ" dx1="1560"/>
			<Connection Source="INI_1.INITO" Destination="INI_1.GET" dx1="80" dx2="80" dy="-240"/>
			<Connection Source="F_DWORD_TO_UDINT_1.CNF" Destination="INI_1.SET" dx1="80"/>
			<Connection Source="INI_1.GETO" Destination="Q_NumericValue_3.REQ" dx1="840"/>
			<Connection Source="InputNumber_I2.IND" Destination="F_DWORD_TO_UDINT_1.REQ" dx1="293.33"/>
			<Connection Source="F_SUB.CNF" Destination="F_DINT_TO_UDINT.REQ" dx1="286.67"/>
			<Connection Source="F_DINT_TO_UDINT.CNF" Destination="F_SEL_E_3.REQ3" dx1="80" dx2="80" dy="-640"/>
			<Connection Source="F_DINT_TO_UDINT_1.CNF" Destination="F_SEL_E_3.REQ2" dx1="253.33"/>
			<Connection Source="F_ADD.CNF" Destination="F_DINT_TO_UDINT_1.REQ" dx1="80" dx2="80" dy="-600"/>
			<Connection Source="F_SEL_E_3.CNF" Destination="F_DINT_TO_UDINT_2.REQ" dx1="80" dx2="80" dy="693.33"/>
			<Connection Source="F_DINT_TO_UDINT_2.CNF" Destination="F_SEL_E_2.REQ1" dx1="80" dx2="80" dy="-893.33"/>
			<Connection Source="F_DINT_TO_UDINT_2.CNF" Destination="NVS.SET" dx1="80" dx2="80" dy="1200"/>
			<Connection Source="logiBUS_IX.IND" Destination="F_SEL.REQ" dx1="566.67"/>
			<Connection Source="F_SEL.CNF" Destination="Q_StringValue.REQ" dx1="586.67"/>
			<Connection Source="logiBUS_IX.IND" Destination="Q_ObjHideShow.REQ" dx1="426.67"/>
			<Connection Source="Button_IE_1.IND" Destination="F_SEL_E_5.REQ1" dx1="953.33"/>
			<Connection Source="Button_IE_1.IND" Destination="F_SEL_E_6.REQ1" dx1="953.33"/>
			<Connection Source="Button_IE_2.IND" Destination="F_SEL_E_5.REQ2" dx1="953.33"/>
			<Connection Source="Button_IE_2.IND" Destination="F_SEL_E_6.REQ2" dx1="953.33"/>
			<Connection Source="Button_IE_3.IND" Destination="F_SEL_E_5.REQ3" dx1="953.33"/>
			<Connection Source="Button_IE_3.IND" Destination="F_SEL_E_6.REQ3" dx1="953.33"/>
			<Connection Source="Button_IE_3.IND" Destination="F_SEL_E_7.REQ3" dx1="953.33"/>
			<Connection Source="Button_IE_2.IND" Destination="F_SEL_E_7.REQ2" dx1="953.33"/>
			<Connection Source="Button_IE_1.IND" Destination="F_SEL_E_7.REQ1" dx1="953.33"/>
			<Connection Source="F_SEL_E_5.CNF" Destination="Q_BackgroundColour_3.REQ" dx1="893.33"/>
			<Connection Source="F_SEL_E_6.CNF" Destination="Q_BackgroundColour_4.REQ" dx1="893.33"/>
			<Connection Source="Q_ObjHideShow_1.CNF" Destination="Q_ObjHideShow.REQ" dx1="80" dx2="80" dy="-373.33"/>
			<Connection Source="F_SEL_E_7.CNF" Destination="Q_BackgroundColour_5.REQ" dx1="893.33"/>
			<Connection Source="F_SEL_E_4.CNF" Destination="Q_ActiveMask_DataMask_M1.REQ" dx1="693.33"/>
			<Connection Source="Button_IE_5.IND" Destination="F_SEL_E_8.REQ2" dx1="300"/>
			<Connection Source="Softkey_IE_debug.IND" Destination="F_SEL_E_4.REQ4" dx1="753.33"/>
			<Connection Source="F_SEL_E_8.CNF" Destination="Q_ActiveMask_DataMask_M3.REQ" dx1="386.67"/>
			<Connection Source="Button_IE_1.IND" Destination="F_SEL_E_9.REQ1" dx1="1000"/>
			<Connection Source="Button_IE_2.IND" Destination="F_SEL_E_9.REQ2" dx1="1000"/>
			<Connection Source="Button_IE_3.IND" Destination="F_SEL_E_9.REQ3" dx1="1000"/>
			<Connection Source="F_SEL_E_9.CNF" Destination="F_UDINT_TO_UINT.REQ" dx1="1213.33"/>
			<Connection Source="F_DIV.CNF" Destination="Q_NumericValue_4.REQ" dx1="1233.33"/>
			<Connection Source="Button_IE_4.IND" Destination="E_PERMIT.EI" dx1="80" dx2="80" dy="-360"/>
			<Connection Source="E_PERMIT.EO" Destination="F_SEL_E_8.REQ1" dx1="1433.33"/>
			<Connection Source="F_SEL_E_9.CNF" Destination="E_SR.S" dx1="80" dx2="80" dy="246.67"/>
			<Connection Source="F_UDINT_TO_UINT.CNF" Destination="INI_1.GET" dx1="1153.33"/>
			<Connection Source="INI_1.GETO" Destination="F_UDINT_TO_UINT_1.REQ" dx1="80" dx2="80" dy="-1260"/>
			<Connection Source="F_UDINT_TO_UINT_1.CNF" Destination="F_DIV.REQ" dx1="80" dx2="80" dy="-546.67"/>
			<Connection Source="INI_2.GETO" Destination="Q_NumericValue_5.REQ" dx1="840"/>
			<Connection Source="InputNumber_I3.IND" Destination="F_DWORD_TO_UDINT_2.REQ" dx1="293.33"/>
			<Connection Source="F_DWORD_TO_UDINT_2.CNF" Destination="INI_2.SET" dx1="80"/>
			<Connection Source="INI_2.INITO" Destination="INI_2.GET" dx1="80" dx2="80" dy="-240"/>
			<Connection Source="Softkey_IE_start.IND" Destination="E_SR_1.S" dx1="653.33"/>
			<Connection Source="Softkey_IE_stop.IND" Destination="E_SR_1.R" dx1="600"/>
			<Connection Source="E_SR_1.EO" Destination="F_SEL_1.REQ" dx1="360"/>
			<Connection Source="E_SR_1.EO" Destination="F_SEL_2.REQ" dx1="360"/>
			<Connection Source="F_SEL_2.CNF" Destination="Q_BackgroundColour_1.REQ" dx1="386.67"/>
			<Connection Source="F_SEL_1.CNF" Destination="Q_BackgroundColour.REQ" dx1="386.67"/>
			<Connection Source="Q_ActiveMask_DataMask_M1.CNF" Destination="E_SR_1.R" dx1="646.67"/>
			<Connection Source="AnalogInput_I6.IND" Destination="F_DWORD_TO_UDINT_3.REQ" dx1="420"/>
			<Connection Source="InputNumber_I1.IND" Destination="F_DWORD_TO_UDINT_4.REQ" dx1="80" dx2="80" dy="740"/>
			<Connection Source="InputNumber_I1.INITO" Destination="F_DWORD_TO_UDINT_4.REQ" dx1="80" dx2="80" dy="846.67"/>
			<Connection Source="F_MUL.CNF" Destination="F_REAL_TO_UDINT.REQ"/>
			<Connection Source="F_DWORD_TO_UDINT_4.CNF" Destination="F_UDINT_TO_REAL.REQ"/>
			<Connection Source="F_UDINT_TO_REAL.CNF" Destination="F_MUL.REQ"/>
			<Connection Source="F_UDINT_TO_DWORD.CNF" Destination="PWMOutput_Q4.REQ" dx1="226.67"/>
			<Connection Source="F_REAL_TO_UDINT.CNF" Destination="F_LIMIT.REQ"/>
			<Connection Source="F_LIMIT.CNF" Destination="F_UDINT_TO_DWORD.REQ"/>
			<Connection Source="F_NOT.CNF" Destination="Q_ObjHideShow_1.REQ" dx1="986.67"/>
			<Connection Source="logiBUS_IX.IND" Destination="F_NOT.REQ" dx1="373.33"/>
			<Connection Source="Button_IX.IND" Destination="logiBUS_QX.REQ" dx1="353.33"/>
			<Connection Source="F_DWORD_TO_UDINT_3.CNF" Destination="Q_NumericValue_6.REQ" dx1="433.33"/>
			<Connection Source="Q_ActiveMask_DataMask_M2.INITO" Destination="E_DELAY.START" dx1="80" dx2="80" dy="706.67"/>
			<Connection Source="E_DELAY.EO" Destination="Q_ActiveMask_DataMask_M2.REQ" dx1="93.33"/>
			<Connection Source="E_DELAY.EO" Destination="logiBUS_IX.REQ" dx1="80" dx2="80" dy="6400"/>
			<Connection Source="Softkey_IE_start.IND" Destination="Speedcontrol.START" dx1="3146.67"/>
			<Connection Source="Softkey_IE_stop.IND" Destination="Speedcontrol.STOP" dx1="3100"/>
			<Connection Source="Button_IE.IND" Destination="Speedcontrol.M_STOP" dx1="400"/>
			<Connection Source="Button_IE_6.IND" Destination="Speedcontrol.M_START" dx1="400"/>
			<Connection Source="NumericValue_ID.IND" Destination="F_DWORD_TO_UDINT_5.REQ" dx1="300"/>
			<Connection Source="F_DWORD_TO_UDINT_5.CNF" Destination="F_UDINT_TO_REAL_1.REQ" dx1="80" dx2="80" dy="-300"/>
			<Connection Source="F_UDINT_TO_REAL_1.CNF" Destination="Speedcontrol.REQ_PID" dx1="406.67"/>
			<Connection Source="Speedcontrol.CNF_SPEED" Destination="F_REAL_TO_UDINT_1.REQ" dx1="186.67"/>
			<Connection Source="F_REAL_TO_UDINT_1.CNF" Destination="Q_NumericValue_7.REQ" dx1="246.67"/>
			<Connection Source="Button_IE_7.IND" Destination="Q_ActiveMask_DataMask_M2.REQ" dx1="606.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="Q_NumericValue.u32OldValue" Destination="F_ADD.IN1" dx1="80" dx2="80" dy="293.33"/>
			<Connection Source="Q_NumericValue.u32OldValue" Destination="F_SUB.IN1" dx1="80" dx2="80" dy="786.67"/>
			<Connection Source="NVS.VALUEO" Destination="Q_NumericValue_1.u32NewValue" dx1="726.67"/>
			<Connection Source="F_SEL_E_2.OUT" Destination="Q_NumericValue.u32NewValue" dx1="286.67"/>
			<Connection Source="Q_NumericValue_1.u32OldValue" Destination="F_SEL_E_2.IN2" dx1="80" dx2="80" dy="-2146.67"/>
			<Connection Source="InputNumber_I1.IN" Destination="F_DWORD_TO_UDINT.IN" dx1="306.67"/>
			<Connection Source="F_DWORD_TO_UDINT.OUT" Destination="INI.VALUE" dx1="833.33"/>
			<Connection Source="INI.VALUEO" Destination="Q_NumericValue_2.u32NewValue" dx1="833.33"/>
			<Connection Source="F_DWORD_TO_UDINT_1.OUT" Destination="INI_1.VALUE" dx1="833.33"/>
			<Connection Source="INI_1.VALUEO" Destination="Q_NumericValue_3.u32NewValue" dx1="826.67"/>
			<Connection Source="InputNumber_I2.IN" Destination="F_DWORD_TO_UDINT_1.IN" dx1="306.67"/>
			<Connection Source="F_SUB.OUT" Destination="F_DINT_TO_UDINT.IN" dx1="486.67"/>
			<Connection Source="F_DINT_TO_UDINT.OUT" Destination="F_SEL_E_3.IN3" dx1="80" dx2="80" dy="-480"/>
			<Connection Source="F_DINT_TO_UDINT_1.OUT" Destination="F_SEL_E_3.IN2" dx1="253.33"/>
			<Connection Source="F_ADD.OUT" Destination="F_DINT_TO_UDINT_1.IN" dx1="80" dx2="80" dy="-600"/>
			<Connection Source="F_SEL_E_3.OUT" Destination="F_DINT_TO_UDINT_2.IN" dx1="80" dx2="80" dy="586.67"/>
			<Connection Source="F_DINT_TO_UDINT_2.OUT" Destination="F_SEL_E_2.IN1" dx1="80" dx2="80" dy="-840"/>
			<Connection Source="F_DINT_TO_UDINT_2.OUT" Destination="NVS.VALUE" dx1="80" dx2="80" dy="1413.33"/>
			<Connection Source="F_SEL.OUT" Destination="Q_StringValue.pau8String" dx1="686.67"/>
			<Connection Source="logiBUS_IX.IN" Destination="F_SEL.G" dx1="520"/>
			<Connection Source="logiBUS_IX.IN" Destination="Q_ObjHideShow.qVisible" dx1="333.33"/>
			<Connection Source="F_SEL_E_5.OUT" Destination="Q_BackgroundColour_3.u8Colour" dx1="893.33"/>
			<Connection Source="F_SEL_E_6.OUT" Destination="Q_BackgroundColour_4.u8Colour" dx1="893.33"/>
			<Connection Source="F_SEL_E_7.OUT" Destination="Q_BackgroundColour_5.u8Colour" dx1="893.33"/>
			<Connection Source="F_SEL_E_4.OUT" Destination="Q_ActiveMask_DataMask_M1.u16NewMaskId" dx1="693.33"/>
			<Connection Source="F_SEL_E_8.OUT" Destination="Q_ActiveMask_DataMask_M3.u16NewMaskId" dx1="386.67"/>
			<Connection Source="F_SEL_E_9.OUT" Destination="F_UDINT_TO_UINT.IN" dx1="1213.33"/>
			<Connection Source="F_UDINT_TO_UINT.OUT" Destination="F_DIV.IN2" dx1="126.67"/>
			<Connection Source="F_DIV.OUT" Destination="Q_NumericValue_4.u32NewValue" dx1="1233.33"/>
			<Connection Source="E_SR.Q" Destination="E_PERMIT.PERMIT" dx1="260"/>
			<Connection Source="INI_1.VALUEO" Destination="F_UDINT_TO_UINT_1.IN" dx1="80" dx2="80" dy="-1360"/>
			<Connection Source="F_UDINT_TO_UINT_1.OUT" Destination="F_DIV.IN1" dx1="80" dx2="80" dy="-546.67"/>
			<Connection Source="INI_2.VALUEO" Destination="Q_NumericValue_5.u32NewValue" dx1="826.67"/>
			<Connection Source="InputNumber_I3.IN" Destination="F_DWORD_TO_UDINT_2.IN" dx1="306.67"/>
			<Connection Source="F_DWORD_TO_UDINT_2.OUT" Destination="INI_2.VALUE" dx1="833.33"/>
			<Connection Source="E_SR_1.Q" Destination="F_SEL_1.G" dx1="360"/>
			<Connection Source="E_SR_1.Q" Destination="F_SEL_2.G" dx1="360"/>
			<Connection Source="F_SEL_1.OUT" Destination="Q_BackgroundColour.u8Colour" dx1="386.67"/>
			<Connection Source="F_SEL_2.OUT" Destination="Q_BackgroundColour_1.u8Colour" dx1="386.67"/>
			<Connection Source="AnalogInput_I6.IN" Destination="F_DWORD_TO_UDINT_3.IN" dx1="366.67"/>
			<Connection Source="InputNumber_I1.IN" Destination="F_DWORD_TO_UDINT_4.IN" dx1="80" dx2="80" dy="633.33"/>
			<Connection Source="F_MUL.OUT" Destination="F_REAL_TO_UDINT.IN"/>
			<Connection Source="F_DWORD_TO_UDINT_4.OUT" Destination="F_UDINT_TO_REAL.IN"/>
			<Connection Source="F_UDINT_TO_REAL.OUT" Destination="F_MUL.IN1"/>
			<Connection Source="F_UDINT_TO_DWORD.OUT" Destination="PWMOutput_Q4.OUT" dx1="226.67"/>
			<Connection Source="F_REAL_TO_UDINT.OUT" Destination="F_LIMIT.IN" dx1="200"/>
			<Connection Source="F_LIMIT.OUT" Destination="F_UDINT_TO_DWORD.IN"/>
			<Connection Source="logiBUS_IX.IN" Destination="F_NOT.IN" dx1="373.33"/>
			<Connection Source="F_NOT.OUT" Destination="Q_ObjHideShow_1.qVisible" dx1="986.67"/>
			<Connection Source="Button_IX.IN" Destination="logiBUS_QX.OUT" dx1="353.33"/>
			<Connection Source="F_DWORD_TO_UDINT_3.OUT" Destination="Q_NumericValue_6.u32NewValue" dx1="433.33"/>
			<Connection Source="NumericValue_ID.IN" Destination="F_DWORD_TO_UDINT_5.IN" dx1="300"/>
			<Connection Source="F_UDINT_TO_REAL_1.OUT" Destination="Speedcontrol.M_INPUT" dx1="406.67"/>
			<Connection Source="F_DWORD_TO_UDINT_5.OUT" Destination="F_UDINT_TO_REAL_1.IN" dx1="80" dx2="80" dy="-373.33"/>
			<Connection Source="Speedcontrol.OUTPUT_SPEED" Destination="F_REAL_TO_UDINT_1.IN" dx1="186.67"/>
			<Connection Source="F_REAL_TO_UDINT_1.OUT" Destination="Q_NumericValue_7.u32NewValue" dx1="560"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
