<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="front_fertilizer_main" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="04jul" Date="2026-01-24">
	</VersionInfo>
	<CompilerInfo packageName="Main">
		<Import declaration="DefaultPool::SoftKey_main"/>
		<Import declaration="isobus::UT::io::Softkey::SoftKeyActivationCode::SK_RELEASED"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="-1500" y="-700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IX" x="-4600" y="-700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="Q_SoftKeyMask" Type="isobus::UT::Q::Q_SoftKeyMask" x="-1500" y="400">
			<Parameter Name="u8MaskType" Value="1"/>
			<Parameter Name="u16DataMaskId" Value="1002"/>
			<Parameter Name="u16SoftKeyMaskId" Value="4000"/>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="logiBUS::io::DQ::logiBUS_QX" x="-1300" y="1700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</FB>
		<FB Name="SoftKey_UP_F1" Type="isobus::UT::io::Softkey::Softkey_IE" x="-4600" y="1600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_main"/>
			<Parameter Name="InputEvent" Value="SK_RELEASED"/>
		</FB>
		<FB Name="E_T_FF" Type="iec61499::events::E_T_FF" x="-2960" y="1800">
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I1.IND" Destination="DigitalOutput_Q1.REQ" dx1="953.33"/>
			<Connection Source="DigitalInput_I1.IND" Destination="Q_SoftKeyMask.REQ" dx1="1073.33"/>
			<Connection Source="SoftKey_UP_F1.IND" Destination="E_T_FF.CLK" dx1="366.67"/>
			<Connection Source="E_T_FF.EO" Destination="DigitalOutput_Q2.REQ" dx1="540"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="DigitalOutput_Q1.OUT" dx1="953.33"/>
			<Connection Source="E_T_FF.Q" Destination="DigitalOutput_Q2.OUT" dx1="580"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
