<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Speedcontrol" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="04jul" Date="2026-03-10">
	</VersionInfo>
	<CompilerInfo>
		<Import declaration="logiBUS::io::DO_LED::LED_FREQ::LED_5HZ"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q4"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q5"/>
		<Import declaration="logiBUS::io::PI::logiBUS_PI::PulseInput_I2"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="START" Type="Event">
			</SubAppEvent>
			<SubAppEvent Name="STOP" Type="Event">
			</SubAppEvent>
			<SubAppEvent Name="M_START" Type="Event">
			</SubAppEvent>
			<SubAppEvent Name="M_STOP" Type="Event">
			</SubAppEvent>
			<SubAppEvent Name="REQ_PID" Type="Event">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="CNF_SPEED" Type="Event">
			</SubAppEvent>
		</SubAppEventOutputs>
		<InputVars>
			<VarDeclaration Name="M_INPUT" Type="REAL"/>
			<VarDeclaration Name="SET_SPEED" Type="REAL"/>
			<VarDeclaration Name="P" Type="REAL"/>
			<VarDeclaration Name="I" Type="REAL"/>
			<VarDeclaration Name="DIF" Type="REAL"/>
		</InputVars>
		<OutputVars>
			<VarDeclaration Name="OUTPUT_PWM" Type="UDINT"/>
			<VarDeclaration Name="OUTPUT_SPEED" Type="REAL"/>
		</OutputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="logiBUS_PI_ID" Type="logiBUS::io::PI::logiBUS_PI_ID" x="-4700" y="400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="PulseInput_I2"/>
			<Parameter Name="ImpulseDelta" Value="0"/>
			<Parameter Name="TimeDelta" Value="250"/>
		</FB>
		<FB Name="FT_DERIV" Type="OSCAT::Basic::POUs::Engineering::Control::FT_DERIV_10" x="500" y="-1600">
			<Parameter Name="K" Value="4"/>
			<Parameter Name="Faktor" Value="5.0"/>
			<Parameter Name="run" Value="TRUE"/>
		</FB>
		<FB Name="F_DWORD_TO_UDINT" Type="iec61131::conversion::F_DWORD_TO_UDINT" x="-2900" y="700">
		</FB>
		<FB Name="F_UDINT_TO_REAL" Type="iec61131::conversion::F_UDINT_TO_REAL" x="-1300" y="700">
		</FB>
		<FB Name="PWMOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QD_PWM" x="7300" y="1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q4"/>
		</FB>
		<FB Name="CTRL_PID" Type="OSCAT::Basic::POUs::Engineering::Control::CTRL_PID" x="2600" y="1300">
			<Parameter Name="SET" Value="16.0"/>
			<Parameter Name="SUP" Value="0.0"/>
			<Parameter Name="OFS" Value="0.0"/>
			<Parameter Name="M_I" Value="8184.0"/>
			<Parameter Name="LL" Value="0.0"/>
			<Parameter Name="LH" Value="8192.0"/>
		</FB>
		<FB Name="F_LREAL_TO_UDINT" Type="iec61131::conversion::F_LREAL_TO_UDINT" x="3900" y="1300">
		</FB>
		<FB Name="F_UDINT_TO_DWORD" Type="iec61131::conversion::F_UDINT_TO_DWORD" x="5500" y="1300">
		</FB>
		<FB Name="E_CYCLE" Type="iec61499::events::E_CYCLE" x="-6500" y="500">
			<Parameter Name="DT" Value="T#500ms"/>
		</FB>
		<FB Name="E_SR" Type="iec61499::events::E_SR" x="-2100" y="2500">
		</FB>
		<FB Name="F_DIV" Type="iec61131::arithmetic::F_DIV" x="-1160" y="-20">
			<Parameter Name="IN2" Value="UDINT#12"/>
		</FB>
		<EventConnections>
			<Connection Source="F_DWORD_TO_UDINT.CNF" Destination="F_UDINT_TO_REAL.REQ"/>
			<Connection Source="F_UDINT_TO_REAL.CNF" Destination="FT_DERIV.REQ" dx1="160"/>
			<Connection Source="FT_DERIV.CNF" Destination="CTRL_PID.REQ" dx1="1220"/>
			<Connection Source="CTRL_PID.CNF" Destination="F_LREAL_TO_UDINT.REQ"/>
			<Connection Source="F_LREAL_TO_UDINT.CNF" Destination="F_UDINT_TO_DWORD.REQ"/>
			<Connection Source="F_UDINT_TO_DWORD.CNF" Destination="PWMOutput_Q1.REQ" dx1="380"/>
			<Connection Source="E_CYCLE.EO" Destination="logiBUS_PI_ID.REQ" dx1="593.33"/>
			<Connection Source="START" Destination="E_CYCLE.START" dx1="593.33"/>
			<Connection Source="E_SR.EO" Destination="CTRL_PID.REQ" dx1="2006.67"/>
			<Connection Source="M_START" Destination="E_SR.S" dx1="3266.67"/>
			<Connection Source="M_STOP" Destination="E_SR.R" dx1="2733.33"/>
			<Connection Source="START" Destination="E_SR.R" dx1="3033.33"/>
			<Connection Source="M_STOP" Destination="CTRL_PID.RST" dx1="3380"/>
			<Connection Source="STOP" Destination="CTRL_PID.RST" dx1="6426.67"/>
			<Connection Source="REQ_PID" Destination="CTRL_PID.REQ" dx1="6380"/>
			<Connection Source="FT_DERIV.CNF" Destination="CNF_SPEED" dx1="4300"/>
			<Connection Source="M_START" Destination="E_CYCLE.START" dx1="1833.33"/>
			<Connection Source="STOP" Destination="E_CYCLE.STOP" dx1="1833.33"/>
			<Connection Source="M_STOP" Destination="E_CYCLE.STOP" dx1="1833.33"/>
			<Connection Source="F_DWORD_TO_UDINT.CNF" Destination="F_DIV.REQ" dx1="346.67"/>
			<Connection Source="logiBUS_PI_ID.IND" Destination="F_DWORD_TO_UDINT.REQ" dx1="406.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="logiBUS_PI_ID.IN" Destination="F_DWORD_TO_UDINT.IN" dx1="406.67"/>
			<Connection Source="F_DWORD_TO_UDINT.OUT" Destination="F_UDINT_TO_REAL.IN"/>
			<Connection Source="F_UDINT_TO_REAL.OUT" Destination="FT_DERIV.in" dx1="353.33"/>
			<Connection Source="FT_DERIV.out" Destination="CTRL_PID.ACT" dx1="766.67"/>
			<Connection Source="CTRL_PID.Y" Destination="F_LREAL_TO_UDINT.IN" dx1="340"/>
			<Connection Source="F_LREAL_TO_UDINT.OUT" Destination="F_UDINT_TO_DWORD.IN"/>
			<Connection Source="F_UDINT_TO_DWORD.OUT" Destination="PWMOutput_Q1.OUT" dx1="380"/>
			<Connection Source="M_INPUT" Destination="CTRL_PID.M_I" dx1="3353.33"/>
			<Connection Source="F_LREAL_TO_UDINT.OUT" Destination="OUTPUT_PWM" dx1="3653.33"/>
			<Connection Source="E_SR.Q" Destination="CTRL_PID.MAN" dx1="2006.67"/>
			<Connection Source="SET_SPEED" Destination="CTRL_PID.SET" dx1="6380"/>
			<Connection Source="FT_DERIV.out" Destination="OUTPUT_SPEED" dx1="4300"/>
			<Connection Source="F_DWORD_TO_UDINT.OUT" Destination="F_DIV.IN1" dx1="346.67"/>
			<Connection Source="P" Destination="CTRL_PID.KP" dx1="6380"/>
			<Connection Source="I" Destination="CTRL_PID.TN" dx1="6380"/>
			<Connection Source="DIF" Destination="CTRL_PID.TV" dx1="6380"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
