<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Change_Softkey_Mask" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="04jul" Date="2026-01-24">
	</VersionInfo>
	<CompilerInfo>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="-1500" y="-700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IX" x="-4600" y="-700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="Q_SoftKeyMask" Type="isobus::UT::Q::Q_SoftKeyMask" x="-1500" y="400">
			<Parameter Name="u8MaskType" Value="1"/>
			<Parameter Name="u16DataMaskId" Value="4000"/>
			<Parameter Name="u16SoftKeyMaskId" Value="1002"/>
		</FB>
		<FB Name="Q_ActiveMask" Type="isobus::UT::Q::Q_ActiveMask" x="-1500" y="1500">
			<Parameter Name="u16WorkSetId" Value="0"/>
			<Parameter Name="u16NewMaskId" Value="1003"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I1.IND" Destination="DigitalOutput_Q1.REQ" dx1="953.33"/>
			<Connection Source="DigitalInput_I1.IND" Destination="Q_SoftKeyMask.REQ" dx1="1073.33"/>
			<Connection Source="DigitalInput_I1.IND" Destination="Q_ActiveMask.REQ" dx1="1173.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="DigitalOutput_Q1.OUT" dx1="953.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
