<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_012a" Comment="Numeric Value Input und Speichern">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::NVS::NVS_Keys::KEY_I1_STORE"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::InputNumber_I1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="CbVtStatus" Type="isobus::UT::status::CbVtStatus" x="-5900" y="1500">
		</FB>
		<SubApp Name="Uebung_012a_sub" Type="Uebungen::Uebung_012a_sub" x="-3200" y="1600">
			<Parameter Name="KEY" Value="KEY_I1_STORE"/>
			<Parameter Name="u16ObjId" Value="InputNumber_I1"/>
		</SubApp>
		<EventConnections>
			<Connection Source="CbVtStatus.IND" Destination="Uebung_012a_sub.REQ"/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
