<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_010c2" Comment="SoftKey_F1 auf DigitalOutput_Q1 mit GreenWhiteBackground mit Subapp">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO_S"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="Uebung_10c2_sub" x="-4600" y="-500">
			<SubAppInterfaceList>
				<InputVars>
					<VarDeclaration Name="u16ObjId" Type="UINT" Comment="Object ID" InitialValue="SoftKey_F1"/>
					<VarDeclaration Name="Output" Type="logiBUS::io::DQ::logiBUS_DO_S" Comment="Identify the Output Output_Q1..Q8" InitialValue="logiBUS_DO::Output_Q1"/>
				</InputVars>
			</SubAppInterfaceList>
			<SubAppNetwork>
				<SubApp Name="GreenWhiteBackground" Type="MyLib::sys::GreenWhiteBackground" x="3200" y="1200">
				</SubApp>
				<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="3200" y="200">
					<Parameter Name="QI" Value="TRUE"/>
					<Parameter Name="PARAMS" Value="">
						<Attribute Name="Visible" Value="false"/>
					</Parameter>
				</FB>
				<FB Name="SoftKey_F1" Type="isobus::UT::io::Softkey::Softkey_IX" x="200" y="0">
					<Parameter Name="QI" Value="TRUE"/>
				</FB>
				<EventConnections>
					<Connection Source="SoftKey_F1.IND" Destination="GreenWhiteBackground.REQ" dx1="1240"/>
					<Connection Source="SoftKey_F1.IND" Destination="DigitalOutput_Q1.REQ" dx1="1653.33"/>
				</EventConnections>
				<DataConnections>
					<Connection Source="SoftKey_F1.IN" Destination="GreenWhiteBackground.DI1" dx1="1060"/>
					<Connection Source="SoftKey_F1.IN" Destination="DigitalOutput_Q1.OUT" dx1="1100"/>
					<Connection Source="u16ObjId" Destination="SoftKey_F1.u16ObjId" dx1="2446.67">
						<Attribute Name="Visible" Value="false"/>
					</Connection>
					<Connection Source="u16ObjId" Destination="GreenWhiteBackground.u16ObjId" dx1="3893.33">
						<Attribute Name="Visible" Value="false"/>
					</Connection>
					<Connection Source="Output" Destination="DigitalOutput_Q1.Output" dx1="4046.67">
						<Attribute Name="Visible" Value="false"/>
					</Connection>
				</DataConnections>
			</SubAppNetwork>
			<Attribute Name="width" Type="LREAL" Value="200"/>
			<Attribute Name="height" Type="LREAL" Value="100"/>
		</SubApp>
	</SubAppNetwork>
</SubAppType>
