<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_002a" Comment="DigitalInput_I1/_I2 mit AND auf DigitalOutput_Q1">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="-700" y="-500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IX" x="-4533.33" y="-933.33">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="DigitalInput_I2" Type="logiBUS::io::DI::logiBUS_IX" x="-4533.33" y="133.33">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
		</FB>
		<FB Name="AND_2" Type="iec61131::bitwiseOperators::AND_2" x="-2000" y="-400">
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I1.IND" Destination="AND_2.REQ" dx1="920"/>
			<Connection Source="DigitalInput_I2.IND" Destination="AND_2.REQ" dx1="920"/>
			<Connection Source="AND_2.CNF" Destination="DigitalOutput_Q1.REQ" dx1="220"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="AND_2.OUT" Destination="DigitalOutput_Q1.OUT" dx1="206.67"/>
			<Connection Source="DigitalInput_I1.IN" Destination="AND_2.IN1" dx1="1493.33"/>
			<Connection Source="DigitalInput_I2.IN" Destination="AND_2.IN2" dx1="1480"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
