<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_070" Comment="WBSD auf UT ausgeben">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool_TECU::NumberVariable_Wheel_based_machine_speed"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="I_WBSD" Type="isobus::tecu::I_WBSD" x="-5200" y="500">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="Q_NumericValue" Type="isobus::UT::Q::Q_NumericValue" x="-700" y="500">
			<Parameter Name="u16ObjId" Value="NumberVariable_Wheel_based_machine_speed"/>
		</FB>
		<EventConnections>
			<Connection Source="I_WBSD.IND" Destination="Q_NumericValue.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="I_WBSD.WHEELBASEDMACHINESPEED" Destination="Q_NumericValue.u32NewValue" dx1="1433.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
