<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_020c3" Comment="DigitalInput_I1 auf DigitalOutput_Q1; FB_TON; Einschaltverzögert">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="-5200" y="700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IX" x="-10600" y="300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="FB_TON" Type="iec61131::timers::FB_TON" x="-7100" y="800">
			<Parameter Name="PT" Value="T#5s"/>
		</FB>
		<FB Name="E_SWITCH_I1" Type="iec61499::events::E_SWITCH" x="-9300" y="500">
		</FB>
		<FB Name="E_CYCLE" Type="iec61499::events::E_CYCLE" x="-8200" y="500">
			<Parameter Name="DT" Value="T#500ms"/>
		</FB>
		<Comment Comment="E_CYCLE bestimmt, &#10;wie oft FB_TON den ET aktualisert" x="-8900" y="0" width="1000" height="400"/>
		<EventConnections>
			<Connection Source="FB_TON.CNF" Destination="DigitalOutput_Q1.REQ"/>
			<Connection Source="E_CYCLE.EO" Destination="FB_TON.REQ" dx1="193.33"/>
			<Connection Source="DigitalInput_I1.IND" Destination="E_SWITCH_I1.EI"/>
			<Connection Source="E_SWITCH_I1.EO0" Destination="E_CYCLE.STOP" dx1="220"/>
			<Connection Source="E_SWITCH_I1.EO1" Destination="E_CYCLE.START" dx1="220"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="FB_TON.IN" dx1="173.33"/>
			<Connection Source="FB_TON.Q" Destination="DigitalOutput_Q1.OUT" dx1="666.67"/>
			<Connection Source="DigitalInput_I1.IN" Destination="E_SWITCH_I1.G" dx1="153.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
