<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_029" Comment="LED_DO Blinkende LED">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I3"/>
		<Import declaration="logiBUS::io::DO_LED::LED_FREQ"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="LED_Q1_5HZ" Type="logiBUS::io::DO_LED::logiBUS_LED_DO_QX" x="-1500" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
			<Parameter Name="FREQ" Value="LED_FREQ::LED_5HZ"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IX" x="-4500" y="-1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="LED_Q1_1HZ" Type="logiBUS::io::DO_LED::logiBUS_LED_DO_QX" x="-1500" y="300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
			<Parameter Name="FREQ" Value="LED_FREQ::LED_1HZ"/>
		</FB>
		<FB Name="DigitalInput_I2" Type="logiBUS::io::DI::logiBUS_IX" x="-4500" y="200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
		</FB>
		<FB Name="LED_Q1_ON" Type="logiBUS::io::DO_LED::logiBUS_LED_DO_QX" x="-1500" y="1500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
			<Parameter Name="FREQ" Value="LED_FREQ::LED_ON"/>
		</FB>
		<FB Name="DigitalInput_I3" Type="logiBUS::io::DI::logiBUS_IX" x="-4500" y="1400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I3"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I1.IND" Destination="LED_Q1_5HZ.REQ" dx1="1126.67"/>
			<Connection Source="DigitalInput_I2.IND" Destination="LED_Q1_1HZ.REQ" dx1="1126.67"/>
			<Connection Source="DigitalInput_I3.IND" Destination="LED_Q1_ON.REQ" dx1="1126.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="LED_Q1_5HZ.OUT" dx1="1126.67"/>
			<Connection Source="DigitalInput_I2.IN" Destination="LED_Q1_1HZ.OUT" dx1="1126.67"/>
			<Connection Source="DigitalInput_I3.IN" Destination="LED_Q1_ON.OUT" dx1="1126.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
