<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_140" Comment="Übung zu SYS_ONTIME (Betriebsstundenzähler)">
	<Identification Standard="61499-2" Description="Copyright (c) 2025 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SYS_ONTIME" Type="logiBUS::signalprocessing::measurement::SYS_ONTIME" x="-1400" y="-400">
		</FB>
	</SubAppNetwork>
</SubAppType>
