<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_060" Comment="für TC-SC also Task Controller Section Control">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="TCPool::DE_NUM_DEVICE"/>
		<Import declaration="Uebungen::const::TC::DDI::ACTUAL_CONDENSED_WORK_STATE_1_16"/>
		<Import declaration="Uebungen::const::TC::DDI::ACTUAL_VOLUME_PER_AREA_APPLICATION_RATE"/>
		<Import declaration="Uebungen::const::TC::DDI::ACTUAL_WORK_STATE"/>
		<Import declaration="Uebungen::const::TC::DDI::SECTION_CONTROL_STATE"/>
		<Import declaration="Uebungen::const::TC::DDI::SETPOINT_CONDENSED_WORK_STATE_1_16"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SETPOINT_CONDENSED_WORK_STATE_1_16" Type="isobus::TC::io::TC_ID" x="-1700" y="-8900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="wDevElementNumb" Value="DE_NUM_DEVICE"/>
			<Parameter Name="wDDI" Value="SETPOINT_CONDENSED_WORK_STATE_1_16"/>
		</FB>
		<FB Name="SPLIT_DWORD_INTO_QUARTERS" Type="eclipse4diac::utils::splitting::SPLIT_DWORD_INTO_QUARTERS" x="700" y="-8700">
		</FB>
		<FB Name="ASSEMBLE_DWORD_FROM_QUARTERS" Type="eclipse4diac::utils::assembling::ASSEMBLE_DWORD_FROM_QUARTERS" x="7300" y="-8700">
		</FB>
		<FB Name="ACTUAL_CONDENSED_WORK_STATE_1_16" Type="isobus::TC::io::TC_QD" x="12506.67" y="-8800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="wDevElementNumb" Value="DE_NUM_DEVICE"/>
			<Parameter Name="wDDI" Value="ACTUAL_CONDENSED_WORK_STATE_1_16"/>
		</FB>
		<FB Name="BOOLS_TO_QUARTERS" Type="logiBUS::utils::quarter::BOOLS_TO_QUARTERS" x="5700" y="-8700">
		</FB>
		<FB Name="QUARTERS_TO_BOOLS" Type="logiBUS::utils::quarter::QUARTERS_TO_BOOLS" x="3100" y="-8700">
		</FB>
		<SubApp Name="Out" Type="Uebungen::Uebung_060_sub_Outputs" x="6800" y="-10700">
		</SubApp>
		<FB Name="SECTION_CONTROL_STATE_IN" Type="isobus::TC::io::TC_ID" x="10900" y="-7700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="wDevElementNumb" Value="DE_NUM_DEVICE"/>
			<Parameter Name="wDDI" Value="SECTION_CONTROL_STATE"/>
		</FB>
		<FB Name="SECTION_CONTROL_STATE_OUT" Type="isobus::TC::io::TC_QD" x="13466.67" y="-7600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="wDevElementNumb" Value="DE_NUM_DEVICE"/>
			<Parameter Name="wDDI" Value="SECTION_CONTROL_STATE"/>
		</FB>
		<FB Name="ACTUAL_RATE" Type="isobus::TC::io::TC_QD" x="13900" y="-9900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="wDevElementNumb" Value="DE_NUM_DEVICE"/>
			<Parameter Name="wDDI" Value="ACTUAL_VOLUME_PER_AREA_APPLICATION_RATE"/>
		</FB>
		<FB Name="ACTUAL_WORK_STATE" Type="isobus::TC::io::TC_QD" x="12700" y="-10900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="wDevElementNumb" Value="DE_NUM_DEVICE"/>
			<Parameter Name="wDDI" Value="ACTUAL_WORK_STATE"/>
		</FB>
		<FB Name="F_SEL" Type="iec61131::selection::F_SEL" x="10800" y="-9600">
			<Parameter Name="IN0" Value="DWORD#0"/>
			<Parameter Name="IN1" Value="DWORD#1"/>
		</FB>
		<FB Name="F_GT" Type="iec61131::comparison::F_GT" x="9800" y="-9600">
			<Parameter Name="IN2" Value="DWORD#0"/>
		</FB>
		<EventConnections>
			<Connection Source="SETPOINT_CONDENSED_WORK_STATE_1_16.IND" Destination="SPLIT_DWORD_INTO_QUARTERS.REQ" dx1="553.33"/>
			<Connection Source="ASSEMBLE_DWORD_FROM_QUARTERS.CNF" Destination="ACTUAL_CONDENSED_WORK_STATE_1_16.REQ" dx1="1233.33"/>
			<Connection Source="BOOLS_TO_QUARTERS.CNF" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.REQ" dx1="260"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.CNF" Destination="QUARTERS_TO_BOOLS.REQ" dx1="473.33"/>
			<Connection Source="QUARTERS_TO_BOOLS.CNF" Destination="BOOLS_TO_QUARTERS.REQ" dx1="760"/>
			<Connection Source="QUARTERS_TO_BOOLS.CNF" Destination="Out.CNF" dx1="226.67"/>
			<Connection Source="SECTION_CONTROL_STATE_IN.IND" Destination="SECTION_CONTROL_STATE_OUT.REQ" dx1="833.33"/>
			<Connection Source="F_GT.CNF" Destination="F_SEL.REQ"/>
			<Connection Source="ASSEMBLE_DWORD_FROM_QUARTERS.CNF" Destination="F_GT.REQ" dx1="360"/>
			<Connection Source="F_SEL.CNF" Destination="ACTUAL_WORK_STATE.REQ" dx1="120"/>
			<Connection Source="F_SEL.CNF" Destination="ACTUAL_RATE.REQ" dx1="340"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="SETPOINT_CONDENSED_WORK_STATE_1_16.IN" Destination="SPLIT_DWORD_INTO_QUARTERS.IN" dx1="266.67"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_00" Destination="BOOLS_TO_QUARTERS.I_00" dx1="760"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_02" Destination="BOOLS_TO_QUARTERS.I_02" dx1="760"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_01" Destination="BOOLS_TO_QUARTERS.I_01" dx1="760"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_03" Destination="BOOLS_TO_QUARTERS.I_03" dx1="760"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_04" Destination="BOOLS_TO_QUARTERS.I_04" dx1="760"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_05" Destination="BOOLS_TO_QUARTERS.I_05" dx1="760"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_06" Destination="BOOLS_TO_QUARTERS.I_06" dx1="760"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_07" Destination="BOOLS_TO_QUARTERS.I_07" dx1="760"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_08" Destination="BOOLS_TO_QUARTERS.I_08" dx1="760"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_09" Destination="BOOLS_TO_QUARTERS.I_09" dx1="760"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_10" Destination="BOOLS_TO_QUARTERS.I_10" dx1="760"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_11" Destination="BOOLS_TO_QUARTERS.I_11" dx1="760"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_12" Destination="BOOLS_TO_QUARTERS.I_12" dx1="760"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_13" Destination="BOOLS_TO_QUARTERS.I_13" dx1="760"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_14" Destination="BOOLS_TO_QUARTERS.I_14" dx1="760"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_15" Destination="BOOLS_TO_QUARTERS.I_15" dx1="760"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_06" Destination="Out.Q_06" dx1="1173.33"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_00" Destination="Out.Q_00" dx1="353.33"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_04" Destination="Out.Q_04" dx1="873.33"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_01" Destination="Out.Q_01" dx1="446.67"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_05" Destination="Out.Q_05" dx1="1026.67"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_07" Destination="Out.Q_07" dx1="1260"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_02" Destination="Out.Q_02" dx1="526.67"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_03" Destination="Out.Q_03" dx1="746.67"/>
			<Connection Source="QUARTERS_TO_BOOLS.Q_08" Destination="Out.Q_08" dx1="1340"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_00" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.QUARTER_BYTE_00" dx1="260"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_01" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.QUARTER_BYTE_01" dx1="260"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_02" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.QUARTER_BYTE_02" dx1="260"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_03" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.QUARTER_BYTE_03" dx1="260"/>
			<Connection Source="ASSEMBLE_DWORD_FROM_QUARTERS." Destination="ACTUAL_CONDENSED_WORK_STATE_1_16.OUT" dx1="1133.33"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_04" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.QUARTER_BYTE_04" dx1="260"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_05" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.QUARTER_BYTE_05" dx1="260"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_06" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.QUARTER_BYTE_06" dx1="260"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_07" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.QUARTER_BYTE_07" dx1="260"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_08" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.QUARTER_BYTE_08" dx1="260"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_09" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.QUARTER_BYTE_09" dx1="260"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_10" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.QUARTER_BYTE_10" dx1="260"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_11" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.QUARTER_BYTE_11" dx1="260"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_12" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.QUARTER_BYTE_12" dx1="260"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_13" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.QUARTER_BYTE_13" dx1="260"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_14" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.QUARTER_BYTE_14" dx1="260"/>
			<Connection Source="BOOLS_TO_QUARTERS.QB_15" Destination="ASSEMBLE_DWORD_FROM_QUARTERS.QUARTER_BYTE_15" dx1="260"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.QUARTER_BYTE_00" Destination="QUARTERS_TO_BOOLS.IB_00" dx1="473.33"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.QUARTER_BYTE_01" Destination="QUARTERS_TO_BOOLS.IB_01" dx1="473.33"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.QUARTER_BYTE_02" Destination="QUARTERS_TO_BOOLS.IB_02" dx1="473.33"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.QUARTER_BYTE_03" Destination="QUARTERS_TO_BOOLS.IB_03" dx1="473.33"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.QUARTER_BYTE_04" Destination="QUARTERS_TO_BOOLS.IB_04" dx1="473.33"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.QUARTER_BYTE_15" Destination="QUARTERS_TO_BOOLS.IB_15" dx1="473.33"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.QUARTER_BYTE_14" Destination="QUARTERS_TO_BOOLS.IB_14" dx1="473.33"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.QUARTER_BYTE_13" Destination="QUARTERS_TO_BOOLS.IB_13" dx1="473.33"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.QUARTER_BYTE_12" Destination="QUARTERS_TO_BOOLS.IB_12" dx1="473.33"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.QUARTER_BYTE_11" Destination="QUARTERS_TO_BOOLS.IB_11" dx1="473.33"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.QUARTER_BYTE_10" Destination="QUARTERS_TO_BOOLS.IB_10" dx1="473.33"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.QUARTER_BYTE_09" Destination="QUARTERS_TO_BOOLS.IB_09" dx1="473.33"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.QUARTER_BYTE_08" Destination="QUARTERS_TO_BOOLS.IB_08" dx1="473.33"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.QUARTER_BYTE_07" Destination="QUARTERS_TO_BOOLS.IB_07" dx1="473.33"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.QUARTER_BYTE_06" Destination="QUARTERS_TO_BOOLS.IB_06" dx1="473.33"/>
			<Connection Source="SPLIT_DWORD_INTO_QUARTERS.QUARTER_BYTE_05" Destination="QUARTERS_TO_BOOLS.IB_05" dx1="473.33"/>
			<Connection Source="SECTION_CONTROL_STATE_IN.IN" Destination="SECTION_CONTROL_STATE_OUT.OUT" dx1="833.33"/>
			<Connection Source="F_GT.OUT" Destination="F_SEL.G"/>
			<Connection Source="ASSEMBLE_DWORD_FROM_QUARTERS." Destination="F_GT.IN1" dx1="553.33"/>
			<Connection Source="F_SEL.OUT" Destination="ACTUAL_RATE.OUT" dx1="1286.67"/>
			<Connection Source="F_SEL.OUT" Destination="ACTUAL_WORK_STATE.OUT" dx1="213.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
