<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_039_sub_Outputs" Comment="Spiegelabfolge V2 mit Schrittkette SUB Out">
	<Identification Standard="61499-2" Description="Copyright (c) 2024 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2024-03-03">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="isobus::UT::Q::const::IDs::ID_NULL"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO_S"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="REQ" Type="Event" Comment="Service Request">
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="OUT" Type="BOOL" Comment="Output data to resource"/>
			<VarDeclaration Name="u16ObjId" Type="UINT" Comment="Object ID Softkey/Button" InitialValue="ID_NULL"/>
			<VarDeclaration Name="Output" Type="logiBUS::io::DQ::logiBUS_DO_S" InitialValue="logiBUS_DO::Invalid"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="QX" Type="logiBUS::io::DQ::logiBUS_QX" x="-500" y="-700">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="IX" Type="isobus::UT::io::Softkey::Softkey_IX" x="-3800" y="-1000">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="OR_2" Type="iec61131::bitwiseOperators::OR_2" x="-2140" y="-193.33">
		</FB>
		<SubApp Name="GreenWhiteBackground" Type="MyLib::sys::GreenWhiteBackground" x="900" y="0">
		</SubApp>
		<EventConnections>
			<Connection Source="OR_2.CNF" Destination="QX.REQ" dx1="260"/>
			<Connection Source="IX.IND" Destination="OR_2.REQ" dx1="500"/>
			<Connection Source="REQ" Destination="OR_2.REQ" dx1="1393.33"/>
			<Connection Source="QX.CNF" Destination="GreenWhiteBackground.REQ" dx1="233.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="OUT" Destination="OR_2.IN2" dx1="1426.67"/>
			<Connection Source="IX.IN" Destination="OR_2.IN1" dx1="240"/>
			<Connection Source="OR_2.OUT" Destination="QX.OUT" dx1="260"/>
			<Connection Source="OR_2.OUT" Destination="GreenWhiteBackground.DI1" dx1="153.33"/>
			<Connection Source="u16ObjId" Destination="GreenWhiteBackground.u16ObjId" dx1="7860">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="u16ObjId" Destination="IX.u16ObjId" dx1="1880">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="Output" Destination="QX.Output" dx1="6980"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
