<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_010c3" Comment="SoftKey_F1 auf DigitalOutput_Q1 mit GreenWhiteBackground mit Typed Subapp">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="Uebung_010c3_sub" Type="Uebungen::Uebung_010c3_sub" x="-4600" y="-500">
			<Parameter Name="u16ObjId" Value="SoftKey_F1"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</SubApp>
	</SubAppNetwork>
</SubAppType>
