<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_120" Comment="Übung zu ISOBUS Name">
	<Identification Standard="61499-2" Description="Copyright (c) 2025 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="isobus::pgn::ISOUSERHOME_e::network"/>
		<Import declaration="isobus::pgn::ISO_CAN_NODE::NODE1"/>
		<Import declaration="Uebungen::const::Uebung_120_129::Filter::FLT_ALL_PASS"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="NmGetCfInfo" Type="isobus::pgn::NmGetCfInfo" x="-1300" y="6400">
			<Parameter Name="u8CanIdx" Value="NODE1"/>
			<Parameter Name="member" Value="network"/>
			<Parameter Name="address" Value="FLT_ALL_PASS"/>
			<Parameter Name="mask" Value="FLT_ALL_PASS"/>
		</FB>
		<FB Name="STRUCT_DEMUX_2" Type="eclipse4diac::convert::STRUCT_DEMUX" x="1300" y="7800">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::CF_INFO_T"/>
		</FB>
		<FB Name="STRUCT_DEMUX_3" Type="eclipse4diac::convert::STRUCT_DEMUX" x="1100" y="4600">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="NmSetNameField" Type="isobus::pgn::NmSetNameField" x="2600" y="5900">
		</FB>
		<FB Name="NmSetNameField_1" Type="isobus::pgn::NmSetNameField" x="3000" y="9300">
		</FB>
		<FB Name="STRUCT_DEMUX" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6200" y="5900">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::NAMEFIELD_T"/>
		</FB>
		<FB Name="STRUCT_DEMUX_1" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6400" y="9300">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::NAMEFIELD_T"/>
		</FB>
		<Comment Comment="mit einem Event an RSP wird der nächste ACL abgefragt." x="-2500" y="6000" width="1700" height="300"/>
		<EventConnections>
			<Connection Source="NmGetCfInfo.IND" Destination="STRUCT_DEMUX_3.REQ" dx1="513.33"/>
			<Connection Source="NmGetCfInfo.IND" Destination="STRUCT_DEMUX_2.REQ" dx1="866.67"/>
			<Connection Source="STRUCT_DEMUX_3.CNF" Destination="NmSetNameField.REQ" dx1="526.67"/>
			<Connection Source="STRUCT_DEMUX_2.CNF" Destination="NmSetNameField_1.REQ" dx1="586.67"/>
			<Connection Source="NmSetNameField.CNF" Destination="STRUCT_DEMUX.REQ"/>
			<Connection Source="NmSetNameField_1.CNF" Destination="STRUCT_DEMUX_1.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="NmGetCfInfo.sNetEv" Destination="STRUCT_DEMUX_3.IN" dx1="733.33"/>
			<Connection Source="NmGetCfInfo.sCfInfo" Destination="STRUCT_DEMUX_2.IN" dx1="733.33"/>
			<Connection Source="STRUCT_DEMUX_3.cfName" Destination="NmSetNameField.au8IsoName" dx1="133.33"/>
			<Connection Source="STRUCT_DEMUX_2.au8Name" Destination="NmSetNameField_1.au8IsoName" dx1="386.67"/>
			<Connection Source="NmSetNameField." Destination="STRUCT_DEMUX.IN" dx1="1133.33"/>
			<Connection Source="NmSetNameField_1." Destination="STRUCT_DEMUX_1.IN" dx1="533.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
