<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_011a2" Comment="Numeric Value Output und BUTTON_PRESS_REPEAT_DONE">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::OutputNumber_N1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_LONG_PRESS_UP"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Q_NumericValue" Type="isobus::UT::Q::Q_NumericValue" x="900" y="1000">
			<Parameter Name="u16ObjId" Value="OutputNumber_N1"/>
		</FB>
		<FB Name="logiBUS_ID" Type="logiBUS::io::DI::logiBUS_ID" x="-3700" y="800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_LONG_PRESS_UP"/>
		</FB>
		<FB Name="F_DWORD_TO_UDINT" Type="iec61131::conversion::F_DWORD_TO_UDINT" x="-1900" y="1200">
		</FB>
		<Comment Comment="BUTTON_PRESS_UP&#10;BUTTON_LONG_PRESS_HOLD&#10;BUTTON_LONG_PRESS_UP" x="-5100" y="2100" width="3100" height="600"/>
		<EventConnections>
			<Connection Source="logiBUS_ID.IND" Destination="F_DWORD_TO_UDINT.REQ" dx1="613.33"/>
			<Connection Source="F_DWORD_TO_UDINT.CNF" Destination="Q_NumericValue.REQ" dx1="860"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="logiBUS_ID.IN" Destination="F_DWORD_TO_UDINT.IN" dx1="353.33"/>
			<Connection Source="F_DWORD_TO_UDINT.OUT" Destination="Q_NumericValue.u32NewValue"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
