<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_12x_sub" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2025-10-22">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
	</CompilerInfo>
	<SubAppInterfaceList>
		<Plugs>
			<AdapterDeclaration Name="PLUG1" Type="isobus::pgn::tx::Callback"/>
		</Plugs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="CallbackFB" Type="isobus::pgn::tx::CallbackFB" x="-400" y="200">
			<Parameter Name="DI1" Value="(data := [16#FF, 16#FF, 16#FF, 16#FF, 16#FF, 16#FF, 16#FF, 16#FF])"/>
		</FB>
		<FB Name="E_CTU" Type="iec61499::events::E_CTU" x="1800" y="-200">
			<Parameter Name="PV" Value="UINT#0"/>
		</FB>
		<FB Name="STRUCT_MUX" Type="eclipse4diac::convert::STRUCT_MUX" x="-2400" y="100">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::CAN_MSG"/>
			<Parameter Name="u16DaSize" Value="0"/>
			<Parameter Name="u8Priority" Value="7"/>
		</FB>
		<FB Name="BYTES_TO_ARR08B" Type="logiBUS::utils::conversion::arr::reversing::BYTES_TO_ARR08B" x="-4500" y="200">
			<Parameter Name="IN_01" Value="16#00"/>
			<Parameter Name="IN_02" Value="16#00"/>
			<Parameter Name="IN_03" Value="16#00"/>
			<Parameter Name="IN_04" Value="16#00"/>
			<Parameter Name="IN_05" Value="16#00"/>
			<Parameter Name="IN_06" Value="16#00"/>
			<Parameter Name="IN_07" Value="16#00"/>
		</FB>
		<FB Name="F_USINT_TO_BYTE" Type="iec61131::conversion::F_UINT_TO_BYTE" x="-6300" y="200">
		</FB>
		<EventConnections>
			<Connection Source="CallbackFB.REQ" Destination="E_CTU.CU" dx1="573.33"/>
			<Connection Source="STRUCT_MUX.CNF" Destination="CallbackFB.CNF" dx1="626.67"/>
			<Connection Source="BYTES_TO_ARR08B.CNF" Destination="STRUCT_MUX.REQ" dx1="560"/>
			<Connection Source="F_USINT_TO_BYTE.CNF" Destination="BYTES_TO_ARR08B.REQ" dx1="433.33"/>
			<Connection Source="E_CTU.CUO" Destination="F_USINT_TO_BYTE.REQ" dx1="80" dx2="80" dy="-493.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="STRUCT_MUX.OUT" Destination="CallbackFB.DI1" dx1="1173.33"/>
			<Connection Source="BYTES_TO_ARR08B.OUT" Destination="STRUCT_MUX.data" dx1="506.67"/>
			<Connection Source="F_USINT_TO_BYTE.OUT" Destination="BYTES_TO_ARR08B.IN_00" dx1="433.33"/>
			<Connection Source="E_CTU.CV" Destination="F_USINT_TO_BYTE.IN" dx1="300" dx2="413.33" dy="-1060"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="CallbackFB.PLUG1" Destination="PLUG1" dx1="4780"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
