<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_012b" Comment="Numeric Value Input und Speichern">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::NVS::NVS_Keys::KEY_I1_STORE"/>
		<Import declaration="Uebungen::const::NVS::NVS_Keys::SECTION_I1_STORE"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::InputNumber_I1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="F_DWORD_TO_UDINT" Type="iec61131::conversion::F_DWORD_TO_UDINT" x="-3600" y="1200">
		</FB>
		<FB Name="InputNumber_I1" Type="isobus::UT::io::NumericValue::NumericValue_ID" x="-5200" y="1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="InputNumber_I1"/>
		</FB>
		<FB Name="INI" Type="eclipse4diac::storage::INI" x="-900" y="700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="SECTION" Value="SECTION_I1_STORE"/>
			<Parameter Name="KEY" Value="KEY_I1_STORE"/>
			<Parameter Name="DEFAULT_VALUE" Value="UDINT#55"/>
		</FB>
		<FB Name="Q_NumericValue" Type="isobus::UT::Q::Q_NumericValue" x="1800" y="900">
			<Parameter Name="u16ObjId" Value="InputNumber_I1"/>
		</FB>
		<FB Name="CbVtStatus" Type="isobus::UT::status::CbVtStatus" x="-1100" y="-900">
		</FB>
		<EventConnections>
			<Connection Source="InputNumber_I1.IND" Destination="F_DWORD_TO_UDINT.REQ"/>
			<Connection Source="F_DWORD_TO_UDINT.CNF" Destination="INI.SET" dx1="80"/>
			<Connection Source="INI.GETO" Destination="Q_NumericValue.REQ" dx1="840"/>
			<Connection Source="CbVtStatus.IND" Destination="Q_NumericValue.REQ" dx1="1560"/>
			<Connection Source="INI.INITO" Destination="INI.GET" dx1="80" dx2="80" dy="-240"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="InputNumber_I1.IN" Destination="F_DWORD_TO_UDINT.IN" dx1="306.67"/>
			<Connection Source="F_DWORD_TO_UDINT.OUT" Destination="INI.VALUE" dx1="833.33"/>
			<Connection Source="INI.VALUEO" Destination="Q_NumericValue.u32NewValue" dx1="840"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
