<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_020i" Comment="DigitalInput_I1 auf DigitalOutput_Q1; E_PULSE; Impulsformend; Teach-In">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="-10700" y="500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="E_PULSE" Type="iec61499::events::timers::E_PULSE" x="-12300" y="600">
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="logiBUS::io::DI::logiBUS_IE" x="-14100" y="400">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="E_STOPWATCH" Type="eclipse4diac::utils::timing::E_STOPWATCH" x="-13700" y="1500">
		</FB>
		<FB Name="E_SWITCH" Type="iec61499::events::E_SWITCH" x="-15100" y="1700">
		</FB>
		<FB Name="DigitalInput_I2" Type="logiBUS::io::DI::logiBUS_IX" x="-16500" y="1500">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Input" Value="Input_I2"/>
		</FB>
		<EventConnections>
			<Connection Source="E_PULSE.CNF" Destination="DigitalOutput_Q1.REQ" dx1="320"/>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="E_PULSE.REQ" dx1="460"/>
			<Connection Source="DigitalInput_I2.IND" Destination="E_SWITCH.EI" dx1="320"/>
			<Connection Source="E_SWITCH.EO1" Destination="E_STOPWATCH.START" dx1="286.67"/>
			<Connection Source="E_SWITCH.EO0" Destination="E_STOPWATCH.STOP" dx1="366.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_PULSE.Q" Destination="DigitalOutput_Q1.OUT" dx1="506.67"/>
			<Connection Source="E_STOPWATCH.TD" Destination="E_PULSE.PT" dx1="326.67"/>
			<Connection Source="DigitalInput_I2.IN" Destination="E_SWITCH.G" dx1="386.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
