<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_121" Comment="Übung zu ISOBUS Name">
	<Identification Standard="61499-2" Description="Copyright (c) 2025 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="isobus::pgn::ISOUSERHOME_e::thisMember"/>
		<Import declaration="isobus::pgn::ISO_CAN_NODE::NODE1"/>
		<Import declaration="Uebungen::const::Uebung_120_129::Filter::FLT_ALL_PASS"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="STRUCT_DEMUX" Type="eclipse4diac::convert::STRUCT_DEMUX" x="2400" y="1400">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::NAMEFIELD_T"/>
		</FB>
		<FB Name="STRUCT_MUX" Type="eclipse4diac::convert::STRUCT_MUX" x="300" y="1400">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::NAMEFIELD_T"/>
		</FB>
		<FB Name="NmSetName" Type="isobus::pgn::NmSetName" x="500" y="4500">
		</FB>
		<FB Name="NmSetNameField" Type="isobus::pgn::NmSetNameField" x="1900" y="4500">
		</FB>
		<FB Name="STRUCT_MUX_1" Type="eclipse4diac::convert::STRUCT_MUX" x="-1600" y="4500">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::NAMEFIELD_T"/>
		</FB>
		<FB Name="STRUCT_DEMUX_1" Type="eclipse4diac::convert::STRUCT_DEMUX" x="4300" y="4500">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::NAMEFIELD_T"/>
		</FB>
		<FB Name="NmGetCfInfo" Type="isobus::pgn::NmGetCfInfo" x="-1300" y="6400">
			<Parameter Name="u8CanIdx" Value="NODE1"/>
			<Parameter Name="member" Value="thisMember"/>
			<Parameter Name="address" Value="FLT_ALL_PASS"/>
			<Parameter Name="mask" Value="FLT_ALL_PASS"/>
		</FB>
		<FB Name="STRUCT_DEMUX_2" Type="eclipse4diac::convert::STRUCT_DEMUX" x="1400" y="7000">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::CF_INFO_T"/>
		</FB>
		<FB Name="STRUCT_DEMUX_3" Type="eclipse4diac::convert::STRUCT_DEMUX" x="1400" y="5900">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<EventConnections>
			<Connection Source="STRUCT_MUX.CNF" Destination="STRUCT_DEMUX.REQ" dx1="673.33"/>
			<Connection Source="NmSetName.CNF" Destination="NmSetNameField.REQ"/>
			<Connection Source="STRUCT_MUX_1.CNF" Destination="NmSetName.REQ" dx1="453.33"/>
			<Connection Source="NmSetNameField.CNF" Destination="STRUCT_DEMUX_1.REQ" dx1="733.33"/>
			<Connection Source="NmGetCfInfo.IND" Destination="STRUCT_DEMUX_3.REQ" dx1="513.33"/>
			<Connection Source="NmGetCfInfo.IND" Destination="STRUCT_DEMUX_2.REQ" dx1="866.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="STRUCT_MUX.OUT" Destination="STRUCT_DEMUX.IN" dx1="673.33"/>
			<Connection Source="STRUCT_MUX_1.OUT" Destination="NmSetName.psNameField" dx1="180"/>
			<Connection Source="NmSetName." Destination="NmSetNameField.au8IsoName"/>
			<Connection Source="NmSetNameField." Destination="STRUCT_DEMUX_1.IN" dx1="733.33"/>
			<Connection Source="NmGetCfInfo.sNetEv" Destination="STRUCT_DEMUX_3.IN" dx1="733.33"/>
			<Connection Source="NmGetCfInfo.sCfInfo" Destination="STRUCT_DEMUX_2.IN" dx1="733.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
