<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_122" Comment="Übung zu ISOBUS Name">
	<Identification Standard="61499-2" Description="Copyright (c) 2025 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="isobus::pgn::ISOUSERHOME_e::network"/>
		<Import declaration="isobus::pgn::ISO_CAN_NODE::NODE1"/>
		<Import declaration="Uebungen::const::Uebung_120_129::Filter::FLT_ALL_PASS"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="NmGetCfInfo" Type="isobus::pgn::NmGetCfInfo" x="-3300" y="-2200">
			<Parameter Name="u8CanIdx" Value="NODE1"/>
			<Parameter Name="member" Value="network"/>
			<Parameter Name="address" Value="FLT_ALL_PASS"/>
			<Parameter Name="mask" Value="FLT_ALL_PASS"/>
		</FB>
		<FB Name="LOG_16" Type="logiBUS::utils::logging::LOG_16" x="-1700" y="-2100">
		</FB>
		<FB Name="SD_A_1" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6306.67" y="-12273.33">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="SD_A_2" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6306.67" y="-10886.67">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="SD_A_3" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6306.67" y="-9500">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="SD_A_4" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6306.67" y="-8113.33">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="SD_A_5" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6306.67" y="-6726.67">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="SD_A_6" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6306.67" y="-5340">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="SD_A_7" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6306.67" y="-3953.33">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="SD_A_8" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6373.33" y="-2566.67">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="SD_A_9" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6373.33" y="-1180">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="SD_A_10" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6306.67" y="206.67">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="SD_A_11" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6306.67" y="1593.33">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="SD_A_12" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6306.67" y="2980">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="SD_A_13" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6306.67" y="4366.67">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="SD_A_14" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6306.67" y="5753.33">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="SD_A_15" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6306.67" y="7140">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="SD_A_16" Type="eclipse4diac::convert::STRUCT_DEMUX" x="6306.67" y="8526.67">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::ISONETEVENT_T"/>
		</FB>
		<FB Name="NmSetNF_1" Type="isobus::pgn::NmSetNameField" x="10500" y="-12300">
		</FB>
		<FB Name="NmSetNF_2" Type="isobus::pgn::NmSetNameField" x="10500" y="-10886.67">
		</FB>
		<FB Name="NmSetNF_3" Type="isobus::pgn::NmSetNameField" x="10500" y="-9500">
		</FB>
		<FB Name="NmSetNF_4" Type="isobus::pgn::NmSetNameField" x="10500" y="-8113.33">
		</FB>
		<FB Name="NmSetNF_5" Type="isobus::pgn::NmSetNameField" x="10500" y="-6726.67">
		</FB>
		<FB Name="NmSetNF_6" Type="isobus::pgn::NmSetNameField" x="10500" y="-5340">
		</FB>
		<FB Name="NmSetNF_7" Type="isobus::pgn::NmSetNameField" x="10500" y="-3953.33">
		</FB>
		<FB Name="NmSetNF_8" Type="isobus::pgn::NmSetNameField" x="10500" y="-2566.67">
		</FB>
		<FB Name="NmSetNF_9" Type="isobus::pgn::NmSetNameField" x="10500" y="-1180">
		</FB>
		<FB Name="NmSetNF_10" Type="isobus::pgn::NmSetNameField" x="10500" y="206.67">
		</FB>
		<FB Name="NmSetNF_11" Type="isobus::pgn::NmSetNameField" x="10500" y="1593.33">
		</FB>
		<FB Name="NmSetNF_12" Type="isobus::pgn::NmSetNameField" x="10500" y="2980">
		</FB>
		<FB Name="NmSetNF_13" Type="isobus::pgn::NmSetNameField" x="10500" y="4366.67">
		</FB>
		<FB Name="NmSetNF_14" Type="isobus::pgn::NmSetNameField" x="10500" y="5753.33">
		</FB>
		<FB Name="NmSetNF_15" Type="isobus::pgn::NmSetNameField" x="10500" y="7140">
		</FB>
		<FB Name="NmSetNF_16" Type="isobus::pgn::NmSetNameField" x="10500" y="8526.67">
		</FB>
		<FB Name="SD_C_1" Type="eclipse4diac::convert::STRUCT_DEMUX" x="14100" y="-12273.33">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::NAMEFIELD_T"/>
		</FB>
		<FB Name="SD_C_2" Type="eclipse4diac::convert::STRUCT_DEMUX" x="13200" y="-10900">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::NAMEFIELD_T"/>
		</FB>
		<FB Name="SD_C_3" Type="eclipse4diac::convert::STRUCT_DEMUX" x="14100" y="-9500">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::NAMEFIELD_T"/>
		</FB>
		<FB Name="SD_C_4" Type="eclipse4diac::convert::STRUCT_DEMUX" x="13100" y="-8200">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::NAMEFIELD_T"/>
		</FB>
		<FB Name="SD_C_5" Type="eclipse4diac::convert::STRUCT_DEMUX" x="14100" y="-6726.67">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::NAMEFIELD_T"/>
		</FB>
		<FB Name="SD_C_6" Type="eclipse4diac::convert::STRUCT_DEMUX" x="13100" y="-5400">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::NAMEFIELD_T"/>
		</FB>
		<FB Name="SD_C_7" Type="eclipse4diac::convert::STRUCT_DEMUX" x="14100" y="-3953.33">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::NAMEFIELD_T"/>
		</FB>
		<FB Name="SD_C_8" Type="eclipse4diac::convert::STRUCT_DEMUX" x="13000" y="-2500">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::NAMEFIELD_T"/>
		</FB>
		<FB Name="SD_C_9" Type="eclipse4diac::convert::STRUCT_DEMUX" x="14100" y="-1180">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::NAMEFIELD_T"/>
		</FB>
		<FB Name="SD_C_10" Type="eclipse4diac::convert::STRUCT_DEMUX" x="12900" y="100">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::NAMEFIELD_T"/>
		</FB>
		<FB Name="SD_C_11" Type="eclipse4diac::convert::STRUCT_DEMUX" x="14100" y="1593.33">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::NAMEFIELD_T"/>
		</FB>
		<FB Name="SD_C_12" Type="eclipse4diac::convert::STRUCT_DEMUX" x="12900" y="2800">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::NAMEFIELD_T"/>
		</FB>
		<FB Name="SD_C_13" Type="eclipse4diac::convert::STRUCT_DEMUX" x="14100" y="4366.67">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::NAMEFIELD_T"/>
		</FB>
		<FB Name="SD_C_14" Type="eclipse4diac::convert::STRUCT_DEMUX" x="13000" y="5700">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::NAMEFIELD_T"/>
		</FB>
		<FB Name="SD_C_15" Type="eclipse4diac::convert::STRUCT_DEMUX" x="14100" y="7140">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::NAMEFIELD_T"/>
		</FB>
		<FB Name="SD_C_16" Type="eclipse4diac::convert::STRUCT_DEMUX" x="12900" y="8400">
			<Attribute Name="StructuredType" Type="STRING" Value="isobus::pgn::NAMEFIELD_T"/>
		</FB>
		<EventConnections>
			<Connection Source="NmGetCfInfo.IND" Destination="LOG_16.REQ" dx1="220"/>
			<Connection Source="LOG_16.CNF" Destination="SD_A_1.REQ" dx1="533.33"/>
			<Connection Source="LOG_16.CNF" Destination="SD_A_2.REQ" dx1="533.33"/>
			<Connection Source="LOG_16.CNF" Destination="SD_A_3.REQ" dx1="533.33"/>
			<Connection Source="LOG_16.CNF" Destination="SD_A_4.REQ" dx1="533.33"/>
			<Connection Source="LOG_16.CNF" Destination="SD_A_5.REQ" dx1="533.33"/>
			<Connection Source="LOG_16.CNF" Destination="SD_A_6.REQ" dx1="533.33"/>
			<Connection Source="LOG_16.CNF" Destination="SD_A_7.REQ" dx1="533.33"/>
			<Connection Source="LOG_16.CNF" Destination="SD_A_8.REQ" dx1="533.33"/>
			<Connection Source="LOG_16.CNF" Destination="SD_A_9.REQ" dx1="533.33"/>
			<Connection Source="LOG_16.CNF" Destination="SD_A_10.REQ" dx1="533.33"/>
			<Connection Source="LOG_16.CNF" Destination="SD_A_11.REQ" dx1="533.33"/>
			<Connection Source="LOG_16.CNF" Destination="SD_A_12.REQ" dx1="533.33"/>
			<Connection Source="LOG_16.CNF" Destination="SD_A_13.REQ" dx1="533.33"/>
			<Connection Source="LOG_16.CNF" Destination="SD_A_14.REQ" dx1="533.33"/>
			<Connection Source="LOG_16.CNF" Destination="SD_A_15.REQ" dx1="533.33"/>
			<Connection Source="LOG_16.CNF" Destination="SD_A_16.REQ" dx1="533.33"/>
			<Connection Source="SD_A_1.CNF" Destination="NmSetNF_1.REQ" dx1="1600"/>
			<Connection Source="NmSetNF_1.CNF" Destination="SD_C_1.REQ" dx1="1320"/>
			<Connection Source="SD_A_2.CNF" Destination="NmSetNF_2.REQ"/>
			<Connection Source="NmSetNF_2.CNF" Destination="SD_C_2.REQ" dx1="873.33"/>
			<Connection Source="SD_A_3.CNF" Destination="NmSetNF_3.REQ"/>
			<Connection Source="NmSetNF_3.CNF" Destination="SD_C_3.REQ"/>
			<Connection Source="SD_A_4.CNF" Destination="NmSetNF_4.REQ"/>
			<Connection Source="NmSetNF_4.CNF" Destination="SD_C_4.REQ" dx1="826.67"/>
			<Connection Source="SD_A_5.CNF" Destination="NmSetNF_5.REQ"/>
			<Connection Source="NmSetNF_5.CNF" Destination="SD_C_5.REQ"/>
			<Connection Source="SD_A_6.CNF" Destination="NmSetNF_6.REQ"/>
			<Connection Source="NmSetNF_6.CNF" Destination="SD_C_6.REQ" dx1="826.67"/>
			<Connection Source="SD_A_7.CNF" Destination="NmSetNF_7.REQ"/>
			<Connection Source="NmSetNF_7.CNF" Destination="SD_C_7.REQ"/>
			<Connection Source="SD_A_8.CNF" Destination="NmSetNF_8.REQ"/>
			<Connection Source="NmSetNF_8.CNF" Destination="SD_C_8.REQ" dx1="773.33"/>
			<Connection Source="SD_A_9.CNF" Destination="NmSetNF_9.REQ"/>
			<Connection Source="NmSetNF_9.CNF" Destination="SD_C_9.REQ"/>
			<Connection Source="SD_A_10.CNF" Destination="NmSetNF_10.REQ"/>
			<Connection Source="NmSetNF_10.CNF" Destination="SD_C_10.REQ" dx1="726.67"/>
			<Connection Source="SD_A_11.CNF" Destination="NmSetNF_11.REQ"/>
			<Connection Source="NmSetNF_11.CNF" Destination="SD_C_11.REQ"/>
			<Connection Source="SD_A_12.CNF" Destination="NmSetNF_12.REQ"/>
			<Connection Source="NmSetNF_12.CNF" Destination="SD_C_12.REQ" dx1="726.67"/>
			<Connection Source="SD_A_13.CNF" Destination="NmSetNF_13.REQ"/>
			<Connection Source="NmSetNF_13.CNF" Destination="SD_C_13.REQ"/>
			<Connection Source="SD_A_14.CNF" Destination="NmSetNF_14.REQ"/>
			<Connection Source="NmSetNF_14.CNF" Destination="SD_C_14.REQ" dx1="773.33"/>
			<Connection Source="SD_A_15.CNF" Destination="NmSetNF_15.REQ"/>
			<Connection Source="NmSetNF_15.CNF" Destination="SD_C_15.REQ"/>
			<Connection Source="SD_A_16.CNF" Destination="NmSetNF_16.REQ"/>
			<Connection Source="NmSetNF_16.CNF" Destination="SD_C_16.REQ" dx1="726.67"/>
			<Connection Source="LOG_16.CNF" Destination="NmGetCfInfo.RSP" dx1="80" dx2="80" dy="-453.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="NmGetCfInfo.sNetEv" Destination="LOG_16.IN" dx1="220"/>
			<Connection Source="LOG_16.OUT1" Destination="SD_A_1.IN" dx1="80"/>
			<Connection Source="LOG_16.OUT2" Destination="SD_A_2.IN" dx1="133.33"/>
			<Connection Source="LOG_16.OUT3" Destination="SD_A_3.IN" dx1="200"/>
			<Connection Source="LOG_16.OUT4" Destination="SD_A_4.IN" dx1="266.67"/>
			<Connection Source="LOG_16.OUT5" Destination="SD_A_5.IN" dx1="333.33"/>
			<Connection Source="LOG_16.OUT6" Destination="SD_A_6.IN" dx1="400"/>
			<Connection Source="LOG_16.OUT7" Destination="SD_A_7.IN" dx1="466.67"/>
			<Connection Source="LOG_16.OUT8" Destination="SD_A_8.IN" dx1="600"/>
			<Connection Source="LOG_16.OUT9" Destination="SD_A_9.IN" dx1="600"/>
			<Connection Source="LOG_16.OUT10" Destination="SD_A_10.IN" dx1="466.67"/>
			<Connection Source="LOG_16.OUT11" Destination="SD_A_11.IN" dx1="400"/>
			<Connection Source="LOG_16.OUT12" Destination="SD_A_12.IN" dx1="333.33"/>
			<Connection Source="LOG_16.OUT13" Destination="SD_A_13.IN" dx1="266.67"/>
			<Connection Source="LOG_16.OUT14" Destination="SD_A_14.IN" dx1="200"/>
			<Connection Source="LOG_16.OUT15" Destination="SD_A_15.IN" dx1="133.33"/>
			<Connection Source="LOG_16.OUT16" Destination="SD_A_16.IN" dx1="66.67"/>
			<Connection Source="SD_A_1.cfName" Destination="NmSetNF_1.au8IsoName" dx1="1646.67"/>
			<Connection Source="SD_A_2.cfName" Destination="NmSetNF_2.au8IsoName" dx1="1646.67"/>
			<Connection Source="SD_A_3.cfName" Destination="NmSetNF_3.au8IsoName" dx1="1646.67"/>
			<Connection Source="SD_A_4.cfName" Destination="NmSetNF_4.au8IsoName" dx1="1646.67"/>
			<Connection Source="SD_A_5.cfName" Destination="NmSetNF_5.au8IsoName" dx1="1646.67"/>
			<Connection Source="SD_A_6.cfName" Destination="NmSetNF_6.au8IsoName" dx1="1646.67"/>
			<Connection Source="SD_A_7.cfName" Destination="NmSetNF_7.au8IsoName" dx1="1646.67"/>
			<Connection Source="SD_A_8.cfName" Destination="NmSetNF_8.au8IsoName" dx1="1620"/>
			<Connection Source="SD_A_9.cfName" Destination="NmSetNF_9.au8IsoName" dx1="1620"/>
			<Connection Source="SD_A_10.cfName" Destination="NmSetNF_10.au8IsoName" dx1="1646.67"/>
			<Connection Source="SD_A_11.cfName" Destination="NmSetNF_11.au8IsoName" dx1="1646.67"/>
			<Connection Source="SD_A_12.cfName" Destination="NmSetNF_12.au8IsoName" dx1="1646.67"/>
			<Connection Source="SD_A_13.cfName" Destination="NmSetNF_13.au8IsoName" dx1="1646.67"/>
			<Connection Source="SD_A_14.cfName" Destination="NmSetNF_14.au8IsoName" dx1="1646.67"/>
			<Connection Source="SD_A_15.cfName" Destination="NmSetNF_15.au8IsoName" dx1="1646.67"/>
			<Connection Source="SD_A_16.cfName" Destination="NmSetNF_16.au8IsoName" dx1="1646.67"/>
			<Connection Source="NmSetNF_1." Destination="SD_C_1.IN" dx1="1266.67"/>
			<Connection Source="NmSetNF_2." Destination="SD_C_2.IN" dx1="1266.67"/>
			<Connection Source="NmSetNF_3." Destination="SD_C_3.IN" dx1="1266.67"/>
			<Connection Source="NmSetNF_4." Destination="SD_C_4.IN" dx1="1266.67"/>
			<Connection Source="NmSetNF_5." Destination="SD_C_5.IN" dx1="1266.67"/>
			<Connection Source="NmSetNF_6." Destination="SD_C_6.IN" dx1="1266.67"/>
			<Connection Source="NmSetNF_7." Destination="SD_C_7.IN" dx1="1266.67"/>
			<Connection Source="NmSetNF_8." Destination="SD_C_8.IN" dx1="1266.67"/>
			<Connection Source="NmSetNF_9." Destination="SD_C_9.IN" dx1="1266.67"/>
			<Connection Source="NmSetNF_10." Destination="SD_C_10.IN"/>
			<Connection Source="NmSetNF_11." Destination="SD_C_11.IN" dx1="1266.67"/>
			<Connection Source="NmSetNF_12." Destination="SD_C_12.IN" dx1="1266.67"/>
			<Connection Source="NmSetNF_13." Destination="SD_C_13.IN" dx1="1266.67"/>
			<Connection Source="NmSetNF_14." Destination="SD_C_14.IN" dx1="1266.67"/>
			<Connection Source="NmSetNF_15." Destination="SD_C_15.IN" dx1="1266.67"/>
			<Connection Source="NmSetNF_16." Destination="SD_C_16.IN" dx1="1266.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
