<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_015a" Comment="Object Pointer umschalten -- 3-fach">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="isobus::UT::io::Softkey::SoftKeyActivationCode::SK_RELEASED"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::Button_A1"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::Button_A2"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::ObjectPointer_P1"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F1"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F2"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F3"/>
		<Import declaration="isobus::UT::Q::const::IDs::ID_NULL"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SoftKey_UP_F1" Type="isobus::UT::io::Softkey::Softkey_IE" x="-5600" y="-1100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_F1"/>
			<Parameter Name="InputEvent" Value="SK_RELEASED"/>
		</FB>
		<FB Name="SoftKey_UP_F2" Type="isobus::UT::io::Softkey::Softkey_IE" x="-5600" y="200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_F2"/>
			<Parameter Name="InputEvent" Value="SK_RELEASED"/>
		</FB>
		<FB Name="F_UINT_TO_UDINT" Type="iec61131::conversion::F_UINT_TO_UDINT" x="-2800" y="0">
			<Parameter Name="IN" Value="Button_A1"/>
		</FB>
		<FB Name="F_SEL_E_3" Type="eclipse4diac::utils::selection::F_SEL_E_3" x="-1100" y="-900">
			<Parameter Name="IN1" Value="ID_NULL"/>
		</FB>
		<FB Name="Q_NumericValue" Type="isobus::UT::Q::Q_NumericValue" x="1100" y="-1000">
			<Parameter Name="u16ObjId" Value="ObjectPointer_P1"/>
		</FB>
		<FB Name="SoftKey_UP_F3" Type="isobus::UT::io::Softkey::Softkey_IE" x="-5600" y="1400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_F3"/>
			<Parameter Name="InputEvent" Value="SK_RELEASED"/>
		</FB>
		<FB Name="F_UINT_TO_UDINT_1" Type="iec61131::conversion::F_UINT_TO_UDINT" x="-2833.33" y="566.67">
			<Parameter Name="IN" Value="Button_A2"/>
		</FB>
		<EventConnections>
			<Connection Source="F_SEL_E_3.CNF" Destination="Q_NumericValue.REQ" dx1="573.33"/>
			<Connection Source="SoftKey_UP_F1.IND" Destination="F_SEL_E_3.REQ1"/>
			<Connection Source="SoftKey_UP_F2.IND" Destination="F_SEL_E_3.REQ2" dx1="280"/>
			<Connection Source="SoftKey_UP_F3.IND" Destination="F_SEL_E_3.REQ3" dx1="446.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="F_UINT_TO_UDINT.OUT" Destination="F_SEL_E_3.IN2" dx1="360"/>
			<Connection Source="F_SEL_E_3.OUT" Destination="Q_NumericValue.u32NewValue" dx1="600"/>
			<Connection Source="F_UINT_TO_UDINT_1.OUT" Destination="F_SEL_E_3.IN3" dx1="500"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
