<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_039a" Comment="Spiegelabfolge V2 mit Schrittkette">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0&#10;   &#10;Spiegelabfolge V2 mit Schrittkette  &#10;geeignet für hydraulisches Ringsystem 3/2 Wege Ventile  (z.B. Claas) &#10;oder pneumatische 5/2 Wege Ventile  &#10;">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="isobus::UT::io::Softkey::SoftKeyActivationCode::SK_RELEASED"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F1"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F2"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F8"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I3"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I4"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
		<Import declaration="logiBUS::utils::sequence::const::sequence::NO_TIME"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="E_TimeOut" Type="iec61499::events::E_TimeOut" x="-9200" y="2000">
		</FB>
		<FB Name="DigitalInput_DOWN_I1" Type="logiBUS::io::DI::logiBUS_IE" x="-13300" y="100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="DigitalInput_DOWN_I2" Type="logiBUS::io::DI::logiBUS_IE" x="-13300" y="1200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="DigitalInput_DOWN_I3" Type="logiBUS::io::DI::logiBUS_IE" x="-13300" y="2200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I3"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="DigitalInput_DOWN_I4" Type="logiBUS::io::DI::logiBUS_IE" x="-13300" y="3200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I4"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="sequence_05" Type="logiBUS::utils::sequence::combi::sequence_ET_05" x="-10700" y="-200">
			<Parameter Name="DT_S1_S2" Value="NO_TIME"/>
			<Parameter Name="DT_S2_S3" Value="NO_TIME"/>
			<Parameter Name="DT_S3_S4" Value="T#5s"/>
			<Parameter Name="DT_S4_S5" Value="NO_TIME"/>
			<Parameter Name="DT_S5_START" Value="NO_TIME"/>
		</FB>
		<SubApp Name="NumbAnzeig" Type="Uebungen::Uebung_039_sub_NumbAnzeig" x="-8766.67" y="-986.67">
		</SubApp>
		<FB Name="SoftKey_UP_F1" Type="isobus::UT::io::Softkey::Softkey_IE" x="-14900" y="-400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_F1"/>
			<Parameter Name="InputEvent" Value="SK_RELEASED"/>
		</FB>
		<SubApp Name="Q1" Type="Uebungen::Uebung_039a_sub_Outputs" x="-7000" y="-100">
			<Parameter Name="u16ObjId" Value="SoftKey_F8"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</SubApp>
		<SubApp Name="Q2" Type="Uebungen::Uebung_039a_sub_Outputs" x="-7000" y="600">
			<Parameter Name="u16ObjId" Value="SoftKey_F2"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</SubApp>
		<EventConnections>
			<Connection Source="DigitalInput_DOWN_I1.IND" Destination="sequence_05.S1_S2" dx1="313.33"/>
			<Connection Source="DigitalInput_DOWN_I2.IND" Destination="sequence_05.S2_S3" dx1="380"/>
			<Connection Source="DigitalInput_DOWN_I3.IND" Destination="sequence_05.S4_S5" dx1="446.67"/>
			<Connection Source="DigitalInput_DOWN_I4.IND" Destination="sequence_05.S5_START" dx1="513.33"/>
			<Connection Source="sequence_05.CNF" Destination="NumbAnzeig.CNF" dx1="73.33"/>
			<Connection Source="SoftKey_UP_F1.IND" Destination="sequence_05.START_S1" dx1="1660"/>
			<Connection Source="sequence_05.EO_S1" Destination="Q1.SET" dx1="1206.67"/>
			<Connection Source="sequence_05.EO_S2" Destination="Q2.SET" dx1="1053.33"/>
			<Connection Source="sequence_05.EO_S4" Destination="Q2.RESET" dx1="906.67"/>
			<Connection Source="sequence_05.EO_S5" Destination="Q1.RESET" dx1="1226.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="sequence_05.STATE_NR" Destination="NumbAnzeig.STATE_NR" dx1="340"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="sequence_05.timeOut" Destination="E_TimeOut.TimeOutSocket" dx1="240"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
