<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_017" Comment="Control Audio Signal">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="isobus::UT::io::Softkey::SoftKeyActivationCode::SK_RELEASED"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SoftKey_UP_F1" Type="isobus::UT::io::Softkey::Softkey_IE" x="-4400" y="-1100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_F1"/>
			<Parameter Name="InputEvent" Value="SK_RELEASED"/>
		</FB>
		<FB Name="Q_CtrlAudioSignal" Type="isobus::UT::Q::Q_CtrlAudioSignal" x="-2400" y="-1000">
			<Parameter Name="u8NumOfRepit" Value="1"/>
			<Parameter Name="u16Frequency" Value="440"/>
			<Parameter Name="u16OnTimeMs" Value="150"/>
			<Parameter Name="u16OffTimeMs" Value="0"/>
		</FB>
		<EventConnections>
			<Connection Source="SoftKey_UP_F1.IND" Destination="Q_CtrlAudioSignal.REQ"/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
