<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_010bA" Comment="Toggle Flip-Flop mit IE Button_A1 BT_STILL_HELD">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::Button_A1"/>
		<Import declaration="isobus::UT::io::Button::ButtonActivationCode::BT_STILL_HELD_START"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="-3900" y="-100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="Button_A1" Type="isobus::UT::io::Button::Button_IE" x="-7200" y="-200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="Button_A1"/>
			<Parameter Name="InputEvent" Value="BT_STILL_HELD_START"/>
		</FB>
		<FB Name="E_T_FF" Type="iec61499::events::E_T_FF" x="-5560" y="0">
		</FB>
		<Comment Comment="BT_STILL_HELD_START wird nicht wiederholt. &#10;Lange drücken ergibt 1 Event." x="-9000" y="800" width="1500" height="700"/>
		<EventConnections>
			<Connection Source="Button_A1.IND" Destination="E_T_FF.CLK" dx1="293.33"/>
			<Connection Source="E_T_FF.EO" Destination="DigitalOutput_Q1.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_T_FF.Q" Destination="DigitalOutput_Q1.OUT" dx1="580"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
