<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_020h" Comment="DigitalInput_I1 auf DigitalOutput_Q1; E_PULSE; Impulsformend">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="-5800" y="500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="E_PULSE" Type="iec61499::events::timers::E_PULSE" x="-7200" y="600">
			<Parameter Name="PT" Value="T#5S"/>
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="logiBUS::io::DI::logiBUS_IE" x="-9000" y="400">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<EventConnections>
			<Connection Source="E_PULSE.CNF" Destination="DigitalOutput_Q1.REQ"/>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="E_PULSE.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_PULSE.Q" Destination="DigitalOutput_Q1.OUT" dx1="73.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
