<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_039b" Comment="Spiegelabfolge V2 mit Schrittkette">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0&#10;   &#10;Spiegelabfolge V2 mit Schrittkette  &#10;geeignet für hydraulisches Ringsystem 3/2 Wege Ventile  (z.B. Claas) &#10;oder pneumatische 5/2 Wege Ventile  &#10;">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="-10400" y="-1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="logiBUS::io::DQ::logiBUS_QX" x="-10700" y="900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="SoftKey_F1" Type="isobus::UT::io::Softkey::Softkey_IX" x="-14700" y="-1100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_F1"/>
		</FB>
		<FB Name="E_TP_Q1" Type="iec61499::events::timers::E_TP" x="-12600" y="-800">
			<Parameter Name="PT" Value="T#8s"/>
		</FB>
		<FB Name="E_TP_Q2" Type="iec61499::events::timers::E_TP" x="-12500" y="1100">
			<Parameter Name="PT" Value="T#4s"/>
		</FB>
		<FB Name="E_TON" Type="iec61499::events::timers::E_TON" x="-13800" y="1200">
			<Parameter Name="PT" Value="T#2s"/>
		</FB>
		<EventConnections>
			<Connection Source="E_TP_Q1.CNF" Destination="DigitalOutput_Q1.REQ" dx1="866.67"/>
			<Connection Source="E_TP_Q2.CNF" Destination="DigitalOutput_Q2.REQ" dx1="666.67"/>
			<Connection Source="E_TP_Q1.CNF" Destination="E_TON.REQ" dx1="646.67" dx2="300" dy="913.33"/>
			<Connection Source="E_TON.CNF" Destination="E_TP_Q2.REQ" dx1="166.67"/>
			<Connection Source="SoftKey_F1.IND" Destination="E_TP_Q1.REQ" dx1="406.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_TP_Q2.Q" Destination="DigitalOutput_Q2.OUT"/>
			<Connection Source="E_TP_Q1.Q" Destination="DigitalOutput_Q1.OUT"/>
			<Connection Source="E_TP_Q1.Q" Destination="E_TON.IN" dx1="400" dx2="833.33" dy="293.33"/>
			<Connection Source="E_TON.Q" Destination="E_TP_Q2.IN"/>
			<Connection Source="SoftKey_F1.IN" Destination="E_TP_Q1.IN"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
