<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_000" Comment="ADD">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="ADD_2" Type="iec61131::arithmetic::ADD_2" x="-1100" y="0">
			<Parameter Name="IN1" Value="INT#5"/>
			<Parameter Name="IN2" Value="INT#3"/>
		</FB>
	</SubAppNetwork>
</SubAppType>
