<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_016" Comment="Background Colour umschalten">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="isobus::UT::io::Softkey::SoftKeyActivationCode::SK_RELEASED"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F1"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F2"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F7"/>
		<Import declaration="isobus::UT::Q::const::colours::COLOR_GREEN"/>
		<Import declaration="isobus::UT::Q::const::colours::COLOR_WHITE"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SoftKey_UP_F1" Type="isobus::UT::io::Softkey::Softkey_IE" x="-4500" y="-1100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_F1"/>
			<Parameter Name="InputEvent" Value="SK_RELEASED"/>
		</FB>
		<FB Name="SoftKey_UP_F2" Type="isobus::UT::io::Softkey::Softkey_IE" x="-4500" y="0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_F2"/>
			<Parameter Name="InputEvent" Value="SK_RELEASED"/>
		</FB>
		<FB Name="E_SR" Type="iec61499::events::E_SR" x="-2800" y="-900">
		</FB>
		<FB Name="F_SEL" Type="iec61131::selection::F_SEL" x="-900" y="-800">
			<Parameter Name="IN0" Value="COLOR_WHITE"/>
			<Parameter Name="IN1" Value="COLOR_GREEN"/>
		</FB>
		<FB Name="Q_BackgroundColour" Type="isobus::UT::Q::Q_BackgroundColour" x="900" y="-1000">
			<Parameter Name="u16ObjId" Value="SoftKey_F7"/>
		</FB>
		<EventConnections>
			<Connection Source="SoftKey_UP_F1.IND" Destination="E_SR.S"/>
			<Connection Source="SoftKey_UP_F2.IND" Destination="E_SR.R" dx1="473.33"/>
			<Connection Source="E_SR.EO" Destination="F_SEL.REQ" dx1="726.67"/>
			<Connection Source="F_SEL.CNF" Destination="Q_BackgroundColour.REQ" dx1="646.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_SR.Q" Destination="F_SEL.G"/>
			<Connection Source="F_SEL.OUT" Destination="Q_BackgroundColour.u8Colour"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
