<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_009" Comment="Ticker">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::OutputNumber_N1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="1800" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="E_CYCLE" Type="iec61499::events::E_CYCLE" x="-2500" y="-700">
			<Parameter Name="DT" Value="T#1s"/>
		</FB>
		<FB Name="E_SWITCH" Type="iec61499::events::E_SWITCH" x="-1600" y="-700">
		</FB>
		<FB Name="E_SR" Type="iec61499::events::E_SR" x="-700" y="-700">
		</FB>
		<FB Name="E_PERMIT" Type="iec61499::events::E_PERMIT" x="600" y="200">
		</FB>
		<FB Name="E_CTUD_UDINT" Type="iec61499::events::E_CTUD_UDINT" x="1800" y="200">
			<Parameter Name="PV" Value="0"/>
		</FB>
		<FB Name="Q_NumericValue" Type="isobus::UT::Q::Q_NumericValue" x="4200" y="100">
			<Parameter Name="u16ObjId" Value="OutputNumber_N1"/>
		</FB>
		<Comment Comment="In Watch wechseln, &#10;und bei START ein Event auslösen. " x="-4600" y="-800" width="1600" height="600"/>
		<EventConnections>
			<Connection Source="E_CYCLE.EO" Destination="E_SWITCH.EI"/>
			<Connection Source="E_SWITCH.EO0" Destination="E_SR.S"/>
			<Connection Source="E_SWITCH.EO1" Destination="E_SR.R"/>
			<Connection Source="E_SR.EO" Destination="DigitalOutput_Q1.REQ" dx1="813.33"/>
			<Connection Source="E_SR.EO" Destination="E_PERMIT.EI" dx1="480"/>
			<Connection Source="E_PERMIT.EO" Destination="E_CTUD_UDINT.CU"/>
			<Connection Source="E_CTUD_UDINT.CO" Destination="Q_NumericValue.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_SR.Q" Destination="E_SWITCH.G" dx1="80" dx2="80" dy="160"/>
			<Connection Source="E_SR.Q" Destination="DigitalOutput_Q1.OUT"/>
			<Connection Source="E_SR.Q" Destination="E_PERMIT.PERMIT" dx1="366.67"/>
			<Connection Source="E_CTUD_UDINT.CV" Destination="Q_NumericValue.u32NewValue" dx1="333.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
