<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_034a1_Q4" Comment="Numeric Value Input auf PWM Ausgang">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool_PWM::InputNumber_PWM_Value"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q4"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="F_DWORD_TO_UDINT" Type="iec61131::conversion::F_DWORD_TO_UDINT" x="1500" y="2300">
		</FB>
		<FB Name="PWMOutput_Q4" Type="logiBUS::io::DQ::logiBUS_QD_PWM" x="1800" y="1100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q4"/>
		</FB>
		<FB Name="PWM_Value" Type="isobus::UT::io::NumericValue::NumericValue_ID" x="-3800" y="1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="InputNumber_PWM_Value"/>
		</FB>
		<Comment Comment="ACHTUNG !! &#10;IND erscheint erst, &#10;wenn man die Numeric Value mit OK Bestätigt. &#10;nicht bei Button Druck. &#10;" x="-5800" y="700" width="1480" height="800"/>
		<EventConnections>
			<Connection Source="PWM_Value.IND" Destination="PWMOutput_Q4.REQ" dx1="2306.67"/>
			<Connection Source="PWM_Value.IND" Destination="F_DWORD_TO_UDINT.REQ" dx1="3013.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="PWM_Value.IN" Destination="F_DWORD_TO_UDINT.IN" dx1="2286.67"/>
			<Connection Source="PWM_Value.IN" Destination="PWMOutput_Q4.OUT" dx1="2306.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
