<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_038" Comment="Lauflicht 8 reine Zeitsteuerung">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::OutputNumber_N1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I4"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q3"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q4"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q5"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q6"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q7"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q8"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="-6300" y="-2366.67">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="E_TimeOut" Type="iec61499::events::E_TimeOut" x="-9333.33" y="2133.33">
		</FB>
		<FB Name="DigitalOutput_Q2" Type="logiBUS::io::DQ::logiBUS_QX" x="-6300" y="-1293.33">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</FB>
		<FB Name="DigitalOutput_Q3" Type="logiBUS::io::DQ::logiBUS_QX" x="-6300" y="-233.33">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q3"/>
		</FB>
		<FB Name="DigitalOutput_Q4" Type="logiBUS::io::DQ::logiBUS_QX" x="-6300" y="833.33">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q4"/>
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="logiBUS::io::DI::logiBUS_IE" x="-11373.33" y="-826.67">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="DigitalInput_CLK_I4" Type="logiBUS::io::DI::logiBUS_IE" x="-11373.33" y="186.67">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I4"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="DigitalOutput_Q5" Type="logiBUS::io::DQ::logiBUS_QX" x="-6300" y="1900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q5"/>
		</FB>
		<FB Name="DigitalOutput_Q6" Type="logiBUS::io::DQ::logiBUS_QX" x="-6300" y="2960">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q6"/>
		</FB>
		<FB Name="DigitalOutput_Q7" Type="logiBUS::io::DQ::logiBUS_QX" x="-6300" y="4033.33">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q7"/>
		</FB>
		<FB Name="DigitalOutput_Q8" Type="logiBUS::io::DQ::logiBUS_QX" x="-6300" y="5100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q8"/>
		</FB>
		<FB Name="Q_NumericValue" Type="isobus::UT::Q::Q_NumericValue" x="-2666.67" y="-2000">
			<Parameter Name="u16ObjId" Value="OutputNumber_N1"/>
		</FB>
		<FB Name="F_SINT_TO_UINT" Type="iec61131::conversion::F_SINT_TO_UINT" x="-4906.67" y="-1820">
		</FB>
		<FB Name="loop" Type="logiBUS::utils::sequence::timed::sequence_T_08_loop" x="-9613.33" y="-600">
			<Parameter Name="DT_S1_S2" Value="T#200ms"/>
			<Parameter Name="DT_S2_S3" Value="T#100ms"/>
			<Parameter Name="DT_S3_S4" Value="T#200ms"/>
			<Parameter Name="DT_S4_S5" Value="T#100ms"/>
			<Parameter Name="DT_S5_S6" Value="T#200ms"/>
			<Parameter Name="DT_S6_S7" Value="T#100ms"/>
			<Parameter Name="DT_S7_S8" Value="T#200ms"/>
			<Parameter Name="DT_S8_S1" Value="T#100ms"/>
		</FB>
		<EventConnections>
			<Connection Source="F_SINT_TO_UINT.CNF" Destination="Q_NumericValue.REQ" dx1="633.33"/>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="loop.START_S1" dx1="486.67"/>
			<Connection Source="DigitalInput_CLK_I4.IND" Destination="loop.RESET" dx1="420"/>
			<Connection Source="loop.CNF" Destination="F_SINT_TO_UINT.REQ" dx1="3153.33"/>
			<Connection Source="loop.EO_S1" Destination="DigitalOutput_Q1.REQ" dx1="820"/>
			<Connection Source="loop.EO_S2" Destination="DigitalOutput_Q2.REQ" dx1="986.67"/>
			<Connection Source="loop.EO_S3" Destination="DigitalOutput_Q3.REQ" dx1="886.67"/>
			<Connection Source="loop.EO_S4" Destination="DigitalOutput_Q4.REQ" dx1="886.67"/>
			<Connection Source="loop.EO_S5" Destination="DigitalOutput_Q5.REQ" dx1="853.33"/>
			<Connection Source="loop.EO_S6" Destination="DigitalOutput_Q6.REQ" dx1="753.33"/>
			<Connection Source="loop.EO_S7" Destination="DigitalOutput_Q7.REQ" dx1="686.67"/>
			<Connection Source="loop.EO_S8" Destination="DigitalOutput_Q8.REQ" dx1="620"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="F_SINT_TO_UINT.OUT" Destination="Q_NumericValue.u32NewValue" dx1="286.67"/>
			<Connection Source="loop.STATE_NR" Destination="F_SINT_TO_UINT.IN" dx1="953.33"/>
			<Connection Source="loop.DO_S1" Destination="DigitalOutput_Q1.OUT" dx1="920"/>
			<Connection Source="loop.DO_S2" Destination="DigitalOutput_Q2.OUT" dx1="1020"/>
			<Connection Source="loop.DO_S3" Destination="DigitalOutput_Q3.OUT" dx1="1053.33"/>
			<Connection Source="loop.DO_S4" Destination="DigitalOutput_Q4.OUT" dx1="886.67"/>
			<Connection Source="loop.DO_S5" Destination="DigitalOutput_Q5.OUT" dx1="820"/>
			<Connection Source="loop.DO_S6" Destination="DigitalOutput_Q6.OUT" dx1="720"/>
			<Connection Source="loop.DO_S7" Destination="DigitalOutput_Q7.OUT" dx1="653.33"/>
			<Connection Source="loop.DO_S8" Destination="DigitalOutput_Q8.OUT" dx1="586.67"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="loop.timeOut" Destination="E_TimeOut.TimeOutSocket" dx1="80" dx2="80" dy="226.67"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
