<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_071b" Comment="WBSD auf UT ausgeben, Q1 Schalten wenn Speed &gt;0">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool_TECU::NumberVariable_Wheel_based_machine_distance"/>
		<Import declaration="Uebungen::const::UT::DefaultPool_TECU::NumberVariable_Wheel_based_machine_speed"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="I_WBSD" Type="isobus::tecu::I_WBSD" x="-5200" y="500">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="Q_NumberVariable_Wheel_based_machine_speed" Type="isobus::UT::Q::Q_NumericValue" x="1100" y="500">
			<Parameter Name="u16ObjId" Value="NumberVariable_Wheel_based_machine_speed"/>
		</FB>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="1900" y="2300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="RangeBasedPulse" Type="eclipse4diac::signalprocessing::distance::RangeBasedPulse" x="-1600" y="2400">
			<Parameter Name="DIST_HIGH" Value="5000"/>
			<Parameter Name="DIST_LOW" Value="5000"/>
		</FB>
		<FB Name="E_D_FF" Type="iec61499::events::E_D_FF" x="300" y="2400">
		</FB>
		<FB Name="Q_NumberVariable_Wheel_based_machine_distance" Type="isobus::UT::Q::Q_NumericValue" x="1000" y="1300">
			<Parameter Name="u16ObjId" Value="NumberVariable_Wheel_based_machine_distance"/>
		</FB>
		<EventConnections>
			<Connection Source="I_WBSD.IND" Destination="Q_NumberVariable_Wheel_based_machine_speed.REQ"/>
			<Connection Source="E_D_FF.EO" Destination="DigitalOutput_Q1.REQ"/>
			<Connection Source="I_WBSD.IND" Destination="Q_NumberVariable_Wheel_based_machine_distance.REQ" dx1="1346.67"/>
			<Connection Source="I_WBSD.IND" Destination="RangeBasedPulse.REQ" dx1="1240"/>
			<Connection Source="RangeBasedPulse.CNF" Destination="E_D_FF.CLK" dx1="260"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="I_WBSD.WHEELBASEDMACHINESPEED" Destination="Q_NumberVariable_Wheel_based_machine_speed.u32NewValue" dx1="806.67"/>
			<Connection Source="E_D_FF.Q" Destination="DigitalOutput_Q1.OUT" dx1="280"/>
			<Connection Source="I_WBSD.WHEELBASEDMACHINEDISTANCE" Destination="Q_NumberVariable_Wheel_based_machine_distance.u32NewValue" dx1="1920"/>
			<Connection Source="I_WBSD.WHEELBASEDMACHINEDISTANCE" Destination="RangeBasedPulse.DIST_IN" dx1="1080"/>
			<Connection Source="RangeBasedPulse.Q" Destination="E_D_FF.D" dx1="260"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
