<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_039_sub_NumbAnzeig" Comment="Spiegelabfolge V2 mit Schrittkette SUB Num">
	<Identification Standard="61499-2" Description="Copyright (c) 2024 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2024-03-03">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::OutputNumber_N1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="CNF" Type="Event">
				<Attribute Name="YPOSITION" Type="INT" Value="20"/>
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="STATE_NR" Type="SINT">
				<Attribute Name="YPOSITION" Type="INT" Value="75"/>
			</VarDeclaration>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="F_SINT_TO_UINT" Type="iec61131::conversion::F_SINT_TO_UINT" x="-800" y="0">
		</FB>
		<FB Name="Q_NumericValue" Type="isobus::UT::Q::Q_NumericValue" x="1340" y="-873.33">
			<Parameter Name="u16ObjId" Value="OutputNumber_N1"/>
		</FB>
		<EventConnections>
			<Connection Source="F_SINT_TO_UINT.CNF" Destination="Q_NumericValue.REQ" dx1="213.33"/>
			<Connection Source="CNF" Destination="F_SINT_TO_UINT.REQ" dx1="273.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="F_SINT_TO_UINT.OUT" Destination="Q_NumericValue.u32NewValue" dx1="246.67"/>
			<Connection Source="STATE_NR" Destination="F_SINT_TO_UINT.IN" dx1="240"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
