<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_002b2" Comment="DigitalInput_I1/_I2/_I3 auf DigitalOutput_Q1; mit MOVE">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I3"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="1900" y="1400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IX" x="-4500" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="DigitalInput_I2" Type="logiBUS::io::DI::logiBUS_IX" x="-4500" y="300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
		</FB>
		<FB Name="AND_2" Type="iec61131::bitwiseOperators::AND_2" x="-2100" y="500">
		</FB>
		<FB Name="DigitalInput_I3" Type="logiBUS::io::DI::logiBUS_IX" x="-4500" y="1300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I3"/>
		</FB>
		<FB Name="OR_2" Type="iec61131::bitwiseOperators::OR_2" x="100" y="1500">
		</FB>
		<FB Name="F_MOVE" Type="iec61131::selection::F_MOVE" x="-1300" y="500">
			<Attribute Name="DataType" Value="BOOL"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I1.IND" Destination="AND_2.REQ" dx1="1626.67"/>
			<Connection Source="DigitalInput_I2.IND" Destination="AND_2.REQ" dx1="826.67"/>
			<Connection Source="OR_2.CNF" Destination="DigitalOutput_Q1.REQ" dx1="493.33"/>
			<Connection Source="DigitalInput_I3.IND" Destination="OR_2.REQ" dx1="1926.67"/>
			<Connection Source="F_MOVE.CNF" Destination="OR_2.REQ" dx1="586.67"/>
			<Connection Source="AND_2.CNF" Destination="F_MOVE.REQ" dx1="140"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="AND_2.IN1" dx1="900"/>
			<Connection Source="DigitalInput_I2.IN" Destination="AND_2.IN2" dx1="853.33"/>
			<Connection Source="DigitalInput_I3.IN" Destination="OR_2.IN2" dx1="1973.33"/>
			<Connection Source="OR_2.OUT" Destination="DigitalOutput_Q1.OUT" dx1="373.33"/>
			<Connection Source="F_MOVE.OUT" Destination="OR_2.IN1" dx1="393.33"/>
			<Connection Source="AND_2.OUT" Destination="F_MOVE.IN" dx1="140"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
