<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_015" Comment="Object Pointer umschalten">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="isobus::UT::io::Softkey::SoftKeyActivationCode::SK_RELEASED"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::Button_A1"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::ObjectPointer_P1"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F1"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F2"/>
		<Import declaration="isobus::UT::Q::const::IDs::ID_NULL"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SoftKey_UP_F1" Type="isobus::UT::io::Softkey::Softkey_IE" x="-4500" y="-1100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_F1"/>
			<Parameter Name="InputEvent" Value="SK_RELEASED"/>
		</FB>
		<FB Name="SoftKey_UP_F2" Type="isobus::UT::io::Softkey::Softkey_IE" x="-4500" y="-100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_F2"/>
			<Parameter Name="InputEvent" Value="SK_RELEASED"/>
		</FB>
		<FB Name="E_SR" Type="iec61499::events::E_SR" x="-2800" y="-900">
		</FB>
		<FB Name="F_UINT_TO_UDINT" Type="iec61131::conversion::F_UINT_TO_UDINT" x="-4500" y="1000">
			<Parameter Name="IN" Value="Button_A1"/>
		</FB>
		<FB Name="F_SEL" Type="iec61131::selection::F_SEL" x="-1100" y="-900">
			<Parameter Name="IN0" Value="ID_NULL"/>
		</FB>
		<FB Name="Q_NumericValue" Type="isobus::UT::Q::Q_NumericValue" x="1300" y="-1000">
			<Parameter Name="u16ObjId" Value="ObjectPointer_P1"/>
		</FB>
		<EventConnections>
			<Connection Source="SoftKey_UP_F1.IND" Destination="E_SR.S"/>
			<Connection Source="SoftKey_UP_F2.IND" Destination="E_SR.R" dx1="473.33"/>
			<Connection Source="F_SEL.CNF" Destination="Q_NumericValue.REQ"/>
			<Connection Source="E_SR.EO" Destination="F_SEL.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="F_SEL.OUT" Destination="Q_NumericValue.u32NewValue" dx1="313.33"/>
			<Connection Source="F_UINT_TO_UDINT.OUT" Destination="F_SEL.IN1" dx1="1706.67"/>
			<Connection Source="E_SR.Q" Destination="F_SEL.G" dx1="220"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
