<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_079" Comment="alle TECU FBs">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="I_GBSD" Type="isobus::tecu::I_GBSD" x="-5213.33" y="453.33">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="I_VDS" Type="isobus::tecu::I_VDS" x="-5200" y="3800">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="I_WBSD" Type="isobus::tecu::I_WBSD" x="-5200" y="1900">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="I_MSS" Type="isobus::tecu::I_MSS" x="-5200" y="5400">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="I_FHS" Type="isobus::tecu::I_FHS" x="-2000" y="-200">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="I_FPTO" Type="isobus::tecu::I_FPTO" x="-2000" y="1600">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="I_RHS" Type="isobus::tecu::I_RHS" x="-2000" y="3800">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="I_RPTO" Type="isobus::tecu::I_RPTO" x="-2000" y="5700">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="COGSOGRapidUpdate" Type="isobus::tecu::I_COGSOGRapidUpdate" x="500" y="5800">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
	</SubAppNetwork>
</SubAppType>
