<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_071" Comment="WBSD auf UT ausgeben, Q1 Schalten wenn Speed &gt;0">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool_TECU::NumberVariable_Wheel_based_machine_speed"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="I_WBSD" Type="isobus::tecu::I_WBSD" x="-6000" y="500">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="Q_NumericValue_WBSD" Type="isobus::UT::Q::Q_NumericValue" x="-700" y="500">
			<Parameter Name="u16ObjId" Value="NumberVariable_Wheel_based_machine_speed"/>
		</FB>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="200" y="1900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="F_GT" Type="iec61131::comparison::F_GT" x="-1500" y="2000">
			<Parameter Name="IN2" Value="UINT#0"/>
		</FB>
		<EventConnections>
			<Connection Source="I_WBSD.IND" Destination="Q_NumericValue_WBSD.REQ"/>
			<Connection Source="I_WBSD.IND" Destination="F_GT.REQ" dx1="1006.67"/>
			<Connection Source="F_GT.CNF" Destination="DigitalOutput_Q1.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="I_WBSD.WHEELBASEDMACHINESPEED" Destination="Q_NumericValue_WBSD.u32NewValue" dx1="806.67"/>
			<Connection Source="I_WBSD.WHEELBASEDMACHINESPEED" Destination="F_GT.IN1" dx1="806.67"/>
			<Connection Source="F_GT.OUT" Destination="DigitalOutput_Q1.OUT" dx1="513.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
