<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_080b" Comment="Beispiel für E_CTU mit E_SPLIT für Event-Verdoppelung">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0&#10;   &#10;Beispiel für E_CTU&#10;Aufwärts zählen&#10;UAO Curriculum Module 3 - The IEC 61499 Standard, &#10;Seite 92">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="-4900" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="logiBUS::io::DI::logiBUS_IE" x="-9500" y="-1100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="E_CTU" Type="iec61499::events::E_CTU" x="-6300" y="-800">
			<Parameter Name="PV" Value="UINT#5"/>
		</FB>
		<FB Name="DigitalInput_CLK_I2" Type="logiBUS::io::DI::logiBUS_IE" x="-8100" y="-100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="E_SPLIT" Type="iec61499::events::E_SPLIT" x="-8100" y="-900">
		</FB>
		<Comment Comment="E_SPLIT macht 2 Events, die dann wieder gemerged werden.&#10;--&gt; Event wird verdoppelt" x="-8400" y="-1400" width="1500" height="400"/>
		<EventConnections>
			<Connection Source="E_CTU.CUO" Destination="DigitalOutput_Q1.REQ" dx1="453.33"/>
			<Connection Source="E_CTU.RO" Destination="DigitalOutput_Q1.REQ"/>
			<Connection Source="DigitalInput_CLK_I2.IND" Destination="E_CTU.R" dx1="273.33"/>
			<Connection Source="E_SPLIT.EO2" Destination="E_CTU.CU"/>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="E_SPLIT.EI"/>
			<Connection Source="E_SPLIT.EO1" Destination="E_CTU.CU" dx1="593.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_CTU.Q" Destination="DigitalOutput_Q1.OUT" dx1="453.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
