<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_020f2" Comment="DigitalInput_I1 auf DigitalOutput_Q1; FB_TP; Impulsformend">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="E_SWITCH_I1" Type="iec61499::events::E_SWITCH" x="1100" y="-300">
		</FB>
		<FB Name="E_SWITCH_Q1" Type="iec61499::events::E_SWITCH" x="4800" y="600">
		</FB>
		<Comment Comment="E_CYCLE bestimmt, &#10;wie oft FB_TP den ET aktualisert" x="2000" y="-700" width="1000" height="400"/>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IX" x="-100" y="-500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="FB_TP" Type="iec61131::timers::FB_TP" x="3700" y="100">
			<Parameter Name="PT" Value="T#5s"/>
		</FB>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="6400" y="-200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="E_CYCLE" Type="iec61499::events::E_CYCLE" x="2600" y="-200">
			<Parameter Name="DT" Value="T#500ms"/>
		</FB>
		<EventConnections>
			<Connection Source="E_CYCLE.EO" Destination="FB_TP.REQ" dx1="413.33"/>
			<Connection Source="DigitalInput_I1.IND" Destination="E_SWITCH_I1.EI"/>
			<Connection Source="FB_TP.CNF" Destination="E_SWITCH_Q1.EI" dx1="266.67"/>
			<Connection Source="E_SWITCH_I1.EO1" Destination="E_CYCLE.START"/>
			<Connection Source="E_SWITCH_Q1.EO0" Destination="E_CYCLE.STOP" dx1="446.67" dx2="446.67" dy="673.33"/>
			<Connection Source="FB_TP.CNF" Destination="DigitalOutput_Q1.REQ" dx1="280"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="E_SWITCH_I1.G" dx1="253.33"/>
			<Connection Source="DigitalInput_I1.IN" Destination="FB_TP.IN" dx1="80"/>
			<Connection Source="FB_TP.Q" Destination="DigitalOutput_Q1.OUT"/>
			<Connection Source="FB_TP.Q" Destination="E_SWITCH_Q1.G" dx1="193.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
