<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_042" Comment="Scaling Function Block Testing">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_CLK_I1" Type="logiBUS::io::DI::logiBUS_IE" x="-5000" y="-400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="SCALE" Type="eclipse4diac::signalprocessing::SCALE" x="-2500" y="-200">
			<Parameter Name="IN" Value="10.0"/>
			<Parameter Name="MAX_IN" Value="20.0"/>
			<Parameter Name="MIN_IN" Value="4.0"/>
			<Parameter Name="MAX_OUT" Value="100.0"/>
			<Parameter Name="MIN_OUT" Value="0.0"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="SCALE.REQ" dx1="806.67"/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
