<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_083" Comment="Beispiel für E_CTUD_UDINT">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0&#10;   &#10;Beispiel für E_CTD&#10;Aufwärts zählen&#10;UAO Curriculum Module 3 - The IEC 61499 Standard, &#10;Seite 94">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::OutputNumber_N1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I3"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I4"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="-6500" y="-100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="logiBUS::io::DI::logiBUS_IE" x="-10800" y="-1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="E_CTUD_UDINT" Type="iec61499::events::E_CTUD_UDINT" x="-9000" y="0">
			<Parameter Name="PV" Value="UINT#5"/>
		</FB>
		<FB Name="DigitalInput_CLK_I2" Type="logiBUS::io::DI::logiBUS_IE" x="-10800" y="0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="DigitalInput_CLK_I3" Type="logiBUS::io::DI::logiBUS_IE" x="-10800" y="1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I3"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="DigitalInput_CLK_I4" Type="logiBUS::io::DI::logiBUS_IE" x="-10800" y="2000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I4"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="logiBUS::io::DQ::logiBUS_QX" x="-6500" y="800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</FB>
		<FB Name="Q_NumericValue" Type="isobus::UT::Q::Q_NumericValue" x="-7400" y="2100">
			<Parameter Name="u16ObjId" Value="OutputNumber_N1"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="E_CTUD_UDINT.CU" dx1="413.33"/>
			<Connection Source="E_CTUD_UDINT.CO" Destination="DigitalOutput_Q1.REQ"/>
			<Connection Source="E_CTUD_UDINT.LDO" Destination="DigitalOutput_Q1.REQ" dx1="393.33"/>
			<Connection Source="DigitalInput_CLK_I2.IND" Destination="E_CTUD_UDINT.CD" dx1="460"/>
			<Connection Source="E_CTUD_UDINT.RO" Destination="DigitalOutput_Q1.REQ" dx1="393.33"/>
			<Connection Source="DigitalInput_CLK_I3.IND" Destination="E_CTUD_UDINT.R" dx1="260"/>
			<Connection Source="DigitalInput_CLK_I4.IND" Destination="E_CTUD_UDINT.LD" dx1="400"/>
			<Connection Source="E_CTUD_UDINT.LDO" Destination="DigitalOutput_Q2.REQ" dx1="393.33"/>
			<Connection Source="E_CTUD_UDINT.CO" Destination="DigitalOutput_Q2.REQ" dx1="393.33"/>
			<Connection Source="E_CTUD_UDINT.RO" Destination="DigitalOutput_Q2.REQ" dx1="393.33"/>
			<Connection Source="E_CTUD_UDINT.CO" Destination="Q_NumericValue.REQ" dx1="380"/>
			<Connection Source="E_CTUD_UDINT.RO" Destination="Q_NumericValue.REQ" dx1="380"/>
			<Connection Source="E_CTUD_UDINT.LDO" Destination="Q_NumericValue.REQ" dx1="380"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_CTUD_UDINT.QU" Destination="DigitalOutput_Q1.OUT" dx1="280"/>
			<Connection Source="E_CTUD_UDINT.QD" Destination="DigitalOutput_Q2.OUT" dx1="313.33"/>
			<Connection Source="E_CTUD_UDINT.CV" Destination="Q_NumericValue.u32NewValue" dx1="126.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
