<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_007a1" Comment="Blinker mit E_CYCLE und E_T_FF">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="-300" y="-700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="E_CYCLE" Type="iec61499::events::E_CYCLE" x="-2900" y="-600">
			<Parameter Name="DT" Value="T#1s"/>
		</FB>
		<FB Name="E_T_FF" Type="iec61499::events::E_T_FF" x="-1700" y="-600">
		</FB>
		<FB Name="START" Type="logiBUS::io::DI::logiBUS_IE" x="-4700" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="STOP" Type="logiBUS::io::DI::logiBUS_IE" x="-4700" y="200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<Comment Comment="Nachteil: &#10;dieser Blinker bleibt zufällig auf &#10;AN oder AUS stehen." x="-3100" y="500" width="1800" height="700"/>
		<EventConnections>
			<Connection Source="E_CYCLE.EO" Destination="E_T_FF.CLK"/>
			<Connection Source="E_T_FF.EO" Destination="DigitalOutput_Q1.REQ"/>
			<Connection Source="START.IND" Destination="E_CYCLE.START" dx1="526.67"/>
			<Connection Source="STOP.IND" Destination="E_CYCLE.STOP" dx1="526.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_T_FF.Q" Destination="DigitalOutput_Q1.OUT" dx1="333.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
