<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_060_sub_Outputs" Comment="für TC-SC also Task Controller Section Control">
	<Identification Standard="61499-2" Description="Copyright (c) 2024 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2024-02-29">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q3"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q4"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q5"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q6"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q7"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q8"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="CNF" Type="Event">
				<Attribute Name="YPOSITION" Type="INT" Value="29"/>
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="Q_00" Type="BOOL">
				<Attribute Name="YPOSITION" Type="INT" Value="20"/>
			</VarDeclaration>
			<VarDeclaration Name="Q_01" Type="BOOL">
				<Attribute Name="YPOSITION" Type="INT" Value="161"/>
			</VarDeclaration>
			<VarDeclaration Name="Q_02" Type="BOOL">
				<Attribute Name="YPOSITION" Type="INT" Value="161"/>
			</VarDeclaration>
			<VarDeclaration Name="Q_03" Type="BOOL">
				<Attribute Name="YPOSITION" Type="INT" Value="161"/>
			</VarDeclaration>
			<VarDeclaration Name="Q_04" Type="BOOL">
				<Attribute Name="YPOSITION" Type="INT" Value="161"/>
			</VarDeclaration>
			<VarDeclaration Name="Q_05" Type="BOOL">
				<Attribute Name="YPOSITION" Type="INT" Value="161"/>
			</VarDeclaration>
			<VarDeclaration Name="Q_06" Type="BOOL">
				<Attribute Name="YPOSITION" Type="INT" Value="161"/>
			</VarDeclaration>
			<VarDeclaration Name="Q_07" Type="BOOL">
				<Attribute Name="YPOSITION" Type="INT" Value="161"/>
			</VarDeclaration>
			<VarDeclaration Name="Q_08" Type="BOOL">
				<Attribute Name="YPOSITION" Type="INT" Value="161"/>
			</VarDeclaration>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q4" Type="logiBUS::io::DQ::logiBUS_QX" x="-3373.33" y="1953.33">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q4"/>
		</FB>
		<FB Name="DigitalOutput_Q7" Type="logiBUS::io::DQ::logiBUS_QX" x="-3373.33" y="4893.33">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q7"/>
		</FB>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="-3373.33" y="-986.67">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalOutput_Q5" Type="logiBUS::io::DQ::logiBUS_QX" x="-3373.33" y="2933.33">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q5"/>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="logiBUS::io::DQ::logiBUS_QX" x="-3373.33" y="-6.67">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</FB>
		<FB Name="DigitalOutput_Q6" Type="logiBUS::io::DQ::logiBUS_QX" x="-3373.33" y="3913.33">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q6"/>
		</FB>
		<FB Name="DigitalOutput_Q8" Type="logiBUS::io::DQ::logiBUS_QX" x="-3373.33" y="5873.33">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q8"/>
		</FB>
		<FB Name="DigitalOutput_Q3" Type="logiBUS::io::DQ::logiBUS_QX" x="-3373.33" y="973.33">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q3"/>
		</FB>
		<EventConnections>
			<Connection Source="CNF" Destination="DigitalOutput_Q4.REQ" dx1="720">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CNF" Destination="DigitalOutput_Q7.REQ" dx1="720">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CNF" Destination="DigitalOutput_Q1.REQ" dx1="660">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CNF" Destination="DigitalOutput_Q5.REQ" dx1="720">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CNF" Destination="DigitalOutput_Q2.REQ" dx1="873.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CNF" Destination="DigitalOutput_Q6.REQ" dx1="720">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CNF" Destination="DigitalOutput_Q8.REQ" dx1="720">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="CNF" Destination="DigitalOutput_Q3.REQ" dx1="720">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</EventConnections>
		<DataConnections>
			<Connection Source="Q_06" Destination="DigitalOutput_Q7.OUT" dx1="233.33"/>
			<Connection Source="Q_00" Destination="DigitalOutput_Q1.OUT" dx1="186.67"/>
			<Connection Source="Q_04" Destination="DigitalOutput_Q5.OUT" dx1="266.67"/>
			<Connection Source="Q_01" Destination="DigitalOutput_Q2.OUT" dx1="186.67"/>
			<Connection Source="Q_05" Destination="DigitalOutput_Q6.OUT" dx1="246.67"/>
			<Connection Source="Q_02" Destination="DigitalOutput_Q3.OUT" dx1="300"/>
			<Connection Source="Q_03" Destination="DigitalOutput_Q4.OUT" dx1="280"/>
			<Connection Source="Q_07" Destination="DigitalOutput_Q8.OUT" dx1="213.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
