<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_087a2" Comment="Beispiel für E_DEMUX_4">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0&#10;   &#10;Beispiel für E_CTD&#10;Aufwärts zählen&#10;UAO Curriculum Module 3 - The IEC 61499 Standard, &#10;Seite 93">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I3"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I4"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q3"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q4"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="5900" y="0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IX" x="1100" y="-100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="logiBUS::io::DQ::logiBUS_QX" x="5900" y="900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</FB>
		<FB Name="DigitalInput_I2" Type="logiBUS::io::DI::logiBUS_IX" x="1100" y="800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
		</FB>
		<FB Name="DigitalOutput_Q3" Type="logiBUS::io::DQ::logiBUS_QX" x="5900" y="1900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q3"/>
		</FB>
		<FB Name="DigitalInput_I3" Type="logiBUS::io::DI::logiBUS_IX" x="1100" y="1800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I3"/>
		</FB>
		<FB Name="DigitalOutput_Q4" Type="logiBUS::io::DQ::logiBUS_QX" x="5900" y="2900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q4"/>
		</FB>
		<FB Name="DigitalInput_I4" Type="logiBUS::io::DI::logiBUS_IX" x="1100" y="2800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I4"/>
		</FB>
		<FB Name="E_DEMUX_4" Type="iec61499::events::E_DEMUX_4" x="3900" y="-700">
		</FB>
		<FB Name="E_MUX_4" Type="iec61499::events::E_MUX_4" x="3100" y="-700">
		</FB>
		<EventConnections>
			<Connection Source="E_MUX_4.EO" Destination="E_DEMUX_4.EI"/>
			<Connection Source="DigitalInput_I1.IND" Destination="E_MUX_4.EI1" dx1="653.33"/>
			<Connection Source="DigitalInput_I2.IND" Destination="E_MUX_4.EI2" dx1="893.33"/>
			<Connection Source="DigitalInput_I3.IND" Destination="E_MUX_4.EI3" dx1="1040"/>
			<Connection Source="DigitalInput_I4.IND" Destination="E_MUX_4.EI4" dx1="1173.33"/>
			<Connection Source="E_DEMUX_4.EO4" Destination="DigitalOutput_Q4.REQ" dx1="120"/>
			<Connection Source="E_DEMUX_4.EO3" Destination="DigitalOutput_Q3.REQ" dx1="300"/>
			<Connection Source="E_DEMUX_4.EO2" Destination="DigitalOutput_Q2.REQ" dx1="480"/>
			<Connection Source="E_DEMUX_4.EO1" Destination="DigitalOutput_Q1.REQ" dx1="660"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_MUX_4.K" Destination="E_DEMUX_4.K"/>
			<Connection Source="DigitalInput_I1.IN" Destination="DigitalOutput_Q1.OUT"/>
			<Connection Source="DigitalInput_I2.IN" Destination="DigitalOutput_Q2.OUT"/>
			<Connection Source="DigitalInput_I3.IN" Destination="DigitalOutput_Q3.OUT"/>
			<Connection Source="DigitalInput_I4.IN" Destination="DigitalOutput_Q4.OUT"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
