<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_028" Comment="Analog-Eingang">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="-100" y="100">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IX" x="-4200" y="-200">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="AnalogInput_I4" Type="logiBUS::io::AI::logiBUS_AI_ID" x="-700" y="1100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="logiBUS::io::AI::logiBUS_AI::AnalogInput_I4"/>
			<Parameter Name="AnalogInput_hysteresis" Value="50"/>
		</FB>
		<FB Name="AnalogInput_I7" Type="logiBUS::io::AI::logiBUS_AI_ID" x="-700" y="2400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="logiBUS::io::AI::logiBUS_AI::AnalogInput_I7"/>
			<Parameter Name="AnalogInput_hysteresis" Value="50"/>
		</FB>
		<FB Name="F_DWORD_TO_UDINT_I7" Type="iec61131::conversion::F_DWORD_TO_UDINT" x="2200" y="2800">
		</FB>
		<FB Name="F_DWORD_TO_UDINT_I4" Type="iec61131::conversion::F_DWORD_TO_UDINT" x="2100" y="1500">
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I1.IND" Destination="DigitalOutput_Q1.REQ" dx1="1673.33"/>
			<Connection Source="AnalogInput_I7.IND" Destination="F_DWORD_TO_UDINT_I7.REQ" dx1="960"/>
			<Connection Source="AnalogInput_I4.IND" Destination="F_DWORD_TO_UDINT_I4.REQ" dx1="960"/>
			<Connection Source="DigitalInput_I1.IND" Destination="AnalogInput_I4.REQ" dx1="1213.33"/>
			<Connection Source="DigitalInput_I1.IND" Destination="AnalogInput_I7.REQ" dx1="1213.33"/>
			<Connection Source="AnalogInput_I7.CNF" Destination="F_DWORD_TO_UDINT_I7.REQ" dx1="960"/>
			<Connection Source="AnalogInput_I4.CNF" Destination="F_DWORD_TO_UDINT_I4.REQ" dx1="960"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="DigitalOutput_Q1.OUT"/>
			<Connection Source="AnalogInput_I7.IN" Destination="F_DWORD_TO_UDINT_I7.IN"/>
			<Connection Source="AnalogInput_I4.IN" Destination="F_DWORD_TO_UDINT_I4.IN"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
