<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_002b3" Comment="DigitalInput_I1/_I2/_I3 auf DigitalOutput_Q1; ohne MOVE">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I3"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="1900" y="1400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IX" x="-4500" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="DigitalInput_I2" Type="logiBUS::io::DI::logiBUS_IX" x="-4500" y="380">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
		</FB>
		<FB Name="AND_2_BOOL" Type="iec61131::bitwiseOperators::AND_2_BOOL" x="-2100" y="700">
		</FB>
		<FB Name="DigitalInput_I3" Type="logiBUS::io::DI::logiBUS_IX" x="-4500" y="1400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I3"/>
		</FB>
		<FB Name="OR_2_BOOL" Type="iec61131::bitwiseOperators::OR_2_BOOL" x="100" y="1720">
		</FB>
		<Comment Comment="kein F_MOVE mehr nötig. " x="-300" y="800" width="1300" height="200"/>
		<EventConnections>
			<Connection Source="DigitalInput_I1.IND" Destination="AND_2_BOOL.REQ" dx1="1566.67"/>
			<Connection Source="DigitalInput_I2.IND" Destination="AND_2_BOOL.REQ" dx1="820"/>
			<Connection Source="OR_2_BOOL.CNF" Destination="DigitalOutput_Q1.REQ" dx1="546.67"/>
			<Connection Source="DigitalInput_I3.IND" Destination="OR_2_BOOL.REQ" dx1="1920"/>
			<Connection Source="AND_2_BOOL.CNF" Destination="OR_2_BOOL.REQ" dx1="926.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="AND_2_BOOL.IN1" dx1="1160"/>
			<Connection Source="DigitalInput_I2.IN" Destination="AND_2_BOOL.IN2"/>
			<Connection Source="DigitalInput_I3.IN" Destination="OR_2_BOOL.IN2"/>
			<Connection Source="OR_2_BOOL.OUT" Destination="DigitalOutput_Q1.OUT"/>
			<Connection Source="AND_2_BOOL.OUT" Destination="OR_2_BOOL.IN1" dx1="680"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
