<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_007a3" Comment="Blinker mit E_CYCLE, E_SWITCH und E_SR">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="-400" y="-600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="E_CYCLE" Type="iec61499::events::E_CYCLE" x="-5000" y="-500">
			<Parameter Name="DT" Value="T#1s"/>
		</FB>
		<FB Name="START" Type="logiBUS::io::DI::logiBUS_IE" x="-6900" y="-1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="STOP" Type="logiBUS::io::DI::logiBUS_IE" x="-6900" y="0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<Comment Comment="Vorteil:&#10;dieser Blinker bleibt immer auf AUS stehen" x="-4900" y="500" width="1800" height="700"/>
		<FB Name="E_SR" Type="iec61499::events::E_SR" x="-1800" y="-500">
		</FB>
		<FB Name="E_SWITCH" Type="iec61499::events::E_SWITCH" x="-3400" y="-500">
		</FB>
		<EventConnections>
			<Connection Source="START.IND" Destination="E_CYCLE.START" dx1="526.67"/>
			<Connection Source="STOP.IND" Destination="E_CYCLE.STOP" dx1="526.67"/>
			<Connection Source="E_SWITCH.EO0" Destination="E_SR.S"/>
			<Connection Source="E_SWITCH.EO1" Destination="E_SR.R"/>
			<Connection Source="E_SR.EO" Destination="DigitalOutput_Q1.REQ"/>
			<Connection Source="E_CYCLE.EO" Destination="E_SWITCH.EI"/>
			<Connection Source="STOP.IND" Destination="E_SR.R" dx1="4026.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_SR.Q" Destination="E_SWITCH.G" dx1="80" dx2="80" dy="160"/>
			<Connection Source="E_SR.Q" Destination="DigitalOutput_Q1.OUT" dx1="466.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
