<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_034" Comment="Analog-Eingang auf PWM Ausgang">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::AI::logiBUS_AI"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q4"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="AnalogInput_I7" Type="logiBUS::io::AI::logiBUS_AI_ID" x="-3700" y="1500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="logiBUS_AI::AnalogInput_I7"/>
			<Parameter Name="AnalogInput_hysteresis" Value="50"/>
		</FB>
		<FB Name="F_DWORD_TO_UDINT_I7" Type="iec61131::conversion::F_DWORD_TO_UDINT" x="1100" y="2600">
		</FB>
		<FB Name="PWMOutput_Q4" Type="logiBUS::io::DQ::logiBUS_QD_PWM" x="1900" y="1600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q4"/>
		</FB>
		<FB Name="F_SHL" Type="iec61131::bitwiseOperators::F_SHL" x="-1246.67" y="1700">
			<Parameter Name="N" Value="UINT#1"/>
		</FB>
		<EventConnections>
			<Connection Source="AnalogInput_I7.IND" Destination="F_SHL.REQ"/>
			<Connection Source="F_SHL.CNF" Destination="F_DWORD_TO_UDINT_I7.REQ" dx1="1040"/>
			<Connection Source="F_SHL.CNF" Destination="PWMOutput_Q4.REQ" dx1="1313.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="AnalogInput_I7.IN" Destination="F_SHL.IN" dx1="206.67"/>
			<Connection Source="F_SHL.OUT" Destination="PWMOutput_Q4.OUT" dx1="1313.33"/>
			<Connection Source="F_SHL.OUT" Destination="F_DWORD_TO_UDINT_I7.IN" dx1="853.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
