<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_026_sub" Comment="Spiegelabfolge (6)">
	<Identification Standard="61499-2" Description="Copyright (c) 2024 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2024-02-05">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DQ::logiBUS_DO"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO_S"/>
	</CompilerInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="SET" Type="Event">
				<Attribute Name="YPOSITION" Type="INT" Value="20"/>
			</SubAppEvent>
			<SubAppEvent Name="RESET" Type="Event">
				<Attribute Name="YPOSITION" Type="INT" Value="29"/>
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="EO1" Type="Event">
				<Attribute Name="YPOSITION" Type="INT" Value="235"/>
			</SubAppEvent>
		</SubAppEventOutputs>
		<InputVars>
			<VarDeclaration Name="Output" Type="logiBUS::io::DQ::logiBUS_DO_S" Comment="Identify the Output Output_Q1..Q8" InitialValue="logiBUS_DO::Invalid"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="E_SR" Type="iec61499::events::E_SR" x="133.33" y="-800">
		</FB>
		<FB Name="QX" Type="logiBUS::io::DQ::logiBUS_QX" x="2100" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_SWITCH" Type="iec61499::events::E_SWITCH" x="1333.33" y="33.33">
		</FB>
		<EventConnections>
			<Connection Source="E_SR.EO" Destination="QX.REQ"/>
			<Connection Source="E_SR.EO" Destination="E_SWITCH.EI" dx1="140"/>
			<Connection Source="SET" Destination="E_SR.S" dx1="473.33">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="RESET" Destination="E_SR.R" dx1="406.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="E_SWITCH.EO1" Destination="EO1" dx1="1453.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_SR.Q" Destination="QX.OUT" dx1="753.33"/>
			<Connection Source="E_SR.Q" Destination="E_SWITCH.G" dx1="73.33"/>
			<Connection Source="Output" Destination="QX.Output" dx1="3540">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
