<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_010b2" Comment="Toggle Flip-Flop mit IE SoftKey_F1 SK_RELEASED">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="isobus::UT::io::Softkey::SoftKeyActivationCode::SK_RELEASED"/>
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QX" x="-3900" y="-100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="SoftKey_UP_F1" Type="isobus::UT::io::Softkey::Softkey_IE" x="-7200" y="-200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_F1"/>
			<Parameter Name="InputEvent" Value="SK_RELEASED"/>
		</FB>
		<FB Name="E_T_FF" Type="iec61499::events::E_T_FF" x="-5560" y="0">
		</FB>
		<EventConnections>
			<Connection Source="SoftKey_UP_F1.IND" Destination="E_T_FF.CLK"/>
			<Connection Source="E_T_FF.EO" Destination="DigitalOutput_Q1.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_T_FF.Q" Destination="DigitalOutput_Q1.OUT" dx1="580"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
