<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_003a" Comment="DigitalInput_I1/_I2 auf DigitalOutput_Q1/_I2 - mit typed Subapp">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="F1" Type="Uebungen::Uebung_003a_sub" x="100" y="700">
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</SubApp>
		<SubApp Name="F2" Type="Uebungen::Uebung_003a_sub" x="100" y="1200">
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</SubApp>
	</SubAppNetwork>
</SubAppType>
