<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_152" Comment="Impulszähler &amp; PI Regler">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I3"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::PI::logiBUS_PI::PulseInput_I8"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="logiBUS_PI_ID" Type="logiBUS::io::PI::logiBUS_PI_ID" x="-4700" y="400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="PulseInput_I8"/>
			<Parameter Name="ImpulseDelta" Value="100"/>
			<Parameter Name="TimeDelta" Value="50000"/>
		</FB>
		<FB Name="FT_DERIV" Type="OSCAT::Basic::POUs::Engineering::Control::FT_DERIV_10" x="400" y="-1700">
			<Parameter Name="K" Value="9"/>
			<Parameter Name="Faktor" Value="1.0"/>
			<Parameter Name="run" Value="TRUE"/>
		</FB>
		<FB Name="F_DWORD_TO_UDINT" Type="iec61131::conversion::F_DWORD_TO_UDINT" x="-2900" y="700">
		</FB>
		<FB Name="F_UDINT_TO_REAL" Type="iec61131::conversion::F_UDINT_TO_REAL" x="-1300" y="700">
		</FB>
		<FB Name="PWMOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QD_PWM" x="7300" y="1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="CTRL_PI" Type="OSCAT::Basic::POUs::Engineering::Control::CTRL_PI" x="2600" y="1300">
			<Parameter Name="SET" Value="16.0"/>
			<Parameter Name="SUP" Value="0.0"/>
			<Parameter Name="OFS" Value="0.0"/>
			<Parameter Name="M_I" Value="8184.0"/>
			<Parameter Name="KP" Value="10.0"/>
			<Parameter Name="KI" Value="10.0"/>
			<Parameter Name="LL" Value="0.0"/>
			<Parameter Name="LH" Value="8184.0"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IE" x="-4800" y="1800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="E_T_FF" Type="iec61499::events::E_T_FF" x="-2300" y="1900">
		</FB>
		<FB Name="F_LREAL_TO_UDINT" Type="iec61131::conversion::F_LREAL_TO_UDINT" x="3900" y="1300">
		</FB>
		<FB Name="F_UDINT_TO_DWORD" Type="iec61131::conversion::F_UDINT_TO_DWORD" x="5500" y="1300">
		</FB>
		<FB Name="E_CYCLE" Type="iec61499::events::E_CYCLE" x="-6500" y="500">
			<Parameter Name="DT" Value="T#200ms"/>
		</FB>
		<FB Name="DigitalInput_I2" Type="logiBUS::io::DI::logiBUS_IE" x="-8400" y="0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="DigitalInput_I3" Type="logiBUS::io::DI::logiBUS_IE" x="-8400" y="1000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I3"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<EventConnections>
			<Connection Source="logiBUS_PI_ID.IND" Destination="F_DWORD_TO_UDINT.REQ" dx1="406.67"/>
			<Connection Source="F_DWORD_TO_UDINT.CNF" Destination="F_UDINT_TO_REAL.REQ"/>
			<Connection Source="F_UDINT_TO_REAL.CNF" Destination="FT_DERIV.REQ" dx1="146.67"/>
			<Connection Source="FT_DERIV.CNF" Destination="CTRL_PI.REQ" dx1="1266.67"/>
			<Connection Source="DigitalInput_I1.IND" Destination="E_T_FF.CLK" dx1="806.67"/>
			<Connection Source="E_T_FF.EO" Destination="CTRL_PI.REQ" dx1="280"/>
			<Connection Source="CTRL_PI.CNF" Destination="F_LREAL_TO_UDINT.REQ"/>
			<Connection Source="F_LREAL_TO_UDINT.CNF" Destination="F_UDINT_TO_DWORD.REQ"/>
			<Connection Source="F_UDINT_TO_DWORD.CNF" Destination="PWMOutput_Q1.REQ" dx1="380"/>
			<Connection Source="DigitalInput_I2.IND" Destination="E_CYCLE.START" dx1="533.33"/>
			<Connection Source="DigitalInput_I3.IND" Destination="E_CYCLE.STOP" dx1="360"/>
			<Connection Source="logiBUS_PI_ID.CNF" Destination="F_DWORD_TO_UDINT.REQ" dx1="406.67"/>
			<Connection Source="E_CYCLE.EO" Destination="logiBUS_PI_ID.REQ" dx1="80"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="logiBUS_PI_ID.IN" Destination="F_DWORD_TO_UDINT.IN" dx1="406.67"/>
			<Connection Source="F_DWORD_TO_UDINT.OUT" Destination="F_UDINT_TO_REAL.IN"/>
			<Connection Source="F_UDINT_TO_REAL.OUT" Destination="FT_DERIV.in" dx1="353.33"/>
			<Connection Source="FT_DERIV.out" Destination="CTRL_PI.ACT" dx1="766.67"/>
			<Connection Source="E_T_FF.Q" Destination="CTRL_PI.MAN" dx1="3646.67"/>
			<Connection Source="CTRL_PI.Y" Destination="F_LREAL_TO_UDINT.IN" dx1="340"/>
			<Connection Source="F_LREAL_TO_UDINT.OUT" Destination="F_UDINT_TO_DWORD.IN"/>
			<Connection Source="F_UDINT_TO_DWORD.OUT" Destination="PWMOutput_Q1.OUT" dx1="380"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
