<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_010b8_AX" Comment="Toggle Flip-Flop mit IE Button_A1 BT_PRESSED_LATCHED">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Moritz Ortmeier" Date="2026-01-15">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::Button_A1"/>
		<Import declaration="isobus::UT::io::Button::ButtonActivationCode::BT_PRESSED_LATCHED"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="-3900" y="-100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="Button_A1" Type="isobus::UT::io::Button::Button_IE" x="-7200" y="-200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="Button_A1"/>
			<Parameter Name="InputEvent" Value="BT_PRESSED_LATCHED"/>
		</FB>
		<FB Name="AX_T_FF" Type="adapter::events::unidirectional::AX_T_FF" x="-5560" y="0">
		</FB>
		<EventConnections>
			<Connection Source="Button_A1.IND" Destination="AX_T_FF.CLK" dx1="293.33"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="AX_T_FF.Q" Destination="DigitalOutput_Q1.OUT" dx1="580"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
