<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_005_AX" Comment="Toggle Flip-Flop mit IX">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Moritz Ortmeier" Date="2026-01-13">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="-1400" y="-600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="AX_T_FF" Type="adapter::events::unidirectional::AX_T_FF" x="-3100" y="-200">
		</FB>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IXA" x="-6000" y="-600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="AX_SWITCH" Type="adapter::events::unidirectional::AX_SWITCH" x="-4500" y="-300">
		</FB>
		<EventConnections>
			<Connection Source="AX_SWITCH.EO1" Destination="AX_T_FF.CLK"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="AX_T_FF.Q" Destination="DigitalOutput_Q1.OUT"/>
			<Connection Source="DigitalInput_I1.IN" Destination="AX_SWITCH.G"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
