<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_010c_AX" Comment="SoftKey_F1 auf DigitalOutput_Q1 mit GreenWhiteBackground">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Moritz Ortmeier" Date="2026-01-15">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="-1400" y="-300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="SoftKey_F1" Type="isobus::UT::io::Softkey::Softkey_IXA" x="-4900" y="-600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId" Value="SoftKey_F1"/>
		</FB>
		<SubApp Name="GreenWhiteBackground_AX" Type="MyLib::sys::GreenWhiteBackground_AX" x="-1700" y="800">
			<Parameter Name="u16ObjId" Value="SoftKey_F1"/>
		</SubApp>
		<Comment Comment="Nachteil: &#10;DefaultPool::SoftKey_F1 &#10;muss 2x angegeben werden" x="-4800" y="700" width="1400" height="700"/>
		<FB Name="AX_SPLIT_2" Type="adapter::events::unidirectional::AX_SPLIT_2" x="-3400" y="200">
		</FB>
		<AdapterConnections>
			<Connection Source="SoftKey_F1.IN" Destination="AX_SPLIT_2.IN" dx1="511.76"/>
			<Connection Source="AX_SPLIT_2.OUT1" Destination="DigitalOutput_Q1.OUT" dx1="488.24"/>
			<Connection Source="AX_SPLIT_2.OUT2" Destination="GreenWhiteBackground_AX.DI1" dx1="341.18"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
