<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_002_AX" Comment="DigitalInput_I1 auf DigitalOutput_Q1/_Q2, mit Plug and Socket ">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IXA" x="100" y="-400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="4000" y="-700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalOutput_Q2" Type="logiBUS::io::DQ::logiBUS_QXA" x="4000" y="300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q2"/>
		</FB>
		<FB Name="AX_SPLIT" Type="adapter::events::unidirectional::AX_SPLIT_2" x="1800" y="100">
		</FB>
		<AdapterConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="AX_SPLIT.IN" dx1="280"/>
			<Connection Source="AX_SPLIT.OUT1" Destination="DigitalOutput_Q1.OUT" dx1="80"/>
			<Connection Source="AX_SPLIT.OUT2" Destination="DigitalOutput_Q2.OUT" dx1="80"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
