<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_020e_AX" Comment="DigitalInput_I1 auf DigitalOutput_Q1; AX_TOF; Ausschaltverzögert">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="-5200" y="500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IXA" x="-8900" y="500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="AX_TOF" Type="adapter::events::unidirectional::timers::AX_TOF" x="-7000" y="800">
			<Parameter Name="PT" Value="T#5s"/>
		</FB>
		<AdapterConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="AX_TOF.IN" dx1="546.67"/>
			<Connection Source="AX_TOF.Q" Destination="DigitalOutput_Q1.OUT" dx1="613.33"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
