<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_004a7_AX" Comment="SR und T-Flip-Flop mit IE und E_REND (Rendezvous)">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I3"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="5300" y="2300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="logiBUS::io::DI::logiBUS_IE" x="200" y="300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="E_T_FF" Type="adapter::events::unidirectional::AX_T_FF_SR" x="3100" y="2600">
		</FB>
		<FB Name="E_REND" Type="iec61499::events::E_REND" x="2100" y="2100">
		</FB>
		<FB Name="DigitalInput_CLK_I2" Type="logiBUS::io::DI::logiBUS_IE" x="200" y="1400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="DigitalInput_CLK_I3" Type="logiBUS::io::DI::logiBUS_IE" x="200" y="2600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I3"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="E_REND.EI1" dx1="933.33"/>
			<Connection Source="DigitalInput_CLK_I2.IND" Destination="E_REND.EI2" dx1="713.33"/>
			<Connection Source="E_REND.EO" Destination="E_T_FF.CLK" dx1="186.67"/>
			<Connection Source="DigitalInput_CLK_I3.IND" Destination="E_T_FF.R" dx1="953.33"/>
			<Connection Source="DigitalInput_CLK_I3.IND" Destination="E_REND.R" dx1="506.67"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="E_T_FF.Q" Destination="DigitalOutput_Q1.OUT" dx1="746.67"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
