<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_020g_AX" Comment="DigitalInput_I1 auf DigitalOutput_Q1; AX_TONOF; Ein-/Ausschaltverzögert">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-01-16">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IXA" x="-8900" y="400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="AX_TONOF" Type="adapter::events::unidirectional::timers::AX_TONOF" x="-7100" y="600">
			<Parameter Name="PT_ON" Value="T#5S"/>
			<Parameter Name="PT_OFF" Value="T#5S"/>
		</FB>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="-5100" y="500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<AdapterConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="AX_TONOF.IN" dx1="406.67"/>
			<Connection Source="AX_TONOF.Q" Destination="DigitalOutput_Q1.OUT" dx1="520"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
