<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_007a3_AX" Comment="Blinker mit E_CYCLE, E_SWITCH und E_SR">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Moritz Ortmeier" Date="2026-01-14">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="-900" y="-100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="AE_CYCLE" Type="adapter::events::unidirectional::timers::AE_CYCLE" x="-7100" y="-300">
			<Parameter Name="DT" Value="T#1s"/>
		</FB>
		<FB Name="START" Type="logiBUS::io::DI::logiBUS_IE" x="-9000" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="STOP" Type="logiBUS::io::DI::logiBUS_IE" x="-9000" y="200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<Comment Comment="Vorteil:&#10;dieser Blinker bleibt immer auf AUS stehen" x="-7100" y="1400" width="1800" height="700"/>
		<FB Name="E_SR" Type="adapter::events::unidirectional::AX_SR" x="-3500" y="0">
		</FB>
		<FB Name="E_SWITCH" Type="adapter::events::unidirectional::AX_SWITCH" x="-4900" y="0">
		</FB>
		<FB Name="AX_AE_MERGE" Type="adapter::events::unidirectional::AX_AE_MERGE" x="-6100" y="-400">
		</FB>
		<FB Name="AX_SPLIT_2" Type="adapter::events::unidirectional::AX_SPLIT_2" x="-2600" y="300">
		</FB>
		<EventConnections>
			<Connection Source="START.IND" Destination="AE_CYCLE.START" dx1="526.67"/>
			<Connection Source="STOP.IND" Destination="AE_CYCLE.STOP" dx1="526.67"/>
			<Connection Source="E_SWITCH.EO0" Destination="E_SR.S"/>
			<Connection Source="E_SWITCH.EO1" Destination="E_SR.R"/>
			<Connection Source="STOP.IND" Destination="E_SR.R" dx1="4026.67"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="E_SR.Q" Destination="AX_SPLIT_2.IN" dx1="300"/>
			<Connection Source="AX_SPLIT_2.OUT1" Destination="AX_AE_MERGE.IN_AX" dx1="70.59" dx2="70.59" dy="-1286.67"/>
			<Connection Source="AE_CYCLE.EO" Destination="AX_AE_MERGE.IN_AE" dx1="160"/>
			<Connection Source="AX_AE_MERGE.OUT" Destination="E_SWITCH.G" dx1="405.88"/>
			<Connection Source="AX_SPLIT_2.OUT2" Destination="DigitalOutput_Q1.OUT" dx1="473.33"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
