<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_010c2_AX" Comment="SoftKey_F1 auf DigitalOutput_Q1 mit GreenWhiteBackground mit Subapp">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Moritz Ortmeier" Date="2026-01-15">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="Uebungen::const::UT::DefaultPool::SoftKey_F1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO_S"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="Uebung_10c2_sub_AX" x="-4600" y="-500">
			<SubAppInterfaceList>
				<InputVars>
					<VarDeclaration Name="u16ObjId" Type="UINT" Comment="Object ID" InitialValue="SoftKey_F1"/>
					<VarDeclaration Name="Output" Type="logiBUS::io::DQ::logiBUS_DO_S" Comment="Identify the Output Output_Q1..Q8" InitialValue="logiBUS_DO::Output_Q1"/>
				</InputVars>
			</SubAppInterfaceList>
			<SubAppNetwork>
				<SubApp Name="GreenWhiteBackground_AX" Type="MyLib::sys::GreenWhiteBackground_AX" x="3200" y="1200">
				</SubApp>
				<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="3200" y="200">
					<Parameter Name="QI" Value="TRUE"/>
					<Parameter Name="PARAMS" Value="">
						<Attribute Name="Visible" Value="false"/>
					</Parameter>
				</FB>
				<FB Name="SoftKey_F1" Type="isobus::UT::io::Softkey::Softkey_IXA" x="200" y="0">
					<Parameter Name="QI" Value="TRUE"/>
				</FB>
				<FB Name="AX_SPLIT_2" Type="adapter::events::unidirectional::AX_SPLIT_2" x="1500" y="700">
				</FB>
				<DataConnections>
					<Connection Source="u16ObjId" Destination="SoftKey_F1.u16ObjId" dx1="2446.67">
						<Attribute Name="Visible" Value="false"/>
					</Connection>
					<Connection Source="u16ObjId" Destination="GreenWhiteBackground_AX.u16ObjId" dx1="3893.33">
						<Attribute Name="Visible" Value="false"/>
					</Connection>
					<Connection Source="Output" Destination="DigitalOutput_Q1.Output" dx1="4046.67">
						<Attribute Name="Visible" Value="false"/>
					</Connection>
				</DataConnections>
				<AdapterConnections>
					<Connection Source="SoftKey_F1.IN" Destination="AX_SPLIT_2.IN" dx1="364.71"/>
					<Connection Source="AX_SPLIT_2.OUT1" Destination="DigitalOutput_Q1.OUT" dx1="388.24"/>
					<Connection Source="AX_SPLIT_2.OUT2" Destination="GreenWhiteBackground_AX.DI1" dx1="388.24"/>
				</AdapterConnections>
			</SubAppNetwork>
			<Attribute Name="width" Type="LREAL" Value="200"/>
			<Attribute Name="height" Type="LREAL" Value="100"/>
		</SubApp>
	</SubAppNetwork>
</SubAppType>
