<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_002a3_AX" Comment="DigitalInput_I1/_I2 mit OR auf DigitalOutput_Q1, mit Plug and Socket">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IXA" x="400" y="-200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="4000" y="100">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="AX_OR_2" Type="adapter::booleanOperators::AX_OR_2" x="2200" y="600">
		</FB>
		<FB Name="DigitalInput_I2" Type="logiBUS::io::DI::logiBUS_IXA" x="400" y="700">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
		</FB>
		<AdapterConnections>
			<Connection Source="AX_OR_2.OUT" Destination="DigitalOutput_Q1.OUT" dx1="420"/>
			<Connection Source="DigitalInput_I1.IN" Destination="AX_OR_2.IN1" dx1="926.67"/>
			<Connection Source="DigitalInput_I2.IN" Destination="AX_OR_2.IN2" dx1="926.67"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
