<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_008_AX" Comment="Blinker mit E_CYCLE, E_SWITCH und E_SR">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Moritz Ortmeier" Date="2026-01-14">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="1700" y="-200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="AE_CYCLE" Type="adapter::events::unidirectional::timers::AE_CYCLE" x="-5600" y="-700">
			<Parameter Name="DT" Value="T#1s"/>
		</FB>
		<FB Name="E_SWITCH" Type="adapter::events::unidirectional::AX_SWITCH" x="-2300" y="-700">
		</FB>
		<FB Name="AX_SR" Type="adapter::events::unidirectional::AX_SR" x="-700" y="-700">
		</FB>
		<FB Name="AX_SPLIT_2" Type="adapter::events::unidirectional::AX_SPLIT_2" x="200" y="200">
		</FB>
		<FB Name="AX_AE_MERGE" Type="adapter::events::unidirectional::AX_AE_MERGE" x="-4000" y="-200">
		</FB>
		<EventConnections>
			<Connection Source="E_SWITCH.EO0" Destination="AX_SR.S"/>
			<Connection Source="E_SWITCH.EO1" Destination="AX_SR.R"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="AX_SR.Q" Destination="AX_SPLIT_2.IN" dx1="205.88"/>
			<Connection Source="AX_SPLIT_2.OUT1" Destination="AX_AE_MERGE.IN_AX" dx1="70.59" dx2="70.59" dy="-1286.67"/>
			<Connection Source="AE_CYCLE.EO" Destination="AX_AE_MERGE.IN_AE" dx1="435.29"/>
			<Connection Source="AX_AE_MERGE.OUT" Destination="E_SWITCH.G" dx1="488.24"/>
			<Connection Source="AX_SPLIT_2.OUT2" Destination="DigitalOutput_Q1.OUT" dx1="373.33"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
