<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_003a0_AX" Comment="DigitalInput_I1/_I2 auf DigitalOutput_Q1/_I2 - mit untyped Subapp">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Moritz Ortmeier" Date="2026-01-13">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="SubApp" x="-4500" y="-500">
			<SubAppInterfaceList>
			</SubAppInterfaceList>
			<SubAppNetwork>
				<FB Name="DigitalInput_I2" Type="logiBUS::io::DI::logiBUS_IXA" x="0" y="100">
					<Parameter Name="QI" Value="TRUE"/>
					<Parameter Name="Input" Value="Input_I2"/>
				</FB>
				<FB Name="DigitalOutput_Q2" Type="logiBUS::io::DQ::logiBUS_QXA" x="3000" y="100">
					<Parameter Name="QI" Value="TRUE"/>
					<Parameter Name="Output" Value="Output_Q2"/>
				</FB>
				<AdapterConnections>
					<Connection Source="DigitalInput_I2.IN" Destination="DigitalOutput_Q2.OUT"/>
				</AdapterConnections>
			</SubAppNetwork>
			<Attribute Name="width" Type="LREAL" Value="200"/>
			<Attribute Name="height" Type="LREAL" Value="100"/>
		</SubApp>
		<SubApp Name="SubApp_1" x="-4500" y="-900">
			<SubAppInterfaceList>
			</SubAppInterfaceList>
			<SubAppNetwork>
				<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="3000" y="100">
					<Parameter Name="QI" Value="TRUE"/>
					<Parameter Name="Output" Value="Output_Q1"/>
				</FB>
				<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IXA" x="0" y="100">
					<Parameter Name="QI" Value="TRUE"/>
					<Parameter Name="Input" Value="Input_I1"/>
				</FB>
				<AdapterConnections>
					<Connection Source="DigitalInput_I1.IN" Destination="DigitalOutput_Q1.OUT"/>
				</AdapterConnections>
			</SubAppNetwork>
			<Attribute Name="width" Type="LREAL" Value="200"/>
			<Attribute Name="height" Type="LREAL" Value="100"/>
		</SubApp>
	</SubAppNetwork>
</SubAppType>
