<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_160_AX" Comment="Motor Links/Rechtslauf">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q5"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q56"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q6"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IXA" x="-5200" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="DigitalOutput_Q5" Type="logiBUS::io::DQ::logiBUS_QXA" x="-1400" y="-800">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q5"/>
		</FB>
		<FB Name="DigitalOutput_Q6" Type="logiBUS::io::DQ::logiBUS_QXA" x="-1400" y="1400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q6"/>
		</FB>
		<FB Name="DigitalInput_I2" Type="logiBUS::io::DI::logiBUS_IXA" x="-5200" y="1400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
		</FB>
		<FB Name="AX_OR_2" Type="adapter::booleanOperators::AX_OR_2" x="-2700" y="800">
		</FB>
		<FB Name="DigitalOutput_Q56" Type="logiBUS::io::DQ::logiBUS_QXA" x="-1400" y="300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q56"/>
		</FB>
		<FB Name="AX_SPLIT_2_A" Type="adapter::events::unidirectional::AX_SPLIT_2" x="-4000" y="-300">
		</FB>
		<FB Name="AX_SPLIT_2_B" Type="adapter::events::unidirectional::AX_SPLIT_2" x="-4000" y="1900">
		</FB>
		<AdapterConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="AX_SPLIT_2_A.IN" dx1="200"/>
			<Connection Source="AX_SPLIT_2_A.OUT1" Destination="DigitalOutput_Q5.OUT" dx1="920"/>
			<Connection Source="DigitalInput_I2.IN" Destination="AX_SPLIT_2_B.IN" dx1="200"/>
			<Connection Source="AX_SPLIT_2_B.OUT2" Destination="DigitalOutput_Q6.OUT" dx1="920"/>
			<Connection Source="AX_OR_2.OUT" Destination="DigitalOutput_Q56.OUT" dx1="340"/>
			<Connection Source="AX_SPLIT_2_A.OUT2" Destination="AX_OR_2.IN1" dx1="273.33"/>
			<Connection Source="AX_SPLIT_2_B.OUT1" Destination="AX_OR_2.IN2" dx1="273.33"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
