<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_020d_AX" Comment="DigitalInput_I1 auf DigitalOutput_Q1; TOF Ausschaltverzögert; aufgelöst">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2026-01-16">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IXA" x="-8700" y="400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="AX_SWITCH" Type="adapter::events::unidirectional::AX_SWITCH" x="-7400" y="600">
		</FB>
		<FB Name="AX_RS" Type="adapter::events::unidirectional::AX_RS" x="-4800" y="600">
		</FB>
		<FB Name="E_DELAY" Type="iec61499::events::E_DELAY" x="-5800" y="200">
			<Parameter Name="DT" Value="T#2S"/>
		</FB>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="-3400" y="500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<EventConnections>
			<Connection Source="AX_SWITCH.EO1" Destination="AX_RS.S" dx1="400"/>
			<Connection Source="AX_SWITCH.EO0" Destination="E_DELAY.START" dx1="453.33"/>
			<Connection Source="E_DELAY.EO" Destination="AX_RS.R" dx1="193.33"/>
			<Connection Source="AX_SWITCH.EO1" Destination="E_DELAY.STOP" dx1="600"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="DigitalInput_I1.IN" Destination="AX_SWITCH.G" dx1="300"/>
			<Connection Source="AX_RS.Q" Destination="DigitalOutput_Q1.OUT"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
