<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_004a8_AX" Comment="mit E_SPLIT_2">
	<Identification Standard="61499-2" Description="Copyright (c) 2026 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Moritz Ortmeier" Date="2026-07-13">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI_Events::BUTTON_SINGLE_CLICK"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q2"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="-4000" y="-300">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_CLK_I1" Type="logiBUS::io::DI::logiBUS_IE" x="-8533.33" y="-6.66">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Input" Value="Input_I1"/>
			<Parameter Name="InputEvent" Value="BUTTON_SINGLE_CLICK"/>
		</FB>
		<FB Name="AX_T_FF_Q1" Type="adapter::events::unidirectional::AX_T_FF" x="-5600" y="0">
		</FB>
		<FB Name="AX_T_FF_Q2" Type="adapter::events::unidirectional::AX_T_FF" x="-5600" y="1400">
		</FB>
		<FB Name="DigitalOutput_Q2" Type="logiBUS::io::DQ::logiBUS_QXA" x="-4000" y="1100">
			<Parameter Name="QI" Value="TRUE">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="PARAMS" Value="">
				<Attribute Name="Visible" Value="false"/>
			</Parameter>
			<Parameter Name="Output" Value="Output_Q2"/>
		</FB>
		<FB Name="E_SPLIT_2" Type="iec61499::events::E_SPLIT_2" x="-7100" y="200">
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_CLK_I1.IND" Destination="E_SPLIT_2.EI" dx1="476.47"/>
			<Connection Source="E_SPLIT_2.EO1" Destination="AX_T_FF_Q1.CLK" dx1="411.76"/>
			<Connection Source="E_SPLIT_2.EO2" Destination="AX_T_FF_Q2.CLK" dx1="411.76"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="AX_T_FF_Q1.Q" Destination="DigitalOutput_Q1.OUT"/>
			<Connection Source="AX_T_FF_Q2.Q" Destination="DigitalOutput_Q2.OUT"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
