<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Uebung_090a1_AX" Comment="Beispiel für AX_MUX_2">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Uebungen">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I2"/>
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I4"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="F_MUX_2" Type="adapter::selection::unidirectional::AX_MUX_2" x="2700" y="3700">
		</FB>
		<FB Name="DigitalInput_I4" Type="logiBUS::io::DI::logiBUS_IX" x="-1400" y="3500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I4"/>
		</FB>
		<FB Name="F_BOOL_TO_UINT_I4" Type="iec61131::conversion::F_BOOL_TO_UINT" x="-300" y="3700">
		</FB>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="4500" y="3400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IXA" x="-1400" y="4400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="DigitalInput_I2" Type="logiBUS::io::DI::logiBUS_IXA" x="-1400" y="5500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I2"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I4.IND" Destination="F_BOOL_TO_UINT_I4.REQ" dx1="173.33"/>
			<Connection Source="F_BOOL_TO_UINT_I4.CNF" Destination="F_MUX_2.REQ"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="DigitalInput_I4.IN" Destination="F_BOOL_TO_UINT_I4.IN" dx1="173.33"/>
			<Connection Source="F_BOOL_TO_UINT_I4.OUT" Destination="F_MUX_2.K"/>
		</DataConnections>
		<AdapterConnections>
			<Connection Source="DigitalInput_I2.IN" Destination="F_MUX_2.IN2" dx1="2360"/>
			<Connection Source="DigitalInput_I1.IN" Destination="F_MUX_2.IN1" dx1="1653.33"/>
			<Connection Source="F_MUX_2.OUT" Destination="DigitalOutput_Q1.OUT" dx1="493.33"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
