<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Versuch_403" Comment="Versuch Array Summe">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Versuche">
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="GET_AT_INDEX" Type="eclipse4diac::convert::GET_AT_INDEX" x="2126.67" y="6320">
			<Parameter Name="INDEX" Value="0"/>
		</FB>
		<FB Name="F_MOVE" Type="iec61131::selection::F_MOVE" x="3286.67" y="6373.33">
			<Attribute Name="DataType" Value="INT"/>
		</FB>
		<FB Name="CountOfElements" Type="eclipse4diac::convert::CountOfElements" x="1786.67" y="7300">
		</FB>
		<FB Name="F_UPPER_BOUND" Type="eclipse4diac::convert::F_UPPER_BOUND" x="2126.67" y="5340">
			<Parameter Name="DIM" Value="1"/>
		</FB>
		<FB Name="F_LOWER_BOUND" Type="eclipse4diac::convert::F_LOWER_BOUND" x="2060" y="3560">
			<Parameter Name="DIM" Value="1"/>
		</FB>
		<FB Name="VALUES2ARRAY_8_INT" Type="eclipse4diac::convert::VALUES2ARRAY_8_INT" x="413.33" y="5340">
			<Parameter Name="IN_1" Value="1"/>
			<Parameter Name="IN_2" Value="22"/>
			<Parameter Name="IN_3" Value="333"/>
			<Parameter Name="IN_4" Value="4444"/>
			<Parameter Name="IN_5" Value="333"/>
			<Parameter Name="IN_6" Value="22"/>
			<Parameter Name="IN_7" Value="1"/>
			<Parameter Name="IN_8" Value="0"/>
		</FB>
		<FB Name="ARRAY2ARRAY_8_INT" Type="eclipse4diac::convert::ARRAY2ARRAY_8_INT" x="1786.67" y="4540">
		</FB>
		<FB Name="CountOfElements_1" Type="eclipse4diac::convert::CountOfElements" x="3700" y="4600">
		</FB>
		<EventConnections>
			<Connection Source="GET_AT_INDEX.CNF" Destination="F_MOVE.REQ" dx1="66.67"/>
			<Connection Source="VALUES2ARRAY_8_INT.CNF" Destination="GET_AT_INDEX.REQ" dx1="133.33"/>
			<Connection Source="VALUES2ARRAY_8_INT.CNF" Destination="CountOfElements.REQ" dx1="133.33"/>
			<Connection Source="VALUES2ARRAY_8_INT.CNF" Destination="F_LOWER_BOUND.REQ" dx1="133.33"/>
			<Connection Source="VALUES2ARRAY_8_INT.CNF" Destination="F_UPPER_BOUND.REQ"/>
			<Connection Source="VALUES2ARRAY_8_INT.CNF" Destination="ARRAY2ARRAY_8_INT.REQ" dx1="133.33"/>
			<Connection Source="ARRAY2ARRAY_8_INT.CNF" Destination="CountOfElements_1.REQ" dx1="413.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="GET_AT_INDEX.OUT" Destination="F_MOVE.IN" dx1="66.67"/>
			<Connection Source="VALUES2ARRAY_8_INT.OUT" Destination="GET_AT_INDEX.IN_ARRAY" dx1="66.67"/>
			<Connection Source="VALUES2ARRAY_8_INT.OUT" Destination="F_UPPER_BOUND.IN_ARRAY"/>
			<Connection Source="VALUES2ARRAY_8_INT.OUT" Destination="F_LOWER_BOUND.IN_ARRAY" dx1="66.67"/>
			<Connection Source="VALUES2ARRAY_8_INT.OUT" Destination="CountOfElements.IN_ARRAY" dx1="66.67"/>
			<Connection Source="VALUES2ARRAY_8_INT.OUT" Destination="ARRAY2ARRAY_8_INT.IN" dx1="66.67"/>
			<Connection Source="ARRAY2ARRAY_8_INT.OUT" Destination="CountOfElements_1.IN_ARRAY" dx1="413.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
