<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Versuch_404" Comment="Versuch Array Summe">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Versuche">
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="INIT_ARR_8_INT" Type="logiBUS::utils::generate::INIT_ARR_0008_INT" x="800" y="2600">
			<Parameter Name="D1" Value="[0, 1, 22, 333, 4444, 333, 22, 1]"/>
		</FB>
		<FB Name="GET_AT_INDEX" Type="eclipse4diac::convert::GET_AT_INDEX" x="2700" y="2700">
			<Parameter Name="INDEX" Value="3"/>
		</FB>
		<FB Name="SUM" Type="logiBUS::utils::dyn_arr::SUM" x="2500" y="3900">
		</FB>
		<EventConnections>
			<Connection Source="INIT_ARR_8_INT.INITO" Destination="GET_AT_INDEX.REQ" dx1="406.67"/>
			<Connection Source="INIT_ARR_8_INT.INITO" Destination="SUM.REQ" dx1="306.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="INIT_ARR_8_INT.D1" Destination="GET_AT_INDEX.IN_ARRAY" dx1="406.67"/>
			<Connection Source="INIT_ARR_8_INT.D1" Destination="SUM.A" dx1="80"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
