<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Versuch_103c3" Comment="DigitalInput_I1 auf DigitalOutput_Q1, mit Plug and Socket und DEMUX">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Versuche">
		<Import declaration="logiBUS::io::DI::logiBUS_DI::Input_I1"/>
		<Import declaration="logiBUS::io::DQ::logiBUS_DO::Output_Q1"/>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DigitalInput_I1" Type="logiBUS::io::DI::logiBUS_IXA" x="2800" y="0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Input" Value="Input_I1"/>
		</FB>
		<FB Name="DigitalOutput_Q1" Type="logiBUS::io::DQ::logiBUS_QXA" x="7000" y="-300">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="Output" Value="Output_Q1"/>
		</FB>
		<FB Name="AX_DEMUX_3" Type="adapter::selection::unidirectional::AX_DEMUX_3" x="5000" y="0">
			<Parameter Name="K" Value="0"/>
		</FB>
		<EventConnections>
			<Connection Source="DigitalInput_I1.INITO" Destination="AX_DEMUX_3.REQ"/>
		</EventConnections>
		<AdapterConnections>
			<Connection Source="AX_DEMUX_3.OUT1" Destination="DigitalOutput_Q1.OUT"/>
			<Connection Source="DigitalInput_I1.IN" Destination="AX_DEMUX_3.IN" dx1="700"/>
		</AdapterConnections>
	</SubAppNetwork>
</SubAppType>
