<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Versuch_409" Comment="Versuch Array Summe">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Versuche">
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SUM" Type="logiBUS::utils::dyn_arr::SUM" x="4400" y="4000">
		</FB>
		<FB Name="INIT_ARR_8_INT" Type="logiBUS::utils::generate::INIT_ARR_0008_INT" x="1320" y="4006.67">
			<Parameter Name="D1" Value="[44, 0, 5, 0, 7, 8, 0, 0]"/>
		</FB>
		<DataConnections>
			<Connection Source="INIT_ARR_8_INT.D1" Destination="SUM.A" dx1="66.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
