<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Versuch_401" Comment="Versuch Array Summe">
	<Identification Standard="61499-2" Description="Copyright (c) 2023 Meisterschulen am Ostbahnhof  &#10; &#10;This program and the accompanying materials are made  &#10;available under the terms of the Eclipse Public License 2.0  &#10;which is available at https://www.eclipse.org/legal/epl-2.0/  &#10; &#10;SPDX-License-Identifier: EPL-2.0">
	</Identification>
	<VersionInfo Organization="Meisterschulen am Ostbahnhof" Version="1.0" Author="Franz Höpfinger" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo packageName="Versuche">
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SUM" Type="logiBUS::utils::dyn_arr::SUM" x="3013.33" y="2640">
		</FB>
		<FB Name="INIT_ARR_8_INT" Type="logiBUS::utils::generate::INIT_ARR_0008_INT" x="800" y="2600">
			<Parameter Name="D1" Value="[44, 0, 5, 0, 7, 8, 0, 0]"/>
		</FB>
		<FB Name="GET_AT_INDEX" Type="eclipse4diac::convert::GET_AT_INDEX" x="3286.67" y="3540">
			<Parameter Name="INDEX" Value="0"/>
		</FB>
		<FB Name="F_MOVE" Type="iec61131::selection::F_MOVE" x="4446.67" y="3593.33">
			<Attribute Name="DataType" Value="INT"/>
		</FB>
		<FB Name="ARR_MIN" Type="logiBUS::utils::dyn_arr::ARR_MIN" x="2880" y="5420">
		</FB>
		<FB Name="ARR_MAX" Type="logiBUS::utils::dyn_arr::ARR_MAX" x="3013.33" y="1740">
		</FB>
		<FB Name="AVG" Type="logiBUS::utils::dyn_arr::AVG" x="2946.67" y="4520">
		</FB>
		<FB Name="CountOfElements" Type="eclipse4diac::convert::CountOfElements" x="2900" y="-400">
		</FB>
		<FB Name="F_UPPER_BOUND" Type="eclipse4diac::convert::F_UPPER_BOUND" x="2900" y="900">
			<Parameter Name="DIM" Value="1"/>
		</FB>
		<FB Name="F_LOWER_BOUND" Type="eclipse4diac::convert::F_LOWER_BOUND" x="2900" y="200">
			<Parameter Name="DIM" Value="1"/>
		</FB>
		<EventConnections>
			<Connection Source="INIT_ARR_8_INT.INITO" Destination="SUM.REQ" dx1="133.33"/>
			<Connection Source="GET_AT_INDEX.CNF" Destination="F_MOVE.REQ" dx1="66.67"/>
			<Connection Source="INIT_ARR_8_INT.INITO" Destination="GET_AT_INDEX.REQ" dx1="133.33"/>
			<Connection Source="INIT_ARR_8_INT.INITO" Destination="CountOfElements.REQ" dx1="133.33"/>
			<Connection Source="INIT_ARR_8_INT.INITO" Destination="ARR_MAX.REQ" dx1="133.33"/>
			<Connection Source="INIT_ARR_8_INT.INITO" Destination="AVG.REQ" dx1="133.33"/>
			<Connection Source="INIT_ARR_8_INT.INITO" Destination="ARR_MIN.REQ" dx1="106.67"/>
			<Connection Source="INIT_ARR_8_INT.INITO" Destination="F_UPPER_BOUND.REQ" dx1="380"/>
			<Connection Source="INIT_ARR_8_INT.INITO" Destination="F_LOWER_BOUND.REQ" dx1="273.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="INIT_ARR_8_INT.D1" Destination="SUM.A" dx1="633.33"/>
			<Connection Source="INIT_ARR_8_INT.D1" Destination="GET_AT_INDEX.IN_ARRAY" dx1="66.67"/>
			<Connection Source="GET_AT_INDEX.OUT" Destination="F_MOVE.IN" dx1="66.67"/>
			<Connection Source="INIT_ARR_8_INT.D1" Destination="ARR_MIN.A" dx1="66.67"/>
			<Connection Source="INIT_ARR_8_INT.D1" Destination="ARR_MAX.A" dx1="66.67"/>
			<Connection Source="INIT_ARR_8_INT.D1" Destination="AVG.A" dx1="66.67"/>
			<Connection Source="INIT_ARR_8_INT.D1" Destination="CountOfElements.IN_ARRAY" dx1="66.67"/>
			<Connection Source="INIT_ARR_8_INT.D1" Destination="F_UPPER_BOUND.IN_ARRAY" dx1="580"/>
			<Connection Source="INIT_ARR_8_INT.D1" Destination="F_LOWER_BOUND.IN_ARRAY" dx1="580"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
